Update git submodules
* Update frameworks/base from branch 'master'
  to 73c4e18d80f9ee6c69d459c0543edf6a6147b071
  - Merge "Prefer `= delete` in place of DISALLOW_COPY_AND_ASSIGN."
  - Prefer `= delete` in place of DISALLOW_COPY_AND_ASSIGN.
    
    Clang-tidy expects modernized code to prefer deleting copy constructors
    and assignment operators to legacy macros.
    
    /disk/android_trees/aosp-master-plus-llvm/frameworks/base/cmds/idmap2/tests/ResultTests.cpp:263:3: error: prefer deleting copy constructor and assignment operator over using macro 'DISALLOW_COPY_AND_ASSIGN' [modernize-replace-disal low-copy-and-assign-macro,-warnings-as-errors]
      DISALLOW_COPY_AND_ASSIGN(NoCopyContainer);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
    Bug: http://b/155835175
    Test: mm in idmap2
    Change-Id: I3bb29b48a478a67cbda959f47b271ccf8543a768