Update git submodules
* Update external/elfutils from branch 'master'
  to ad0182654b68d2e198bed5d3b5e926260cd1fde2
  - Merge "Merge tag 'elfutils-0.180' into master"
  - Merge tag 'elfutils-0.180' into master
    
    elfutils 0.180 release
    
    * tag 'elfutils-0.180':
      Prepare for 0.180
      libebl: Remove Ebl struct size check and MODVERSION string.
      nm: Handle corrupt symbol name table.
      nm: Explicitly print weak 'V' or 'T' and common 'C' symbols.
      libelf: Sync elf.h from glibc.
      size: Also obey radix printing for bsd format.
      libcpu: Free unused new bitfield on error in i386_parse.y new_bitfield.
      libdwfl: Return failure from dwfl_standard_find_debuginfo for NULL module.
      src: Check ebl_openbackend result before using ebl handle.
      libelf: Check for NULL shdr in elf_strptr.
      libelf: Check __gelf_getehdr_rdlock call doesn't fail in elf_getdata.
      tests: Make sure to not call memcmp with NULL arguments.
      libdwfl: Cleanup user_core resources on failure in dwfl_core_file_report.
      libdw: Skip imported compiler_units in libdw_visit_scopes walking DIE tree
      libdw: Use correct CU to resolve file names in dwarf_decl_file.
      libdwfl: Handle debugaltlink in dwfl_standard_find_debuginfo.
      libdwfl: Fix double free on failure path in gzip.c.
      libdw: Call Dwarf oom_handler() when malloc fails in __libdw_alloc_tail.
      libasm: Fix double fclose in asm_end.
      libelf: Fix double free in __libelf_compress on error path.
      tests: Run run-varlocs-self.sh for object files with --exprlocs.
      tests: Build test-nlist with minimal CFLAGS to guarantee symbol order.
      debuginfod sysconfig: add /var/lib/pulp as default search path
      libdw, readelf: Handle GCC LTO .gnu.debuglto_ prefix.
      elflint: Allow SHF_EXCLUDE as generic section flag when --gnu is given.
      libcpu: Replace assert with goto invalid_op for bad prefix.
      libdwfl: Initialize bits to NULL in dwfl_standard_find_debuginfo for LTO.
      config: chmod uploaded dir and files to make them readable.
    
    This also regenerates config.h and version.h accordingly and adds the
    script post_update.sh as well as the necessary patches/ to do so.
    
    Signed-off-by: Matthias Maennich <maennich@google.com>
    Change-Id: Iab9ecd269d0ac4a0223109942832de457ca4d280
    
  - Prepare for 0.180
    
    Set version to 0.180.
    Update NEWS and elfutils.spec.in.
    Set copyright year in printversion.
    Regenerate po/*.po files.
    Update .gitignore.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - libebl: Remove Ebl struct size check and MODVERSION string.
    
    We used to do several sanity checks when the ebl backend libraries
    were loaded to make sure there was no version mismatch. When initializing
    the backend we passed the current Ebl struct size so the library could
    check it supported the given Ebl struct and we checked that the init
    method returned the correct build time module version string. Neither
    are necessary now that the backends are builtin.
    
    Remove both the struct size check and the MODVERSION string (which
    wasn't actually checked anymore). Make the init function return the
    given Ebl handle or NULL on error (no init function currently indicates
    any error).
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - nm: Handle corrupt symbol name table.
    
    We try to sort symbol by name (when neither -n nor -p are given).
    This could crash if the symbol name table was corrupt. Use elf_strptr
    to get the symbol name and use the empty string in case a name couldn't
    be found.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - nm: Explicitly print weak 'V' or 'T' and common 'C' symbols.
    
    Mimic binutils nm for bsd and posix formats which uses 'V' for weak
    symbols, 'C' for common symbols and 'T' for weak functions. Also fix
    some formatting issues. Don't print undefined addresses as zeros, but
    make sure there is enough padding instead. Just print UNIQUE for
    GNU_UNIQUE to make it fit 6 chars, like other binding names in sysv
    format.
    
    https://sourceware.org/bugzilla/show_bug.cgi?id=25227
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - libelf: Sync elf.h from glibc.
    
    There is now finally a PT_GNU_PROPERTY define.
    Also EM_ARC_COMPACT2 got renamed to EM_ARCV2.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - size: Also obey radix printing for bsd format.
    
    eu-size already prints according to the given radix for sysv format,
    but not for the bsd format. Fix that.
    
    Reported-by: Ulrich Drepper <drepper@redhat.com>
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - libcpu: Free unused new bitfield on error in i386_parse.y new_bitfield.
    
    GCC10 -fanalyzer detected we didn't free the newly created bitfield
    on error. Make sure to free it before returning.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - libdwfl: Return failure from dwfl_standard_find_debuginfo for NULL module.
    
    GCC10 -fanalyzer plus -flto notices that some functions called by
    dwfl_standard_find_debuginfo check that the given module isn't NULL,
    but others expect it to be non-NULL. Just return a failure immediately
    when a NULL mod is passed to dwfl_standard_find_debuginfo.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - src: Check ebl_openbackend result before using ebl handle.
    
    GCC10 -fanalyzer plus -flto sees that ebl_openbackend can fail and
    return NULL. Most of the time we will get a dummy ebl, but in case
    of out of memory or corrupt ELF header it might return NULL. Make
    sure that we report a (fatal) error in that case in all tools.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - libelf: Check for NULL shdr in elf_strptr.
    
    GCC10 -fanalyzer with -flto notices __elf64_getshdr_rdlock can fail
    and because the result isn't checked in elf_strptr it can cause a
    dereference of NULL.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - libelf: Check __gelf_getehdr_rdlock call doesn't fail in elf_getdata.
    
    GCC10 -fanalyzer with -flto notices __gelf_getehdr_rdlock can fail
    and that the result of the call in __libelf_set_rawdata_wrlock isn't
    checked, which can cause a dereference of NULL.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - tests: Make sure to not call memcmp with NULL arguments.
    
    GCC10 -fanalyzer thinks we are too clever:
    
    elfputzdata.c: In function ‘main’:
    elfputzdata.c:178:8: warning: use of possibly-NULL ‘orig_buf’ where
                         non-null expected [CWE-690]
                         [-Wanalyzer-possible-null-argument]
      178 |     && memcmp (orig_buf, d->d_buf, orig_size) == 0)
    
    orig_buf can only be NULL when orig_size is zero, but it might still
    be undefined behaviour. So don't try to be too smart and just check
    whether we actually have an buffer.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - libdwfl: Cleanup user_core resources on failure in dwfl_core_file_report.
    
    GCC10 -fanalyzer noticed that we allocate, but don't always cleanup the
    dwfl->user_core if it wasn't set yet on error. In theory dwfl_module_end
    should take care of it, but it is cleaner and less confusing to just do
    it here.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - libdw: Skip imported compiler_units in libdw_visit_scopes walking DIE tree
    
    Some gcc -flto versions imported other top-level compile units,
    skip those. Otherwise we'll visit various DIE trees multiple times.
    
    Note in the testcase that with newer GCC versions function foo is
    fully inlined and does appear only once (as declared, but not as
    separate subprogram).
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - libdw: Use correct CU to resolve file names in dwarf_decl_file.
    
    dwarf_decl_file uses dwarf_attr_integrate to get the DW_AT_decl_file
    attribute. This means the attribute might come from a different DIE
    in a different CU. If so, we need to use the CU associated with the
    attribute, not the original DIE, to resolve the file name.
    
    Also add a bit more documentation to dwarf_attr_integrate explaining
    that the attribute returned might come from a different CU (and even
    different Dwarf).
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - libdwfl: Handle debugaltlink in dwfl_standard_find_debuginfo.
    
    When we fall back to the debuginfod client then we need to do the
    same trick we do for local lookups in dwfl_build_id_find_debuginfo.
    If the debug file (dw) is already set, then we must be looking for
    the altfile. But we cannot use the actual file/path name given as
    hint. We'll have to lookup the alt file "build-id". Because the
    debuginfod client only handles build-ids.
    
    Previously we would use the build-id of the main file which meant
    the debuginfod client would give us another copy of the debug file,
    which would then be set as its own altfile. This caused lots of
    confusion...
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - libdwfl: Fix double free on failure path in gzip.c.
    
    GCC10 -fanalyzer found a double free when openstream failed. When
    openstream fails __libdw_gunzip will call fail, which frees the
    state->buffer. But openstream can call zlib_fail, which will also
    call fail. Instead of calling zlib_fail, just return the error
    that zlib_fail would have returned.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - libdw: Call Dwarf oom_handler() when malloc fails in __libdw_alloc_tail.
    
    GCC10 -fanalyzer found a possibly-NULL dereference after a failed
    malloc in __libdw_alloc_tail. In this case we should call the Dwarf
    oom_handler as is done in other places where an essential malloc
    call fails. The oom_handler cannot return and will likely just abort.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - libasm: Fix double fclose in asm_end.
    
    GCC10 -fanalyzer found a double fclose in asm_end. asm_end can call
    text_end, which calls fclose and checks for errors, then asm_end
    calls __libasm_finictx which can call fclose again (but doesn't
    check for errors). Call fflush in text_end instead. fflush will
    generate the same error fclose would if something went wrong writing
    out the file.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - libelf: Fix double free in __libelf_compress on error path.
    
    In commit 2092865a7e589ff805caa47e69ac9630f34d4f2a
    "libelf: {de,}compress: ensure zlib resource cleanup" we added a
    call to deflate_cleanup to make sure all resources were freed.
    As GCC10 -fanalyzer points out that could cause a double free
    of out_buf. Fix by removing the free (out_buf) in __libelf_compress.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - tests: Run run-varlocs-self.sh for object files with --exprlocs.
    
    The varlocs test relies on finding addresses for the CUs, even in
    object files. This might not be true (for example when building with
    gcc -flto, which only emits partial, type only, debuginfo). Split
    running the self tests in running on executables and shared libraries
    as normal, but run object files with --exprlocs to test that output
    too (and not require addresses).
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - tests: Build test-nlist with minimal CFLAGS to guarantee symbol order.
    
    test_nlist checks its own symbol table, and expects various symbols
    to be in the order as specified in the source file. Explicitly set
    minimal CFLAGS.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - debuginfod sysconfig: add /var/lib/pulp as default search path
    
    Red Hat Satellite 6 (pulp era) stores RPMs under this hierarchy, so if
    a user is fortunate enough to have debuginfod on such a machine, we
    might as well index that.
    
    Signed-off-by: Frank Ch. Eigler <fche@redhat.com>
    
  - libdw, readelf: Handle GCC LTO .gnu.debuglto_ prefix.
    
    GCC puts (partial) DWARF debuginfo into sections prefixed with
    .gnu.debuglto_. Handle those sections as if they are normal .debug
    sections (which they are). This allows showing the DWARF that gcc
    puts into ET_REL files compiled with -flto.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - elflint: Allow SHF_EXCLUDE as generic section flag when --gnu is given.
    
    Strictly speaking SHF_EXCLUDE is a processor specific section flag,
    but it is used generically in the GNU toolchain. For example when
    adding .gnu.lto_ sections.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - libcpu: Replace assert with goto invalid_op for bad prefix.
    
    https://sourceware.org/bugzilla/show_bug.cgi?id=25831
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - libdwfl: Initialize bits to NULL in dwfl_standard_find_debuginfo for LTO.
    
    GCC10 LTO is too smart (and somewhat cryptic):
    
        find-debuginfo.c: In function ‘dwfl_standard_find_debuginfo’:
        debuginfod-client.c:85:8: error: ‘bits’ may be used uninitialized
        in this function [-Werror=maybe-uninitialized]
        find-debuginfo.c:360:24: note: ‘bits’ was declared here
        lto1: all warnings being treated as errors
    
    So it inlines __libdwfl_debuginfod_find_debuginfo into
    dwfl_standard_find_debuginfo and since it cannot see into the
    function pointer (*fp_debuginfod_find_debuginfo), it assumes that
    build_id_bit (== bits in dwfl_standard_find_debuginfo) will be used
    by the called function and it might not be initialized.
    But if you read the code the there is a check for build_id_len > 0
    to see whether bits is or isn't initialized before using bits.
    But gcc isn't smart enough to figure that out.
    
    Maybe that actually should be an heuristic gcc lto should use.
    If the callchain I am inlining is so deep that I cannot figure out
    maybe-uninitialized variables anymore I should stop inlining.
    
    For now just help GCC out and initialize bits to NULL.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - config: chmod uploaded dir and files to make them readable.
    
    Default file permissions on sourceware have changed. Make sure that
    the upload-release.sh script sets the permissions right.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>