Update git submodules
* Update external/perfetto from branch 'master'
  to 5dc147f282abfab68c485d9d448b2a0630016720
  - Fix clock_tracker.cc
    
    aosp/1423925 broke the CI due to atomic not being copyable:
    
    ../../src/trace_processor/importers/common/clock_tracker.cc:214:34: error: copying variable of type 'std::atomic<uint32_t>' (aka 'atomic<unsigned int>') invokes deleted constructor
         static std::atomic<uint32_t> dlog_count = 0;
                                      ^            ~
     /ci/ramdisk/src/buildtools/emsdk/emscripten/system/include/libcxx/atomic:1048:7: note: copy constructor of 'atomic<unsigned int>' is implicitly deleted because base class '__atomic_base<unsigned int>' has a deleted copy constructor
         : public __atomic_base<_Tp>
           ^
     /ci/ramdisk/src/buildtools/emsdk/emscripten/system/include/libcxx/atomic:967:7: note: copy constructor of '__atomic_base<unsigned int, true>' is implicitly deleted because base class '__atomic_base<unsigned int, false>' has a deleted copy constructor
         : public __atomic_base<_Tp, false>
           ^
     /ci/ramdisk/src/buildtools/emsdk/emscripten/system/include/libcxx/atomic:947:5: note: '__atomic_base' has been explicitly marked deleted here
         __atomic_base(const __atomic_base&) = delete;
         ^
    
    Change-Id: I60e290f0fec24fb5340bb3344c4bae4c7059f057