Update git submodules
* Update tools/asuite from branch 'master'
  to 12010e61fa980d531ec88c32b75ed06542929925
  - Merge "AIDEGen: Use Match.group instead of Match.__getitem__"
  - AIDEGen: Use Match.group instead of Match.__getitem__
    
    The following error occurs when aidegen modifies
    idea.properties file on Ubuntu16.04 and Python3.5
    
    if res and int(res['value']) < self._FILESIZE_LIMIT:
    TypeError: '_sre.SRE_Match' object is not subscriptable
    
    Because this method is new in version Python v3.6
    
    Test: m aidegen;aidegen-dev framework -s
          Checked idea.properties file.
    
    Change-Id: I69099a00670b6c8ad8e5879976d6bc8bc120bfd1