Update git submodules
* Update external/googletest from branch 'master'
  to e87584ebb141cd532f4688556835903c44563292
  - Upgrade googletest to 70b90929b1da20580cad9ed996397cf04ef8f16d
    
    Change-Id: Ib64485b580de081d0c8fa584a037729cc522df91
    
  - Googletest export
    
    Adding std:: namespace to string in the example
    
    PiperOrigin-RevId: 320327910
    
  - Merge pull request #2872 from elindsey:master
    
    PiperOrigin-RevId: 320224740
    
  - Merge pull request #2808 from OlivierLDff:cmake-cpp11-feature
    
    PiperOrigin-RevId: 320222294
    
  - Merge pull request #2682 from mjvankampen:cmake-QNX-fix
    
    PiperOrigin-RevId: 320191208
    
  - Googletest export
    
    Replace ByRef with std::ref everywhere in docs.
    
    PiperOrigin-RevId: 320002303
    
  - Googletest export
    
    Cleanup: Error message grammar fix.
    PiperOrigin-RevId: 319992912
    
  - Googletest export
    
    Fix mismatch between `int` and `int32_t` in the parse function.
    On some platforms, those are different types.
    
    PiperOrigin-RevId: 319991862
    
  - Googletest export
    
    Improve compatibility with strict compilers targeting Windows
    
    Remove an unnecessary ##, which could result in warnings about invalid preprocessor tokens when pasting to an initial '('
    
    PiperOrigin-RevId: 319277617
    
  - use target_compile_features to use c++11 if cmake > 3.8
    
    If target_compile_features is available and cxx_std_11.
    This fix compilation with clang and gcc when c++11 isn't specified by user.
    
  - Googletest export
    
    Add Bazel build rules for gtest_list_output_unittest.py and correct some off-by-one line number expectations.
    
    PiperOrigin-RevId: 318466071
    
  - Googletest export
    
    Normalize headers in gMock docs
    
    Increasing Header levels on two pages, to better match other pages in the same directory.
    
    PiperOrigin-RevId: 318280892
    
  - Googletest export
    
    Update auto_mock to support C++17 nested namespaces
    
    PiperOrigin-RevId: 318192214
    
  - Merge pull request #2902 from mshingote:master
    
    PiperOrigin-RevId: 318147761
    
  - Googletest export
    
    Make sure sanitizers do not tamper with the stack here in StackLowerThanAddress().
    
    PiperOrigin-RevId: 318082465
    
  - Merge pull request #2718 from NINI1988:master
    
    PiperOrigin-RevId: 317696457
    
  - Merge pull request #2891 from zoddicus:fixMinGW
    
    PiperOrigin-RevId: 317666280
    
  - Updated googletest issue tracker url.
    
  - Googletest export
    
    gtest.cc: fix a couple typos
    
    s/paramaterized/parameterized/
    
    PiperOrigin-RevId: 316878900
    
  - Googletest export
    
    gMock Cookbook: Fix incorrect comment about EXPECT priority order
    
    It's actually the last matching expectation that's used, not the first.
    
    PiperOrigin-RevId: 316490770
    
  - Googletest export
    
    Adds support for printing pointers of types char8_t, char16_t, and char32_t.
    
    PiperOrigin-RevId: 316112767
    
  - Googletest export
    
    Change string matchers, like HasSubstr, to accept `string_view` input if available.
    
    PiperOrigin-RevId: 315726484
    
  - Googletest export
    
    Make visible ParseInt32 in case users have separate gmock/gtest libraries and hidden-by-default symbols.
    
    This function is still considered an internal implementation detail and is subject to change without notice. It is still unsafe/unsupported to link together libraries built at different commits.
    
    PiperOrigin-RevId: 315405429
    
  - Googletest export
    
    Fail TEST_Ps or TYPED_TEST_Ps that are defined but are not instantiated, as well as the opposite case, where INSTANTIATE_TEST_SUITE_P or INSTANTIATE_TYPED_TEST_SUITE_P is used but without any matching TEST_P or TYPED_TEST_P.
    
    PiperOrigin-RevId: 315255779
    
  - Googletest export
    
    Add missing static_cast to char32_t printer
    
    PiperOrigin-RevId: 314925583
    
  - Fix build issue for MinGW
    
    Fixes #2885
    
  - Googletest export
    
    Adds support for printing the types char8_t, char16_t, and char32_t
    
    This changes prints these types as Unicode code points. It is possible
    that there is a better way of printing these types, but that change is
    more complex, and the format in which Googletest prints these types is
    subject to change if someone implements a better way of printing them.
    
    This fixes the C++20 build, which removed support for printing these types.
    https://en.cppreference.com/w/cpp/io/basic_ostream/operator_ltlt2
    
    Fixes #2854
    
    PiperOrigin-RevId: 314826912
    
  - Merge pull request #2742 from kuzkry:c++17-type-printers
    
    PiperOrigin-RevId: 314593695
    
  - Googletest export
    
    gMock Cookbook: Slight rewording
    
    Remove "I" because documentation can have multiple authors. And remove unnecessary "guy".
    
    PiperOrigin-RevId: 314533746
    
  - Merge pull request #2755 from Conan-Kudo:set-version-for-libs
    
    PiperOrigin-RevId: 314427570
    
  - Googletest export
    
    Note that EXPECT_EQ(actual_value, expected_value) or EXPECT_THAT(actual_value, Eq(expected_value)) is preferred over EXPECT_THAT(actual_value, expected_value).
    
    PiperOrigin-RevId: 314350852
    
  - Googletest export
    
    Modify NULL to nullptr in code examples
    
    PiperOrigin-RevId: 314150792
    
  - fix compilation on OpenBSD 6.7
    
    Building on OpenBSD 6.7 current fails due to implicit numeric
    conversions:
    
        OpenBSD clang version 8.0.1 (tags/RELEASE_801/final) (based on LLVM 8.0.1)
        Target: amd64-unknown-openbsd6.7
        Thread model: posix
        InstalledDir: /usr/bin
    
        In file included from /tmp/u/build/_deps/googletest-src/googletest/src/gtest-all.cc:45:
        /tmp/u/build/_deps/googletest-src/googletest/src/gtest-port.cc:201:19: error: implicit conversion changes signedness:
              'int' to 'unsigned long' [-Werror,-Wsign-conversion]
          mib[5] = size / mib[4];
                        ~ ^~~~~~
        /tmp/u/build/_deps/googletest-src/googletest/src/gtest-port.cc:211:33: error: implicit conversion changes signedness:
              'int' to 'unsigned long' [-Werror,-Wsign-conversion]
          for (size_t i = 0; i < size / mib[4]; i++) {
                                      ~ ^~~~~~
        /tmp/u/build/_deps/googletest-src/googletest/src/gtest-port.cc:215:10: error: implicit conversion changes signedness:
              'int' to 'size_t' (aka 'unsigned long') [-Werror,-Wsign-conversion]
          return nthreads;
          ~~~~~~ ^~~~~~~~
        /tmp/u/build/_deps/googletest-src/googletest/src/gtest-port.cc:201:17: error: implicit conversion loses integer
              precision: 'unsigned long' to 'int' [-Werror,-Wshorten-64-to-32]
          mib[5] = size / mib[4];
                 ~ ~~~~~^~~~~~~~
        4 errors generated.
    
  - make UniversalPrinter<std::any> support RTTI
    
  - specialize UniversalPrinter<> for std::any (without support for RTTI)
    
  - specialize UniversalPrinter<> for std::optional
    
  - specialize UniversalPrinter<> for std::variant
    
  - Googletest export
    
    Update Travis CI to use Ubuntu Bionic in some cases
    
    PiperOrigin-RevId: 313639562
    
  - Googletest export
    
    Fix compile error from protected destructor of std::codecvt
    
    PiperOrigin-RevId: 313584603
    
  - Googletest export
    
    Change 'suite' to 'case' in comments.
    
    PiperOrigin-RevId: 313429487
    
  - Merge pull request #2767 from mvoorsluys:OutputXmlSkipped
    
    PiperOrigin-RevId: 313386267
    
  - Googletest export
    
    Rollback of warning on unused ACTION result change
    
    PiperOrigin-RevId: 313380971
    
  - Merge pull request #2862 from prehistoric-penguin:prehistoric-penguin-patch-1
    
    PiperOrigin-RevId: 313289519
    
  - Merge pull request #2845 from matepek:readme-update-with-opensource-proj
    
    PiperOrigin-RevId: 312530971
    
  - Merge pull request #2677 from IYP-Programer-Yeah:fix-file-path-normalize-function
    
    PiperOrigin-RevId: 312486861
    
  - Merge pull request #2698 from aribibek:patch-1
    
    PiperOrigin-RevId: 312342956
    
  - Googletest export
    
    Spell out namespace for absl::Notification.
    
    PiperOrigin-RevId: 312300192
    
  - Googletest export
    
    Addresses https://github.com/google/googletest/issues/2848 by using `_wfopen(...)` on Windows
    
    PiperOrigin-RevId: 312198825
    
  - Googletest export
    
    Silence MSVC C4100 (unused formal parameter) to fix breakage from recently added testcase.  This warning is silenced in many files throughout googletest, but was not needed here until this testcase was added.
    
    PiperOrigin-RevId: 312121200
    
  - Googletest export
    
    Mark ACTION_Pn()-generated functions as must-use-result.
    
    This catches when a client creates an action and discards it, thinking that the action has actually been applied to something.
    
    This will help people who make the mistake of defining, for example, both `void Use(Foo*)` and `ACTION(Use) { Use(arg); }` for later application to a Foo.  With such an overload, a client may then write `Use();`, forgetting the param and being confused why nothing happens.
    
    This also catches when a client defines their own action in terms of an ACTION()-generated one, invokes the ACTION's builder, and then fails to invoke the resulting action, thinking it's operating on the outer action's parameters.
    
    PiperOrigin-RevId: 312108101
    
  - Googletest export
    
    Fix the ACTION* macros to allow for more than 10 arguments in the action.
    Only the first 10 will be passed as individual arguments as `argN`, but the rest
    can be accessed from the `args` tuple.
    
    PiperOrigin-RevId: 311542098
    
  - Use count function instead of handwritten loop
  - Merge remote-tracking branch 'original/master' into readme-update-with-opensource-proj
    
  - README.dm: Renamed related open source project name: Catch2 and Google Test Explorer -> C++ TestMate
    
  - Fix test with stack.
    
    
  - Merge branch 'master' of https://github.com/google/googletest into cmake-QNX-fix
    
    # Conflicts:
    #	CMakeLists.txt
    
  - Fixed xml unit-tests and added extra tests
    
    The extra tests check that the xml output is correct when a failure occurs before skipping, and that the right skip message is added to the file.
    
    The json file had to be fixed because it's the same executable.
  - Fix multiple \n characters in xml file when using GTEST_SKIP.
    
    
  - Only write ">\n" once when there is failure and skipped tests.
    
    
  - Output skipped information in the xml file.
    
    
  - Set the version for the libraries
    
    When building packaged shared libraries for use, having the version
    set makes it so that the soname is set correctly for parallel installation.
    
    This change is derived from the one used for the Fedora gtest package.
    
    Signed-off-by: Neal Gompa <ngompa13@gmail.com>
    
  - Add missing call for gtest_list_output_unittest_ unitTest.
    Add unitTest for fixed TEST_P line number.
    Use CodeLocation TestInfo struct.
    
  - Fix: shadow member
    
  - Add correct line number to TEST_P test cases for gtest_output.
    
  - Merge branch 'master' of https://github.com/google/googletest into cmake-QNX-fix
    
    # Conflicts:
    #	CMakeLists.txt
    
  - fix a link to documentation
    
    fix a documentation link on "how to customize the printing of the arguments"
  - Fix always false condition and clean function body
    
    An always false condition was remove from Normalize member function of
    FilePath and the body of the function which was poorly writen is
    improved.
    
  - Fixes extensions missing for QNX
    

* Update system/testing/gtest_extras from branch 'master'
  to 8b01e5b60bb320cc0f81da43f31bd6a73ecc7860
  - Adds a \n between "Skipped" and message.
    
    message will not come with a prefix \n, according to upstream change:
    https://github.com/google/googletest/commit/23dadb84
    
    Change-Id: I4d07ed6ca62db497d233895a26ac01c7751e5249