Update git submodules
* Update frameworks/support from branch 'androidx-master-dev'
  to 57227a148b1292d39ef423af9e90eb8e55dd0788
  - Merge "Desktop: fix tests" into androidx-master-dev
  - Desktop: fix tests
    
    We should always use TestComposeWindow/DesktopScreenshotTestRule/createComposeRule if we test compose classes.
    Otherwise there will be an error sometimes:
          java.lang.UnsatisfiedLinkError: 'long org.jetbrains.skija.Paint._nGetFinalizer()'
    
    (because initCompose() may be not called before test)
    
    Test: ./gradlew jvmTest desktopTest -Pandroidx.compose.multiplatformEnabled=true
    Change-Id: I71ca818ebb892c81186b758e4d5286c7eb05c768