Autoupdate of 2 submodules
*build/soong updated to 54f45e5c17f513fe03e5b9e6c95219cb3689162b
Merge "Enable enum-enum-conversion warning"
*external/deqp-deps/glslang updated to 4d7691789b060ba6e5fdbd29bd258c02e28eac8f
Suppress enum-enum-conversion warning

external/deqp-deps/glslang/glslang/MachineIndependent/ParseHelper.cpp:9291:108: error: arithmetic between different enumeration types ('glslang::TLayoutPacking' and 'glslang::TLayoutMatrix') [-Werror,-Wenum-enum-conversion]
        size_t originMemberHash = hasher(originType->getStruct()->at(i).type->getQualifier().layoutPacking +
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
external/deqp-deps/glslang/glslang/MachineIndependent/ParseHelper.cpp:9293:102: error: arithmetic between different enumeration types ('glslang::TLayoutPacking' and 'glslang::TLayoutMatrix') [-Werror,-Wenum-enum-conversion]
        size_t tmpMemberHash = hasher(tmpType->getStruct()->at(i).type->getQualifier().layoutPacking +
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^

Test: presubmit
Bug: 154138986
Change-Id: Ia306c9381178139f55e474a6e7056baaa07c4cbb