Autoupdate of 2 submodules
*build/soong updated to 4a06eea3cfc4bc958a931e7bbb4c9906735b493c
Merge "Update clang version to clang-r475365"
*packages/modules/adb updated to f789513e42f3dbef4cc6839ccc1fe30f1384375b
Fix test for clang update.

With clang update, clang-tidy reports below error:

types_test.cpp:53:14: error: 'x' used after it was moved [bugprone-use-after-move,-warnings-as-errors]
    CHECK_EQ(x.coalesce().size(), y.coalesce().size());
             ^
types_test.cpp:52:14: note: move occurred here
    IOVector y(std::move(x));
             ^

Bug: 253033919
Test: run clang-tidy manually
Change-Id: Id74599a9868fce9390a0bfe17e6f83e48ef892de