Fix misc-unused-using-decls clang-tidy warning
packages/modules/Connectivity/service/native/TrafficController.cpp:58:18: error: using decl 'DumpWriter' is unused [misc-unused-using-decls,-warnings-as-errors]
using netdutils::DumpWriter;
^
packages/modules/Connectivity/service/native/TrafficController.cpp:58:18: note: remove the using
using netdutils::DumpWriter;
~~~~~~~~~~~~~~~~^~~~~~~~~~~
packages/modules/Connectivity/service/native/TrafficController.cpp:61:18: error: using decl 'ScopedIndent' is unused [misc-unused-using-decls,-warnings-as-errors]
using netdutils::ScopedIndent;
^
packages/modules/Connectivity/service/native/TrafficController.cpp:61:18: note: remove the using
using netdutils::ScopedIndent;
~~~~~~~~~~~~~~~~^~~~~~~~~~~~~

Test: presubmit
Change-Id: I1871139fed31c57a5c15a8ab4f88aa7c695ff360