Merge branch 'upstream-master' into 'master'
* aosp/upstream-master:
  ELF reader: detect Linux kernel binary only once
  Abigail reader: report missing XML type definitions
  STG: dwarf wrappers: trade NRVO optimization attempt for readability
  unification: rename UnificationCache to Unification
  stg, stgdiff: eliminate evil global variable
  DWARF processor: add scoped name for functions
  error: use a wrapper object for hexadecimal output
  error: use a wrapper object for errno output
  proto reader: clean-up diagnostics
  unification: split this functionality out of type resolution
  type resolution: make UnificationCache own the substitution mapping
  type resolution: Update as member function of UnificationCache
  DWARF reading: support scope in struct/class/union and typedef
  Reading: refactor scope building
  type resolution: rename Unify to Unifier and add Unify wrapper function
  type resolution: make UnificationCache a class
  type resolution: remove incomplete named type collection
  unification cache: make union prefer second node
  unification: determine direction of substitutions
  graph: report undefined node internal ID
  ELF reader: fix typo in comment

Change-Id: I79d3694c8c7cff66255f86d81b318cf4eccc3213
Signed-off-by: Matthias Maennich <maennich@google.com>