Update git submodules
* Update external/fmtlib from branch 'master'
  to 2ea04745efe22c936ceb530d6dd89c6eeafe303b
  - Upgrade fmtlib to 6.2.0
    
    Test: None
    Change-Id: I31621962fc73c4491aafd4232d8517312eb38f36
    
  - Update version
    
  - Fix punctuation in changelog
    
  - Fix gcc version check
    
  - Update changelog
    
  - Fix markup
    
  - Bump version
    
  - Update changelog
    
  - Update changelog
    
  - Update changelog
    
  - Update changelog
    
  - Implement the L specifier
    
  - Follow naming conventions
    
  - Fix posix-mock-test
    
  - Reduce binary size
    
  - Merge branch 'master' of github.com:fmtlib/fmt
    
  - Update changelog
    
  - Fix wide print overload (#1609)
    
  - Use FMT_THROW macro where applicable
    
  - Update readme and add compatibility option
    
  - Undo comment change
    
  - Fix -Wsign-conversion warnings
    
  - Enable FMT_STRING() use with types other than string literals
    
  - Fix handling of small precision in general format
    
  - Add .vs to .gitignore
    
  - Detect /utf-8 in MSVC
    
  - Improve exception safety in dynamic_format_arg_store
    
  - Move FMT_USE_FLOAT and friends to fmt/format.h
    
  - Allow disabling floating point support (#1590)
    
    * Allow disabling floating point support
    
    Add FMT_USE_FLOAT, FMT_USE_DOUBLE and FMT_USE_LONG_DOUBLE to allow a
    user of the library to configure the float types they want to allow.
    This is specially useful in embedded environements where code size is
    important.
    
    * Avoid conditional macros to disable float support
    
    * Add is_supported_floating_point constexpr function
    
    * Fix empty-body warning
  - Don't use properties when setting FMT_LIB_NAME
    
  - Add back missing OUTPUT_NAME in target properties. (#1598)
    
    
  - Simplify dynamic_format_arg_store
    
  - Color formatting fixed for wide strings (fixes issue #1594) (#1596)
    
    * Use std::char_traits::length for ansi_color_escape::begin
    
    -Fixes issue #1594 https://github.com/fmtlib/fmt/issues/1594
    
  - Simplify dynamic store
    
  - Minor tweaks for dynamic_format_arg_store
    
  - Dynamic arguments storage. Implementation of enhancement from issue #1170. (#1584)
    
    
  - Ability to join elements of std::initializer_list was added
    
  - Allow leading zeros in precision (#1579)
    
  - Deprecate fmt::char8_t
    
  - Fix a typo in CMake config: STRINGS -> STRING
    
  - Fix handling of empty tuples (#1588)
    
  - Add FMT_HAS_CPP14_ATTRIBUTE / FMT_HAS_CPP17_ATTRIBUTE to test for language-specific attributes.
    
    FMT_DEPRECATED is now defined as FMT_HAS_CPP14_ATTRIBUTE(deprecated), as this attribute was introduced in C++14.
    
    FMT_FALLTHROUGH is now defined as FMT_HAS_CPP17_ATTRIBUTE(fallthrough), as this attribute was introduced in C++17.
    
    FMT_MAYBE_UNUSED is defined as FMT_HAS_CPP17_ATTRIBUTE(maybe_unused), as this attribute was introduced in C++17.
    
    FMT_MAYBE_UNUSED has been applied to fix a couple of -Wunused-member-function warnings from clang.
    
  - Workaround 'cannot call member function without object' error on gcc 4.9
    
  - Fix handling of volatile enums
    
  - Workaround broken fallthrough attribute in the PGI compiler (#1583)
    
  - Tweak a comment
    
  - Workaround for broken [[deprecated]] in PGI compiler (#1581)
    
    * Workaround broken [[deprecated]] in PGI compiler
      - similar to Intel and NVCC, add workaround for PGI compiler
  - Fix empty debug postfix
    
  - Remove gcc 4.4 workaround
    
  - set_doc -> set_verbose
    
  - Cleanup CMake config
    
  - is_static_compiled_format -> is_compiled_format
    
  - Fix clang -Wdisabled-macro-expansion warning from FMT_STRING_IMPL.
    
    FMT_STRING_IMPL has an internal helper named FMT_STRING, however FMT_STRING is also the name of the macro that invokes FMT_STRING_IMPL.
    
    Renaming this helper avoids the appearance of a recursive macro.
    
  - Fix ambiguous overloads of format & format_to
    
  - Deprecate undocumented _u suffix
    
  - Improve width computation
    
  - Make FMT_DEBUG_POSTFIX a cache variable (#1566)
    
  - Apply clang-format
    
  - Fix clang -Wsign-conversion warning in grisu_count_digits. (#1573)
    
    grisu_count_digits is only used by grisu_gen_digits, which assigns the unsigned result to a (signed) int.
    
    Although grisu_count_digits always returns a positive integer this keeps its return type in sync with the type its result is assigned to.
  - Make compile-time checks in format_to handle references
    
  - Fix simple -Wsign-conversion cases. (#1571)
    
    * Fix -Wsign-conversion in bigint::subtract_aligned.
    
    n is assigned a size_t, and only used for comparisons with j.
    
    j is assigned 0, compared to n (size_t), and passed to basic_memory_buffer::operator[] (size_t).
    
    * Fix -Wsign-conversion in bigint::assign.
    
    num_bigits is initialised to 0, is only ever incremented, and is passed to basic_memory_buffer::operator[] (size_t) and basic_memory_buffer::resize (size_t).
    
  - Move FMT_CLANG_VERSION definition to core.h (#1568)
    
    Previously format.h defined FMT_CLANG_VERSION after including core.h, however core.h tests FMT_CLANG_VERSION when it defines FMT_API.
  - Add FMT_NORETURN to assert_fail prototype. (#1569)
    
    When building with -Werror,-Wmissing-noreturn clang identifies that assert_fail could be declared with the 'noreturn' attribute.
  - Tentative fix for default template param in friend error
    
  - Make FMT_ASSERT work in constexpr on clang 4.0.1
    
  - Don't use internal GTest API
    
  - Fix FMT_FORMAT_AS const specifier position (#1554)
    
    The current `FMT_FORMAT_AS` macro will make `formatter<Char *>::format`
    have the first argument type `const Char *&` which is incorrect an
    should be `Char *const &`.  This pull request fixes that by changing the
    first argument type in the macro definition body from `const Type &` to
    `Type const &`.
  - improved use of find (#1560)
    
    * improved use of find
    
    *begin is supposed to be different from '{' when this find is used, so we can avoid checking it.
    
  - add const begin and end overload to buffer (#1553)
    
    * add const begin and end overload to buffer
    
    since there is a const overload for data I think there should also be one for begin and end
    
  - Fix to_string docs
    
  - Remove misleading FMT_USE_WINDOWS_H
    
  - Workaround broken UDL templates in GCC < 6.4
    
  - Make formatter override implicit conversion to a C string
    
  - Fix a link error in gcc8 (#1548)
    
  - only modify CMAKE_RUNTIME_OUTPUT_DIRECTORY if it is not already set
    
  - Only use compiler features if available
    
  - string_view::char_type -> value_type (#1539)
    
  - Update README.rst
  - Fix symbol visibility on Linux when compiling with -fvisibility=hidden (#1535)
    
    Make FMT_API symbols use the default visibility on non-Windows
    platforms. Otherwise, one cannot use the generated fmt library when
    compiling globally with -fvisibility=hidden.
    
    Fixes compile errors like:
    
    ```
    ../3rdParty/fmt/include/fmt/core.h:757: error: undefined reference to 'fmt::v6::internal::assert_fail(char const*, int, char const*)'
    ```
    
    Note that the symbol exists, but is local:
    
    ```
    $ nm -C libfmtd.so.6.1.3  | grep assert_fail
                     U __assert_fail
    0000000000233ffa t fmt::v6::internal::assert_fail(char const*, int, char const*)
    ```
    
    With this patch, the compile error is gone and the symbol is properly
    exported:
    
    ```
    $ nm -a bin/libfmtd.so -C | grep assert_fail
                     U __assert_fail
    00000000002366ba T fmt::v6::internal::assert_fail(char const*, int, char const*)
    ```
    
    Change-Id: I96054e622d9a2ae81907e1b01a1033e629767a91
  - Apply coding conventions
    
  - Configure fmt.pc library name correctly.
    
    Simplify getting library name.
    
    Add FMT_DEBUG_SUFFIX variable.
    
  - Fix formatting std::chrono::duration types to wide strings (#1533)
    
    * Fix formatting chrono durations to wide strings
    
    * Make format buffers const correct
    
    * Add FormatWide chrono test case
    
    * Fix incorrect wide encoding of 'µs'
    I think might be a source file encoding issue, so I used \u00B5 instead.
    
    * Update FormatWide test to use proper encoding of µs
    
    * Revert changes to format_localized's parameters
    
    * Use different overload of `std::time_put<T>::put` to avoid needing a format string
    
    * Use utf8_to_utf16 instead of having redundant overloads of get_units
    
    * Revert some minor changes
    
    * Remove FMT_CONSTEXPR from expression
    
    This should hopefully fix compilation on VS <2019
    
    * Make suggested changes from code review
    
    * Run clang-format on chrono.h
    
    * Make sure unit isn't null before constructing a string_view from it
    
  - Disallow passing non-string-literals to FMT_STRING
    
  - Fix length computation of constexpr C strings
    
  - fix interal compiler error when building with mingw
    
  - Fix so can work without locale defined
    
    If `FMT_STATIC_THOUSANDS_SEPARATOR` defined, then locale is not included or defined, so this call will be unresolved.  I think this is the correct fix based on the code in `format-inl.h` and `format.h`
  - Add locale example
    
  - Workaround a bogus MSVC warning
    
  - Add namespaces
    
  - Add more examples
    
  - Update fill docs
    
  - Test invalid fill
    
  - Bump version
    
  - Add variable-width fill support (#1109)
    
  - Avoid unnecessary unsigned overflows (#1515)
    
  - Remove static and simplify names
    
  - Add a locale example
    
  - Move docs to the proper place
    
  - update format
    
  - re-fix url link
    
  - fix url link
    
  - Correct display format
    
  - Add vcpkg installation instructions
    
  - Remove redundant braces
    
  - Avoid namespace clash for fmt
    
    ## Problem
    
    In the case of an existing `fmt` namespace (in my project this looks like `Project::fmt`) it is possible to get a namespace clash in debug builds (MSVC 2017)
    
    ## Proposed Solution
    
    When referencing `fmt` internally, be explicit that it is relative to the global namespace using `::fmt`
  - Use C++11 compatible std::is_same operations
    
    The `operator()` member function of `std::is_same` was added in C++14.  For C++11, the `::value` needs to be used instead.
  - Use type_identity to block unnecessary template argument deduction (thanks Tim Song)
    
  - Work-around for nvcc 
    
    The nvcc compiler (at least up to 9.2) defines `__SIZEOF_INT128__`, but doesn't support 128-bit integers on device code:
    ```
    error: "fmt::v6::format_arg_store<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char>>, char>, const char *, int, const char *>" contains a 128-bit integer, which is not supported in device code
    ```
  - Use C++11-compatible operations
    
    The `std::is_base_of<T,U>()` and `std::is_reference<T>()` member functions were added in C++14.  To maintain C++11 compatibility, use the `::value` instead.
    
    Current code fails on intel-17 and other compilers if using strict C++11
  - Fix for older versions of intel compiler
    
    The intel-17 and intel-18 compilers seem to require that `u` be `const`:
    ```
    /src/fmt/format.h(226): warning #437: reference to local variable of enclosing function is not allowed
            char data[sizeof(u)];
    ```
    If `u` is declared as `const auto u =1u` instead of just `auto u=1u`, the file compiles with no warnings.
  - Use FMT_NOEXCEPT instead of noexcept directly
    
    Otherwise breaks on compilers without noexcept support
    
  - Improve join docs
    
  - check if _SECURE_SCL is defined not equal to 0
    
  - Optimize grisu_gen_digits
    
  - Restructure float_format
    
  - Fix handling of output iterators in format_to_n (#1506)
    
  - Move vprint_mojibake to the internal namespace
    
  - Catch invalid uses of fmt::arg
    
  - Convert 'char8_t' character sequences to 'char' sequences
    
    Otherwise, Google Test will insist on inserting 'char8_t' NTBS into 'char' streams, but basic_ostream<char>::operator<< overloads taking 'char8_t' arguments are defined as deleted by P1423.
    Handling individual 'char8_t's is done inline.
    
    This fixes the compilation errors seen in C++20 mode beginning with VS2019 Update 2.
    
    Signed-off-by: Daniela Engert <dani@ngrt.de>
    
  - Suppress a bogus -Wdouble-promotion warning
    
  - Simplify example
    
  - More showpoint fixes and tests (#1498)
    
  - Clarify lifetime of basic_format_args
    
  - Update syntax.rst
  - Update syntax.rst
  - warning C4267: 'argument': conversion from 'size_t' to 'DWORD', possible loss of data
    
  - Update apidoc
    
  - Add fmt::bytes
    
  - Deprecate u8string_view
    
  - Enable mojibake
    
  - Improve UTF-8 handling on Windows
    
  - Improve UTF-8 handling on Windows
    
  - Flatten forward
    
  - Improve UTF-8 support
    
  - Handle block boundaries in utf8_to_utf16
    
  - Apply clang-format
    
  - Make type a scoped enum
    
  - Make round_direction a scoped enum
    
  - Add os.h to docs
    
  - Add trailing decimal point if # is specified (#1476)
    
  - trailing_zeros -> showpoint
    
  - Simplify FMT_STRING_IMPL
    
  - Apply clang-format and update inclusion guards
    
  - Eliminate NVCC NVidia compiler emits unreachable code warnings
    
    Similar to the MSC Compiler, the NVidia NVCC compiler also
    emits unreachable code warnings when there is a return
    statement following an exception.  These changes eliminate
    those warnings.
    
  - Handle block boundaries in utf8_to_utf16
    
  - Chore(readme): use https (#1481)
    
    
  - Mitigate MSVC issue with min/max macros (#1480)
    
    
  - Rename posix-test to os-test
    
  - posix.cc -> os.cc
    
  - Move OS-specific APIs to a separate header
    
  - Implement utf8_to_utf16 using utf8_decode
    
  - Add a UTF-8 decoder
    
  - Give an error on precision overflow
    
  - Avoid shadowing warnings in FMT_STRING
    
  - Apply a typo fix retroactively
    
  - Fix a typo
    
  - Squelch MSVC warning exporting subclasses of runtime_error (fix for PR #1433) (#1470)
    
    * Squelch MSVC warning exporting subclasses of runtime_error
    
    When compiling {fmt} as a DLL, MSVC complains that we are exporting
    classes that inherit from "std::runtime_error", which we are not
    exporting.
    
    In this case, it's not really a problem because that symbol is already
    exported via the C++ stdlib. So we just add a pragma to silence the
    warning.
    
    * Fix compilation with MinGW
    
    Commit 3bc28fcc6b2a ("Squelch MSVC warning exporting subclasses of
    runtime_error", 2019-11-29) silenced a MSVC warning under. The MinGW
    compiler also defines _WIN32, but does not support the "warning" pragma.
    
    Introduce a helper macro to squelch the MSVC warning only when using the
    Microsoft compiler.
    
    Signed-off-by: Beat Bolli <dev@drbeat.li>
    
    * Fix compilation with VS2015 (#1450)
    
    VS2015 does not support the __pragma(...) syntax in the midst of a
    class declaration, so move it to just before the declaration.
    
  - Improve error reporting
    
  - warning C4468: 'fallthrough': attribute must be followed by a case label or a default label
    
  - Merge branch 'master' of github.com:fmtlib/fmt
    
  - Extend FMT_FALLTHROUGH compatibily to gcc and clang pre-C++17 (#1469)