Update git submodules
* Update hardware/ril from branch 'master'
  to 180d9e2e0410a5ba61ae0444cf46a830f204d071
  - Merge "Fix -Wformat error with explicit void* -> char* cast."
  - Fix -Wformat error with explicit void* -> char* cast.
    
    hardware/ril/reference-ril/reference-ril.c:1841:46: error: format specifies type 'char *' but the argument has type 'void *' [-Werror,-Wformat]
        snprintf(cmd, sizeof(cmd), "AT+CCHO=%s", data);
                                            ~~   ^~~~
    
    Bug: http://b/155835175
    Test: m
    Change-Id: I7fd819c6c452b56aae15429344320c4cdaed702c
    (cherry picked from commit 363b39bbc81a3269fe75bd5f505289f85d05792e)