Update git submodules
* Update system/apex from branch 'master'
  to e2d790f9220f2b676e5e20674fb76dc5628cbec2
  - Enable com.android.support.apexer only for linux_glibc_x86_64 target
    
    With the addition of linux_bionic_arm64 host target, this test apex
    automatically gets enabled for the cross host target. However, some
    dependencies of this apex like soong_zip, etc. are not available for the
    cross-host target.  As a result, we get the following errors:
    
    error: system/apex/apexer/Android.bp:104:1: dependency "merge_zips" of
    "com.android.support.apexer" missing variant:
      os:linux_bionic, arch:arm64
    available variants:
      os:linux_glibc, arch:x86_64
    error: system/apex/apexer/Android.bp:104:1: dependency "soong_zip"
    of "com.android.support.apexer" missing variant:
      os:linux_bionic, arch:arm64
    available variants:
      os:linux_glibc, arch:x86_64
    
    Fix the problem by disabling this apex for targets where the tools are
    not available.
    
    Bug: 159685774
    Test: HOST_CROSS_OS=linux_bionic HOST_CROSS_ARCH=arm64 m
    
    Change-Id: Ie79b116438da3b08d3aba65391affa409a3dfa36