Update git submodules
* Update external/zlib from branch 'master'
  to 28320305b90e717b351c5538358a840ec3620bc0
  - Merge "Upgrade zlib to 89bddfee9cf8fde3ab1212ed63bf03d76baf8914"
  - Upgrade zlib to 89bddfee9cf8fde3ab1212ed63bf03d76baf8914
    
    Change-Id: I4085bcf0f2d4ae3ec2935beb443187aae49b183f
    
  - mac/arm64: Make zlib actually link.
    
    This is a follow-up to https://chromium-review.googlesource.com/c/chromium/src/+/2271018
    which made the initialization at arm_cpu_enable_crc32 build-time constant for mac/arm64.
    However, since there are a few callers of cpu_check_features() in cross-platform
    zlib code, we still need to give cpu_check_features() an (empty) implementation
    on mac/arm. (...or add preprocessor checks for mac/arm at each calling site,
    which seems worse.)
    
    Bug: 1099892
    Change-Id: I65785c2e815d80d7e50f25280963ed5aba66304c
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2284145
    Auto-Submit: Nico Weber <thakis@chromium.org>
    Reviewed-by: Mark Mentovai <mark@chromium.org>
    Commit-Queue: Nico Weber <thakis@chromium.org>
    Cr-Original-Commit-Position: refs/heads/master@{#785570}
    Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
    Cr-Mirrored-Commit: 64cf0064494d35e48dcb9cf253e18b270fa58c57
    
  - mac arm64: add support for this new configuration to zlib
    
    While compiling third_party/zlib/cpu_features.c, for example during
    https://ci.chromium.org/p/chromium/builders/ci/mac-arm64/661:
    
    ../../third_party/zlib/cpu_features.c:83:13: error: unused function '_cpu_check_features' [-Werror,-Wunused-function]
    static void _cpu_check_features(void)
                ^
    
    macOS support for arm64 is expected to have a high baseline requirement
    for extensions such as crc32, so rather than doing runtime feature
    detection, assume presence. crc32 is mandatory in ARMv8.1-A per ARM DDI
    0487F.b (current), and all Apple ARM A-series CPUs since A10 (2016)
    implement at least ARMv8.1-A.
    
    Bug: 1099892
    Change-Id: I9d7a113b5c88f9779f95baf4ef0724aa4158c721
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2271018
    Auto-Submit: Mark Mentovai <mark@chromium.org>
    Commit-Queue: Adenilson Cavalcanti <cavalcantii@chromium.org>
    Reviewed-by: Adenilson Cavalcanti <cavalcantii@chromium.org>
    Cr-Original-Commit-Position: refs/heads/master@{#783353}
    Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
    Cr-Mirrored-Commit: 5e82a80c084052276d274061fb694f59aa3fffa2
    
  - mac: enough to make `target_cpu = "arm64"` make it through `gn gen`
    
    Doesn't build at all, but hey, it's a start.
    
    Bug: 1098899
    Change-Id: I63500b3650b315c47219614cc9ae9a3ddbcf42c5
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2264499
    Commit-Queue: Mark Mentovai <mark@chromium.org>
    Auto-Submit: Nico Weber <thakis@chromium.org>
    Reviewed-by: Mark Mentovai <mark@chromium.org>
    Cr-Original-Commit-Position: refs/heads/master@{#782116}
    Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
    Cr-Mirrored-Commit: 0347dc10a71fbb47457f639f7f908bdeaafbebc8
    
  - Remove/replace unnecessary includes of logging.h (various third_party/)
    
    If the file just needs the CHECK/CHECK_OP/NOTREACHED
    macros, use the appropriate header for that instead.
    Or if logging.h is not needed at all, remove it.
    
    This is both a nice cleanup (logging.h is a big header,
    and including it unnecessarily has compile-time costs),
    and part of the final step towards making logging.h no
    longer include check.h and the others.
    
    Bug: 1031540
    Change-Id: I96a2faa1a6ae358cd3d81c556139e2c4689e1c24
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2263835
    Commit-Queue: Hans Wennborg <hans@chromium.org>
    Commit-Queue: Nico Weber <thakis@chromium.org>
    Auto-Submit: Hans Wennborg <hans@chromium.org>
    Reviewed-by: Nico Weber <thakis@chromium.org>
    Cr-Original-Commit-Position: refs/heads/master@{#781849}
    Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
    Cr-Mirrored-Commit: c5691bdf6d4c9adc50550efa456be52e1c21ac9a
    
  - Include-what-you-use related to logging.h (various third_party dirs)
    
    Add direct includes for things provided transitively by logging.h
    (or by other headers including logging.h).
    
    This is in preparation for cleaning up unnecessary includes of
    logging.h in header files (so if something depends on logging.h,
    it needs include it explicitly), and for when logging.h no longer
    includes check.h, check_op.h, and notreached.h.
    
    Bug: 1031540
    Change-Id: Ib0673654853166ba85d84113357d1dbf40ef466f
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2252147
    Auto-Submit: Hans Wennborg <hans@chromium.org>
    Reviewed-by: Nico Weber <thakis@chromium.org>
    Commit-Queue: Hans Wennborg <hans@chromium.org>
    Cr-Original-Commit-Position: refs/heads/master@{#780423}
    Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
    Cr-Mirrored-Commit: 21fc1479bb816a1d05a773e76a855c62f9628340