Update git submodules
* Update device/google/cuttlefish from branch 'android11-gsi'
  to 76dba97fcf3608c81b6e38e0a98c20eae6f7e83d
  - Reject attestations requesting DEVICE_UNIQUE_ATTESTATION.
    
    The keymint specification does not allow these attestations for
    implementations that identify as TRUSTED_ENVIRONMENT, only STRONGBOX.
    
    Bug: 172031303
    Test: atest VtsHalKeymasterV4_1TargetTest
    Change-Id: I0decca4047b946e4e1325b2204325cabe5ca177d
    (cherry picked from commit 4a1902d440c210c60f6cc8a56693612b47738dca)
    Updated to return the value rather than using a pointer.
    
  - Switch to TpmGatekeeper by default.
    
    Test: Set a lock screen password and fail the lock screen several times
    Test: atest VtsHalGatekeeperV1_0TargetTest
    Bug: 162770156
    Change-Id: I79aed9c298a0551cbe1d647d48c1145395f1f772
    (cherry picked from commit 5238965244d0f734d059257fb23eedd4474632aa)
    
  - Revert "Revert "Switch to host gatekeeper""
    
    This reverts commit 74bfc451240aec76f45ee9124927856998b1aa26.
    
    Bug: 155694540
    Test: atest VtsHalGatekeeperV1_0TargetTest
    Test: Set a lock screen password
    Change-Id: Icba478902ee8e3e3a59265ab1b5898f9e6ed02e8
    (cherry picked from commit ee3790a855db405a7a82f8f3ef778819836138bc)
    
  - Fix uninitialized data bug, add error logging to RemoteGatekeeper
    
    Test: Set a lock screen password with RemoteGatekeeper enabled
    Bug: 155694540
    Change-Id: If0eecff14f707a184771799091664fcba52982d9
    (cherry picked from commit 075ce444c58756c5b83a98fe93ed4f4c5114d49a)
    
  - Scale the timeout value in auth_token_timed_out.
    
    The value given to KeymasterEnforcement::auth_token_timed_out is given
    in seconds rather than milliseconds.
    
    References:
    https://cs.android.com/android/platform/superproject/+/master:system/security/keystore/keymaster_enforcement.cpp;l=475;drc=ff3d7f4b83dd9a3fcbc8e502033923336e0dea20
    https://cs.android.com/android/platform/superproject/+/master:device/google/cuttlefish/host/commands/secure_env/tpm_keymaster_enforcement.cpp;l=73;drc=8b1bf9ac9e6bf207e6b70a1e1e660527748922a5
    
    This bug resulted in the test failure seen in b/168642961
    
    Bug: 155694540
    Test: atest CtsDevicePolicyManagerTestCases:com.android.cts.devicepolicy.ManagedProfilePasswordTest#testRebootDevice_separatePasswords -- --abi x86
    Change-Id: Ic42c7209a09da607f1665df50d8842c8c842293b
    (cherry picked from commit d68714f994b69f945acb9e7682a3bde91dbd202a)
    
  - Use SoftKeymasterLogger to expose keymaster logs.
    
    Keymaster internally uses its own logging system. This wires it up to
    the host logging system so the logs will appear in launcher.log as part
    of the secure_env process logging.
    
    This was discovered and resolved by jdanis@.
    
    Test: Add a LOG_E message to keymaster internals, check launcher.log
    Bug: 175080122
    Change-Id: I22bde00aed311c6774f83acc08a2c21e6e75141f
    (cherry picked from commit 5db5b47a6eac5cccf4f393a3d86b9e92b05376c7)
    
  - Fix KeyAttestationTest failures on Cuttlefish.
    
    * Prevent Cuttlefish's TEE from attesting attestationApplicationId.
    * Add OS version and patch level to key blob in Cuttlefish's TEE.
    
    Fix: 168870109
    Bug: 155697375
    Test: atest KeyAttestationTest
    
    Change-Id: I8544ca5f6b22319b6725e4e9cb5ad3530d58b16a
    (cherry picked from commit 75373ae3bf34283702551d267bf2c91c370b9afb)
    
  - Convert raw pointer members to references.
    
    This is now allowed by the style guide. The benefit is to lock down
    reassignment and make nullability clearer.
    
    Test: launch_cvd
    Change-Id: I180e5d8ff471306eb63fdae1004b3d329468918a
    (cherry picked from commit 2b1a5d6f3bd49a89bdbfba0c91a7e19f70230711)
    
  - Use TpmKeymasterEnforcement in secure_env
    
    Test: launch_cvd
    Bug: 155694409
    Change-Id: Ia709ab70d4f318ffcec735791436aa8d70ee09b5
    (cherry picked from commit 20b3954ff4c51ae579f073867d771c24f94bbff7)
    
  - TPM-based KeymasterEnforcement implementation.
    
    Shares data with the existing TPM Gatekeeper implementation.
    
    Test: m -j
    Bug: 155694409
    Change-Id: I37017b957d38b3f9271743b78ad9c985a7e40c72
    (cherry picked from commit 5a0b2834a2f969fd95ef8408b0806431534695bd)
    
  - Add TpmGatekeeper integration to secure_env.
    
    This allows using the TPM-backed gatekeeper instead of the pure software
    one.
    
    Test: m -j
    Bug: 162770156
    Change-Id: I0274d2af979c93beb46da9296f10690a00a9efba
    (cherry picked from commit acb1bc5023372382c2a4f58a3782e5db46a0563b)
    
  - Add storage methods to TpmGatekeeper.
    
    These delegate to the previously defined GatekeeperStorage abstraction
    to save the sensitive data on a secure storage medium.
    
    Bug: 162770156
    Test: m -j
    Change-Id: Iaeb06b00930605b3a6557b9b6fcd2195bea8aa06
    (cherry picked from commit 36232e23d399a007481b830cd3bc80586b09087f)
    
  - Add a TPM-backed gatekeeper implementation.
    
    This uses a signing key resident inside the TPM to produce
    authentication tokens.
    
    Bug: 162770156
    Test: m -j
    Change-Id: I5937fad7c6a5c47b6b9aceb5d5b4f16a869e3ab2
    (cherry picked from commit dcd0c8c02e5798f395010d267b02fd928a76c278)
    
  - Add an InsecureFallbackStorage implementation of GatekeeperStorage.
    
    This fallback storage mechanism stores all its data in the index file,
    making it susceptible to the rollback attacks that work against the
    protected json files.
    
    Bug: 162770156
    Test: m -j
    Change-Id: I548421eab952610bc53ee1e42da2e8d2eedb62d1
    (cherry picked from commit 867295690070bb1870f8ca898716e6f1c779fd37)
    
  - Add a FragileTpmStorage implementation of GatekeeperStorage.
    
    This uses a protected json index file, with sensitive data stored inside
    the TPM itself using TPM non-volatile memory. This means that
    substituting the protected index file with an older version won't roll
    back the value stored at a particular key in the index.
    
    Test: m -j
    Bug: 162770156
    Change-Id: I2bb85e66eba8b3be8d418674db649e351fc603a7
    (cherry picked from commit deecdc5f7cf5d7e0ae0be34060d6d3d4778aaef8)
    
  - Add functions to serialize json to a file, protected by the TPM
    
    This data can only be decrypted with access to the TPM. It can be
    corrupted or destroyed but only in obviously noticeable ways. However, one
    deficiency is a present version can be replaced with a past version
    without it being obvious.
    
    Test: m -j
    Bug: 162770156
    Change-Id: I08dbb50d8e3e9ee08d1da6acb1e3d970fc5f5132
    (cherry picked from commit 9031d4fc216a316db2ad6600e52c815a8de5763e)
    Update: added the libjsoncpp dependency
    
  - Add a GatekeeperStorage interface.
    
    This will be implemented with a more-secure default implementation and a
    less-secure fallback implementation.
    
    Test: m -j
    Bug: 162770156
    Change-Id: Ifcf46dc85716d2203e5f668f1785a257bb5c9772
    (cherry picked from commit e0c08a3fc7aa8a7cdb7197ef5fb1a3416a747dad)
    
  - Extract logic to create TPM primary keys to a separate file.
    
    Bug: 162770156
    Test: launch_cvd
    Change-Id: I526629e078b1f1dd2b681154153d107c29253c8c
    (cherry picked from commit 06c08827561ced8591557c17a8f83c279a6abc5a)
    
  - Always reset Dictionary Attack Lockout for the in-process TPM.
    
    The in-process TPM is likely to experience many disorderly shutdowns,
    which can trigger a Dictionary Attack Lockout that has to be explicitly
    reset.
    
    Test: launch_cvd multiple times, kill it while it's starting up
    Bug: 166843389
    Change-Id: I22c962bf329fb8ca6750668cd809f38cec725922
    (cherry picked from commit f10b45ecc5d1b29ac456d49c5e762f6b3ecfea7c)
    
  - Fix reboots by removing a call to Esys_Clear.
    
    This call is not necessary to set up the TPM. Running this every boot
    also wipes some internal TPM state used in key management.
    
    Specifically, this fixes the error of
    
    secure_env E 08-14 16:43:00 1089957 1089970 hmac_serializable.cpp:119] Signature check did not match original signature.
    secure_env E 08-14 16:43:00 1089957 1089970 tpm_key_blob_maker.cpp:288] Failed to deserialize key.
    
    when running
    
    launch_cvd --daemon
    stop_cvd
    launch_cvd
    
    Bug: 164530585
    Test: launch_cvd multiple times without resetting data
    Change-Id: I7a2398ac771e5f3ee6763f228da05217caf3fb64
    (cherry picked from commit c617ccb982deccd656be9d7575fd32529aa49f57)
    
  - Switch the default to the TPM keymaster context.
    
    Bug: 155695501
    Test: launch_cvd
    Change-Id: I48ddf7dd67eeee21c26aa4368c992cdfd8726f88
    (cherry picked from commit 57fa5be27fb2d3cfb66517546e2dcb6768a9bf2b)
    
  - Fake out KeymasterContext::GenerateAttestation.
    
    Implementation that signs the certificate with a TPM-resident key is
    still TODO.
    
    Still fails a CTS test with:
    STACKTRACE:
    java.lang.Exception: Failed on curve 0 challenge 0 purpose 0 includeValidityDates true and devicePropertiesAttestation true
            at android.keystore.cts.KeyAttestationTest.testEcAttestation(KeyAttestationTest.java:181)
    ...
    Caused by: java.lang.AssertionError: Attestations must not contain any extra data
    Expected: is an empty collection
         but: <[2.5.29.35, 2.5.29.15]>
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
            at android.keystore.cts.KeyAttestationTest.checkUnexpectedOids(KeyAttestationTest.java:711)
    
    This looks like it is another instance of b/158212234 and b/149746301.
    
    Bug: 155695501
    Test: Treehugger
    Change-Id: I2ad89beeae8ede46d31b3591d22bef4e5a732def
    (cherry picked from commit 0d50b819de69c303278567655bf6352fc225f8be)
    
  - Implement KeymasterContext::UpgradeKeyBlob with a TPM.
    
    Bug: 155695501
    Test: Treehugger
    Change-Id: I26e3b310e798296773823de90e461c404042d5af
    (cherry picked from commit 4a6d5a59a192d29d62b32fa768356d8bcc759e55)
    
  - Attach the key origin to the hw_enforced property set.
    
    Bug: 155695501
    Test: atest CtsKeystoreTestCases
    Change-Id: I0a169826fe7d8b4a0ffc39b1de78609825cced87
    (cherry picked from commit 32e75bf96b75f43699edef57bc7f670d99bc7f1c)
    
  - Fix bug with hmac calculations on long strings.
    
    Bug: 155695501
    Test: atest CtsKeystoreTestCases
    Change-Id: I13e2f74a27d486f9353c15aa6c7ae6b2e1766e36
    (cherry picked from commit ee55dc51a3d1e97f744070014b40e1e70edc42ac)
    
  - Implement KeymasterContext::AddRngEntropy with a TPM.
    
    Bug: 155695501
    Test: Treehugger
    Change-Id: I0766e955f301ee82edf9a7b2efd24b7a7a595a28
    (cherry picked from commit a729ba435f5494041f3d67ec1e20b4887f15eb1d)
    
  - Add host support for gatekeeper.
    
    SoftGateKeeper is imported from here:
    https://cs.android.com/android/platform/superproject/+/master:hardware/interfaces/gatekeeper/1.0/software/SoftGateKeeper.h;drc=43773f6c42191841fbd030e298e223e3e27206e1
    
    Test: make -j && launch_cvd
    Bug: 155694540
    Change-Id: I6e82747a045b43f5d50c3c6dac8aa8e769ba1992
    (cherry picked from commit b22e34e63978f78d9a5e47c3c0ef6f120902b9fd)
    Updated to use dynamic vsock port allocation.
    
  - Import TrustyGateKeeper as RemoteGateKeeper
    
    Comes from here:
    https://cs.android.com/android/platform/superproject/+/master:system/core/trusty/gatekeeper/;drc=a4eaf64de8727e870cdea23be203268405c8606d
    
    Test: m android.hardware.gatekeeper@1.0-service.remote
    Bug: 155694540
    Change-Id: I1c10485bc1fb212302ab91119fac6693649ea87e
    (cherry picked from commit b8fcb35b5a38808da7dec2434c0eb98571fb0512)
    Updated to use vendor_ property sepolicy prefixes.
    
  - Add a GateKeeper communication channel.
    
    Test: make -j
    Bug: 155694540
    Change-Id: Ifba8eeb009b36fa9fad07af9b90ee4ebf4a9766e
    (cherry picked from commit e9cfbc252e6eb9eb0fd94f96201d43fdd93552ee)
    
  - Update secure env to support using the in-process TPM.
    
    Test: launch_cvd
    Bug: 155695501
    Change-Id: Ia1d896d7c329430b93dea0c25e019563d5ceb3ff
    (cherry picked from commit e9f19892506c7b7bd4779f3cf5dd404d42f55060)
    
  - Fix TpmHmac to take a const data argument.
    
    Test: m -j
    Bug: 155695501
    Change-Id: Iddf7d502561303aeaf0fb9f4c52c4a1698e10f06
    (cherry picked from commit e304f694544091792387c72fc32aea89af3d2c8a)
    
  - In-process TPM
    
    Bug: 157948411
    Test: make -j
    Change-Id: I34f32ff9af142ff9a728ce91ba6971b18a86f1a5
    (cherry picked from commit e3be3ff3f7c03f10d2b975ecf53eb4bc563b10eb)
    Updated: Added NVChip to preserving list
    
  - TPM command logging utilities.
    
    Taken from here:
    https://cs.android.com/android/platform/superproject/+/master:device/google/cuttlefish/guest/commands/vtpm_manager/commands.cpp;drc=70057e8f6b766bca0bb8cd010d83a1e57fba78aa
    
    Bug: 157948411
    Test: make -j
    Change-Id: Ief89158f57929448ecf62e28ab7c94563fb0e07f
    (cherry picked from commit ae2978a0ebcaaec191298f14be1fc30150e3c281)
    
  - TPM-based Keymaster context.
    
    Test: make -j
    Bug: 155695501
    Change-Id: I0d70e963241d6f7bf04bb21a9bc222f1df881270
    (cherry picked from commit 63223a6b4e3beab1b0f9fa9b95149de32e51c8aa)
    
  - TPM key blob maker. Ensures privacy and integrity.
    
    Bug: 155695501
    Test: make -j
    Change-Id: I2e6053aac49e292a0d5f1537552f372b9ff54655
    (cherry picked from commit 14baf20115f8bbbc9d7e2a120e3e192579c5f27e)
    
  - Add a Serializable that encrypts its data, ensuring data privacy.
    
    Bug: 155695501
    Test: make -j
    Change-Id: Ib115892ce22b9b639a76f073cdd2be5bdaea9ad4
    (cherry picked from commit feefd6c2d505ee7221a366742f68a3f5498a9c7a)
    
  - Add a convenience wrapper for TPM2_EncryptDecrypt2.
    
    Bug: 155695501
    Test: make -j
    Change-Id: Id2e3f58cdff6c997995e5584003d25f9fc8ece15
    (cherry picked from commit d7cb5170ae000d1b745652c90cc71943209f9bb6)
    
  - Implement an integrity-validated wrapping Serializable class.
    
    Bug: 155695501
    Test: make -j
    Change-Id: If1b53a15f53f47158ca6679af345a56a3fc35066
    (cherry picked from commit 836bacc2b593ab3a7dd302637f3ad31c21825e91)
    
  - Add a TpmHmac function to sign arbitrary binary data.
    
    Bug: 155695501
    Test: make -j
    Change-Id: I3eeceb9c94921b9fc273c8ab4c98d13644d26323
    (cherry picked from commit af7a723761af6dcc7e8ae1996ec31069b574b3ae)
    
  - Generic serialization of a composite type.
    
    Bug: 155695501
    Test: make -j
    Change-Id: I16100bc0fba7a343ddcf8211481bfd9fc882695e
    (cherry picked from commit 5114694f565267fbc1c9d7e531e859d9d85a9dbe)
    
  - Integration between TPM marshalling and Keymaster serialization.
    
    Bug: 155695501
    Test: make -j
    Change-Id: I8242f5d9ae851c00d4fcc19b474ea6bef1145c61
    (cherry picked from commit 391aa473487be214c660dcd0ff88715538ac3538)
    
  - TPM Resource Manager: track in-TPM memory usage.
    
    Bug: 155695501
    Test: make -j
    Change-Id: Id6c5a3ab98ef43fb66738803d6d312a38f1cb824
    (cherry picked from commit 3b3a05f2090064821446d60702d0de8fe891ad63)
    
  - Allocate heap memory for the keymaster context.
    
    Fixes a double free, discovered by natsu@.
    
    Bug: 155328335
    Test: N/A
    Change-Id: I20729a299099c3a060c798a6bcbf3d6aaccc6d10
    (cherry picked from commit 9b95a52fbf182c823a895a344399da313b6bdbe8)
    
  - Add a tpm2 authorization wrapper class.
    
    This is a convenience function for calling tss-esys methods.
    
    Bug: 155695501
    Test: make -j
    Change-Id: Icb681a699dd63b44138f408acfd10b766fed7617
    (cherry picked from commit 7e60f761f12491e6c7509836c129a069d999c7ef)
    
  - Revert "Revert "Implement keymaster::RandomSource based on a TPM.""
    
    This reverts commit bda6834637ddf30272fa92e5e30b9f5c17df1f17.
    
    Revert + add extra missing dependencies.
    
    Bug: 155694540
    Test: TreeHugger
    Change-Id: I6e39bf7ce61be08c0705f3982db40af1b4509a88
    (cherry picked from commit 0193e335bf7cf83dbca26953b53ac31d97d56b14)
    
  - Switch to host keymaster
    
    Bug: 155328335
    Test: launch_cvd
    Change-Id: Ib54d7e80f0d134e4717a56ea6005cd69042ec928
    (cherry picked from commit c2bddd1d79872877d170496b1bb87bb3c5223c15)
    
  - Upgrade RemoteKeymaster from 4.0 to 4.1
    
    Test: Compiles
    Bug: 158517345
    Change-Id: I8f697ad859ce44cd8bb7e377ef13e364db55cb1f
    (cherry picked from commit c7026352ffa91505001dd227a53cdb22d6fb7394)
    
  - Configure sepolicy for the remote keymaster HAL.
    
    This uses the ro.boot.vsock_keymaster_port to load a port number and
    sends commands over vsock.
    
    Bug: 155328112
    Test: make -j
    Change-Id: Iaddb077fbbeac072595695f793621f658c3332b9
    (cherry picked from commit 4d75cddc47710103a1ec5dfe26ab853c34f8b7df)
    Updated the sepolicy for the property to match other properties.
    
  - Launch secure_env from the host and connect from the guest.
    
    Bug: 155328335
    Test: make -j
    Change-Id: I8b882c0c99cd6ee18e61eb28b69e67204ba67e41
    (cherry picked from commit af4b621f300234e753e35cfa4f7aebc3784c6f12)
    Updated for `namespace cuttlefish` and automatic vsock port assignment.
    
  - Integrate PureSoftKeymaster in secure_env.
    
    Bug: 155328335
    Test: m secure_env
    Change-Id: I45be3620c61c916c790b0f4dc31669af31b334c7
    (cherry picked from commit 03d2effffc5974653401e8c1ecb180ce22a52a64)
    Updated for `namespace cuttlefish`.
    
  - Add a secure_env host command.
    
    From the perspective of Android, this will be the secure environment.
    
    Test: Compiles
    Bug: 155328335
    Change-Id: I569fd54e1b4b2f3afa5d59a2caf329bcbc1daf3e
    (cherry picked from commit ffe42edf10d70cbebc05f5f7814e50bd24273f39)
    
  - Replace keymaster_command with AndroidKeymasterCommand
    
    AndroidKeymasterCommand is defined by keymaster.
    
    Bug: 155328112
    Test: m android.hardware.keymaster@4.0-service.remote
    Change-Id: Iff3c271513e74f003f3f3eeb77057da9044bb61b
    (cherry picked from commit fac587ae58f95569c16c50a1d872a283c135baf3)
    Updated for `namespace cuttlefish`.
    
  - Use KeymasterChannel in RemoteKeymaster.
    
    Bug: 155328112
    Test: m android.hardware.keymaster@4.0-service.remote
    Change-Id: I99044f7c7fddd25b737549b0f00143adb499f996
    (cherry picked from commit 9a5c369384e48f133002fae2edaaf0a26e6894a8)
    Updated for `namespace cuttlefish`.
    
  - Generalize Keymaster communication channel
    
    Bug: 155328112
    Test: m android.hardware.keymaster@4.0-service.remote
    Test: libcuttlefish_security
    Change-Id: Ib11d27ba4deb1b7eb8a4fa212b2dddeedd8ab2f0
    (cherry picked from commit ef439736d0d4fdc869c42c2ddc29d6627ac04e1e)
    Updated for `namespace cuttlefish`.
    
  - Import TrustyKeymaster as RemoteKeymaster.
    
    Files originally from here:
    https://cs.android.com/android/platform/superproject/+/master:system/core/trusty/keymaster/;drc=15351dcf60179cc23d126f7699a0832276acd2ea
    
    Changes made:
     - Renamed TrustyKeymaster to RemoteKeymaster
     - Removed Trusty IPC calls.
    
    Test: m android.hardware.keymaster@4.0-service.remote
    Bug: 155328112
    Change-Id: I22e58ceb16775b0e58cb19272eb066c9a73a5d29
    (cherry picked from commit 5ef76e975103bbafe1108f257e439ec3399c4941)