Autoupdate of 2 submodules
*build/soong updated to 2c3999050b7bc68a77c2415a8258fb786371bdd6
Merge "Enable deprecated-enum-enum-conversion warning"
*system/incremental_delivery updated to 0c13909a84775840c6889a049634741a3c2ec1cc
Suppress deprecated-enum-enum-conversion warning

system/incremental_delivery/incfs/incfs.cpp:553:23: error: bitwise operation between different enumeration types ('IncFsMountFlags' and 'android::incfs::MountFlags') is deprecated [-Werror,-Wdeprecated-enum-enum-conversion]
    if (options.flags & createOnly) {
        ~~~~~~~~~~~~~ ^ ~~~~~~~~~~
system/incremental_delivery/incfs/incfs.cpp:558:30: error: bitwise operation between different enumeration types ('IncFsMountFlags' and 'android::incfs::MountFlags') is deprecated [-Werror,-Wdeprecated-enum-enum-conversion]
    } else if (options.flags & android::incfs::truncate) {
               ~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~

Test: presubmit
Bug: 153746563
Change-Id: I815502169b914f271def7a72b980aa30a940fcfd