Update git submodules
* Update external/autotest from branch 'master'
  to 4d8d4f9d15bfd1d686264a069fa98fda2371f406
  - Revert "servo_host: grab all servod logs since restart" am: 5bd9da1ad0
    
    Change-Id: Ia1b2ffcbfd67548425e995a8ec56696a56e5fb7b
    
  - Revert "servo_host: grab all servod logs since restart"
    
    This reverts commit b0ef0f442f8eb6d8be3da83f78ccbfc972567824.
    
    Reason for revert: https://crbug.com/1066308  "AttributeError: 'NoneType' object has no attribute 'has_control' "
    
    Original change's description:
    > servo_host: grab all servod logs since restart
    > 
    > Servod might crash in the middle of a run for any number of reasons and
    > we need to debug that. This change caches the instance's log timestamp
    > on init, and compares it to the timestamp at the end. If they are not
    > the same, it will find all timestamps (i.e. instances that have run
    > before but were turned down/crashed) between the init timestamp and the
    > current one, and grab those logs as well.
    > 
    > BUG=chromium:1056780
    > TEST=test_that --autotest_dir . $DUT servo_LogGrab --args "servo_host=$LABS"
    >      // test is added in subsequent CL
    > 
    > Change-Id: I60ee7c00a757ed3f9dc2ac87d5c2f0a567266d14
    > Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/2121366
    > Tested-by: Ruben Rodriguez Buchillon <coconutruben@chromium.org>
    > Reviewed-by: Dana Goyette <dgoyette@chromium.org>
    > Commit-Queue: Ruben Rodriguez Buchillon <coconutruben@chromium.org>
    
    Bug: chromium:1056780
    Change-Id: I8f799746d0cbafd5075014ddb6990e8e72e49cd2
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/2129193
    Reviewed-by: Prasad Vuppalapu <prasadv@chromium.org>
    Reviewed-by: Garry Wang <xianuowang@chromium.org>
    Commit-Queue: Prasad Vuppalapu <prasadv@chromium.org>
    Tested-by: Garry Wang <xianuowang@chromium.org>
    Tested-by: Prasad Vuppalapu <prasadv@chromium.org>
    Auto-Submit: Prasad Vuppalapu <prasadv@chromium.org>