Update git submodules
* Update frameworks/native from branch 'master'
  to 4d3171a49c44bbefcbd6384078a07ef9fc1b4572
  - Merge "Parcel: deprecate unique_ptr read/write methods"
  - Parcel: deprecate unique_ptr read/write methods
    
    Since Android R, Parcel provides read/write methods for "@nullable"
    values using std::optional. Deprecating "unique_ptr" versions
    so that the compiler emits errors like following when trying to use
    unique_ptr variants:
    
      error: 'readUtf8FromUtf16' is deprecated: use std::optional
          version instead [-Werror,-Wdeprecated-declarations]
    
    Note that parcel_puzzer/binder.cpp still tests deprecated functions.
    
    Bug: 149784838
    Test: m
    Change-Id: I65fc58333373ce04a871dd5cdbe4b761ce548393