Update git submodules
* Update tools/metalava from branch 'master'
  to 1987d6013dae66915b7151c09fcdbdc31d0ba6d8
  - Use absolute paths for kotlin files
    
    Change https://r.android.com/2319368 caused metalava to find the module
    for Kotlin source files (where module is a set of files, like a source
    root, or a jar). Another set of changes changed how Psi... code handled
    files, switching from relative to absolute that required changes like
    https://r.android.com/2274906.
    
    In combination those changes require that both the source roots and the
    Kotlin files are absolute. This change extracts `parseAbsoluteSources`
    from `parseSources` and then modifies `parseSources` to make all the File
    objects absolute before passing to `parseAbsoluteSources`.
    
    Bug: 281035030
    Test: ./gradlew
          m update-api
    Change-Id: Iebce48a7bea04be92fa9a0c46d8981586af51ebf
    
  - Fix test/build failures caused by update to 31.1.0-alpha01
    
    The failures are due to changes in the linter code to properly support
    SDK extensions (see ag/18185655) which causes the `ApiLookup` code to
    stop using the `since` attribute and use the `sdks` attribute instead.
    Unsurprisingly, the failures are in the SDK extension specific tests.
    
    * Build failures are due to deprecation of `ApiLookup.get*Version(...)`
      methods. They were deprecated in favor of `get*Versions(...)` methods
      that return an `ApiConstraint` instead of an int version. That is
      needed because the introduction of SDK extensions means that there is
      no longer a single version when an API was added.
    * Test failures caused by differences in the results caused by use of
      the `sdks` attribute instead of the `since` attribute.
    
    The tests and the code need to be updated now that the linter properly
    supports SDK extensions. There appears to be some overlap between code
    that uses `SdkAndVersion` and the new code added in `ApiLookup` and
    `ApiConstraint`. The tests also need to set the `sdks` attribute so
    that it is more consistent with the `since` attribute and switch to
    using non-deprecated methods. However, that is outside the scope of
    this bug and doing that work before completing the de-fork will likely
    introduce more conflicts and make de-forking harder.
    
    There appears to be a bug in the implementation of
    `ApiConstraint.min()` which is an alias for
    `ApiConstraint.fromInclusive()`. See b/282932318.
    
    The fixes that are made in this change are:
    * Adding an ApiConstraint.minApiLevel() method that implements the
      correct behavior for `ApiConstraint.fromInclusive()/min()`.
    * Use the new `minApiLevel()` method instead of relying on deprecated
      methods that use the broken `min()` method.
    * Added some information that was missing from the `sdks` attribute
      in one test.
    
    Bug: 281035030
    Test: ./gradlew
          m update-api
    Change-Id: I0dc7e11d4e23211ea38df6e2ac12c2b90705cc22
    
  - Merge commit 'f346488ae1186711265c74e1af59e59f3c4544da' into aosp/master
    
    Relatively clean merge with only one conflict in imports in change
    f346488a. Despite the conflicts that change was chosen as the change to
    merge in because it includes fixes for some test failures that were
    caused by upgrading to 31.1.0-alpha01.
    
    Specifically, it fixes test failures like the following:
    ```
    java.lang.NoClassDefFoundError: Could not initialize class com.android.tools.lint.detector.api.ApiConstraint
    ...
    Caused by: java.lang.NullPointerException: Cannot invoke "com.android.tools.lint.detector.api.ApiConstraint$SdkApiConstraint$Companion.getNO_LEVELS()" because "com.android.tools.lint.detector.api.ApiConstraint$SdkApiConstraint.Companion" is null
    	at com.android.tools.lint.detector.api.ApiConstraint.<clinit>(ApiConstraint.kt:219)
    ```
    
    That are caused by some initialization issues with the ApiConstraint
    class. The following lines from that change seem to fix the issue:
    ```
        // Trigger <clinit> of [SdkApiConstraint] to call `isValidApiLevel` in its companion
        ApiConstraint.UNKNOWN
    ```
    
    The other changes merged in do cause some build and test failures that
    will be resolved in a follow up change. The failures are due to changes
    in the linter code to properly support SDK extensions
    (see ag/18185655) which causes the `ApiLookup` code to stop using the
    `since` attribute and use the `sdks` attribute instead:
    * Build failures are due to deprecation of `ApiLookup.get*Version(...)`
      methods. They were deprecated in favor of `get*Versions(...)` methods
      that return an `ApiConstraint` instead of an int version. That is
      needed because the introduction of SDK extensions means that there is
      no longer a single version when an API was added.
    * Test failures caused by differences in the results caused by use of
      the `sdks` attribute instead of the `since` attribute.
    
    Bug: 281035030
    Test: ./gradlew
          m update-api
    Change-Id: Ie44bb53c4922eb2ccfd1853beacf72c39d0859bd
    
  - Pick safer test API level and ensure it is valid
    
    Bug: 265967163
    Bug: 260225596
    Test: unit test updated
    Change-Id: I1a131fb61ba8067475c589264b69a8a96731449e
    
  - Merge "Update ApiGeneratorTest according to constraints on ApiConstraint" into metalava-main
  - Update ApiGeneratorTest according to constraints on ApiConstraint
    
    Bug: 265967163
    Test: ApiGeneratorTest updated
    Change-Id: Ia248ede7b230752231727ca0eaa232d33897f112
    
  - Start targeting Java 17
    
    Bug: 265967163
    Test: ./gradlew test and IDE runs
    Change-Id: I2fb21b2dd98997ac117ab60a149f5bd884d61cfa
    
  - Upgrade to the newest Android Lint 31.1.0-alpha01
    
    Two tests needed to be updated as lint changed how it takes
    in gziped base64 encoded jars.
    
    Test: ran existing tests
    Fixes: 265638613
    Change-Id: Ib226ed601571305a7f41220d3038bef45495ccc0
    
  - Render nullness suffix for raw type only if there is a hint on type
    
    Workaround added at Ibfc12424306390adf20b7d970c78f626ece0237c
    should be applied only if there is a nullability hint on PsiType.
    
    Bug: 238733178
    Bug: 244408981
    Bug: 260564147
    Test: unit test added
    Change-Id: Ia39410ad7fe6fa905a266c090bfff8cdfac409cd
    
  - Workaround for nullability/type of parameter on @Deprecated
    
    Such @Deprecated methods won't be created by LC, and UAST adds a fake
    PSI instead, including parameters. Parameter type/nullability is
    computed/added by LC, but UAST does so incorrectly while adding a fake
    one (KTIJ-23837).
    
    Until upstream fix is available, this commit adds a workaround for
    handling vararg type and type nullability.
    (Correct type arguments still need an upstream fix.)
    
    Bug: 238733178
    Bug: 244408981
    Bug: 260564147
    Test: unit test modified
    Change-Id: Ibfc12424306390adf20b7d970c78f626ece0237c
    
  - Make metalava studio integration work again
    
    - Build with JDK17
    - Read the right file for the version
    
    Test: presubmit
    Change-Id: I8cdfd092e03adaf6f3a1bf779df75354f0c10720
    
  - Merge "Regression test for throwsList from LC methods" into metalava-main
  - Regression test for throwsList from LC methods
    
    Bug: 261137560
    Test: unit test added
    Change-Id: Ica35dae2bcd0ba7bb2fa32c0dc3e86dd85585b04
    
  - Regression test for APIs before/after @Deprecated(HIDDEN)
    
    Bug: 240475358
    Bug: 244408981
    Bug: 238733178
    Bug: 262033498
    Test: unit test added
    Change-Id: If0683b548006c3315021f7a1f6986f8299b3f4c5
    
  - Merge "Towards frontend-agnostic logic (Analysis APIs)" into metalava-main
  - Merge "Workaround for return type nullability on @Deprecated" into metalava-main
  - Towards frontend-agnostic logic (Analysis APIs)
    
    When K2 UAST arrives, entities in the old frontend, such as
    BindingContext, KotlinType, descriptors, etc., won't be available.
    For smooth transition, we have another layer (frontend of frontends),
    named Analysis APIs, so that frontend usages can be rewritten just once.
    
    There are two frontend usages left in Metalava, and this commit adds
    counterpart logics that use Analysis APIs. Technically, we can remove
    FE1.0 code right now, and AA code works great. For safter transition,
    though, we will keep the old logic for one or two release cycles.
    
    Bug: 229742431
    Test: ./gradlew test
    Change-Id: I831aab798fb9d87b3b8f9816028d465b50119cf5
    
  - Upgrade to Lint 31.0.0-alpha09
    
    Bug: 251845105
    Test: ./gradlew
    Change-Id: I2151e12bd313de1c66ef24940c2fc6bbabdc9128
    
  - Workaround for return type nullability on @Deprecated
    
    Such @Deprecated methods won't be created by LC, and UAST adds a fake
    PSI instead. Return type nullability is added by LC, but UAST forgot to
    do so while adding a fake one (KTIJ-23807).
    Until the upstream fix is available, one workaround is to add a
    nullability annotation if the given UMethod is a delegate to such fake
    PSI and its return type nullability is available.
    
    Bug: 219792969
    Test: unit test modified
    Change-Id: If8941a3ea8b306a7e30e947ebaa986979d87ffe1
    
  - Regression test for companion object in annotation
    
    Bug: N/A
    Test: unit test added
    Change-Id: Ic7a4e95ed32efc700fd19bde396f7c02e65d5f62
    
  - Avoid adding duplicate annotations on properties
    
    Bug: 259424545
    Test: unit test updated
    Change-Id: I385aa4e836570bd21e7051356526e72417ad00d1
    
  - Bump metalava version to 1.0.0-alpha07
    
    Bug: 258477743
    Test: presubmit
    Change-Id: I83a309cc5bdded78b07587c06556723ed3bad5c3
    
  - Revert "Bump metalava version to 1.0.0-alpha07"
    
    This reverts commit 4ed72a3c2cfc700d7c96ac06d780fdb724df2ca4.
    
    Reason for revert: Broke aosp-androidx-main/androidx_with_metalava
    
    Change-Id: Ifc8b2cc126d02ecad61a8b91a6c25b48ffe034ef
    
  - Bump metalava version to 1.0.0-alpha07
    
    Bug: 258477743
    Test: N/A
    Change-Id: Ib9b5e8ea6af577aaad420c170e726de73a8b5778