Merge branch 'upstream-master' into 'main'
* aosp/upstream-master:
  ELF reader test: initialise all fields of SymbolTableEntry
  type roots: document merge support
  Filtering: use "list" as prefix for symbol/file list section
  DWARF processor: use file entry information to filter definitions
  Abigail reader: generalise duplicate member removal
  Abigail reader: fix bad DWARF-ELF links caused by size zero symbol confusion cont.
  Add `--symbol-filter` option as synonym for `--symbols`
  make Methods be exclusively virtual methods
  DWARF processing: support virtual method offset
  Remove non-virtual methods in DWARF and Abigail readers
  Restore the original license text whitespace
  Refactor symbol filter to generic filter
  symbol filter: minor cleanups
  ELF reader: use CFI address for symbols
  ELF loader: add CFI symbol table loader
  ELF loader: fix clang-tidy warning
  ELF reading: match TLS variables by name
  DWARF processing: support virtual base class offset
  DWARF processing: support base class virtuality
  DWARF processing: support base classes
  error: use a wrapper object for hexadecimal output cont.^2
  Abigail reader: fix bad DWARF-ELF links caused by size zero symbol confusion
  Abigail reader: add missing libxml2 include
  Abigail reader: change SetAttribute to take a string value
  README: fix build instructions for CMake build
  CMake: clean up link dependencies
  DWARF processing: refactor DWARF expression manipulation

Change-Id: I82d4c20e75165a5253ff192e25f93ad352a98b67
Signed-off-by: Aleksei Vetrov <vvvvvv@google.com>