Update git submodules
* Update external/toybox from branch 'master'
  to 906148de8f0298d067e0c25f41e1d6001819eec9
  - Merge remote-tracking branch 'toybox/master' into HEAD
    
    Change-Id: I3f5c519cde22e66c9b6e21d2b89a63e0cb5959b6
    
  - Fluff out the FAQ some more and flush pending README changes.
    
    Yes, I need to convert to README.md, it's on the todo list...
    
  - Replace more SKIP_HOST with toyonly.
    
    SKIP_HOST won't run a test when TEST_HOST set, but toyonly runs its arguments
    whenever testing toybox (including when the host version is toybox).
    
  - Annotate sed tests with toyonly.
    
  - Add tests for sed -s
    
  - Add sed -s
    
  - remove unneeded ; after GLOBALS
    
  - portability.c: fix macOS build.
    
    I suspect the rest of the non-POSIX signals might end up like this, but this is the subset that needs to be #ifdef'ed to fix the macOS build.
    
  - route: remove unused get_hostname()
    
  - Trivial cleanup.
    
  - Cleanup pass.
    
  - dhcpd: fix warnings
    
    Add presumably intended conversion specifier for gconfig.valid_lifetime
    as it is an argument to error_msg despite the format string having no
    conversion specifiers.
    Remove always true false inverse check for address of array
    gstate.rcvd.rcvd_pkt6.transaction_id.
    
  - Convert array_add() to arg_add().
    
  - devmem: replace getpagesize with POSIX sysconf(_SC_PAGESIZE)
    
  - Remove unused include and constants
    
  - Merge ipv6 setroute into a single function
    
  - Instead of ifdef linux or macos, just ifdef the signals.
    
  - Fix syntax checking for "if true; then echo hello | fi", fix some tests,
    slightly more elaborate debug output.
    
  - More sh tests.
    
  - First pass of adding RTNetlink setroute support
    
  - Remove send_nlrtmsg embedding call into display_route as it is only used here
    
  - Use perror_exit to replace exit calls.
    
  - Tweak roadmap so status.html is a bit more current.
    
  - Cleanup openvt.
    
  - Cleanup blkdiscard.
    
    Yeah, this limits 32 bit support, but that's a "fix it properly in lib/args.c
    or don't care" issue. Why work around it here when truncate -s doesn't?
    
  - Ahem: have the backgrounding test actually background.
    
    Point is to make sure the consumer waits for all output, not for process exit.
    
  - More shell tests.
    
  - Check the signal rather than special case a library and a target.
    
  - vmstat: increase column sizes
    
    Increase memory:swpd,free,cache to 7 characters
    Increase swap:si,so to 5 characters
    Increase system:in,cs to 5 characters
    
    Sample output from Pixel 4 phone:
    procs ------------memory------------ ----swap--- -----io---- ---system-- ----cpu----
     r  b    swpd    free   buff   cache    si    so    bi    bo    in    cs us sy id wa
     4  0 1111676   87896   6328 2268596  8152 11896 10712 14280     0 25712 31 21 46  3
    17  0 1082788  224292   5972 2213996 73220 68908  2432  3948     1 26611 41 38 22  0
     6  0 1127316  203196   5972 2225164  8980 53996 11796   788     0 25200 33 22 45  1
     0  0 1133072  200984   5972 2225280   416  6260    52    88     0  8543 10  6 84  0
     2  0 1128976  196976   5972 2225692  3588     0   340   800     0  5243  5  4 91  0
    
  - glibc on mips is missing SIGSTKFLT
    
    Do not therefore assume it being available linuxwide
    
    Fixes
    | lib/portability.c:433:3: error: use of undeclared identifier 'SIGSTKFLT'
    |   SIGNIFY(STKFLT), SIGNIFY(POLL), SIGNIFY(PWR),
    |   ^
    
    Signed-off-by: Khem Raj <raj.khem@gmail.com>
    
  - David Legault reported that unescape2() doesn't handle \0 right
    because scanf("0%o") needs a 0 _and_ one or more digits. So add it to
    the end of the \n translation list (where it returns the null terminator).
    
  - Add RTA_CACHEINFO support and resolve remaining todo items in display_routes
    
  - xsignal_all_killers() should install the handler given to it, and do some
    refactoring while I was looking at the codepath.
    
  - The standalone build for "make sh" has more dependencies because MAYFORK.
    
  - Don't leak sockfd into children.
    
  - Merge IPv6 support into display_routes
    
  - Don't ask for line continuation when ending with &
    
  - Allow "make distclean" to fail gracefully when root_download exists.
    (Don't delete it, warn it's there, but don't _not_ run next target.)
    
  - Add support for mss, win and irtt to new netlink based display_routes
    
  - Refactor display_routes to use rtnetlink
    
  - Add xsend, xrecv and send_nlrtmsg
    
  - Fix address family help text
    
  - How to cross compile with 2 compilers and 3 libc.
    
  - URL moved and the automatic redirect triggers https shenanigans.
    
  - Massage TEST_HOST test output (coreutils?) to match toybox.