Update git submodules
* Update frameworks/support from branch 'androidx-master-dev'
  to bba7542147d68edc9f38623ecacdba2d8581bba6
  - Merge "Probe for @hide tracing APIs" into androidx-master-dev
  - Probe for @hide tracing APIs
    
    * TraceCompat APIs are switching to using API 29 methods and catching `NoSuchMethodErrors`.
      This is because its very likely that these methods exist on lower API levels but
      are marked @hide.
    
    Test: Existing unit tests pass.
    Fixes: b/152526219
    Change-Id: I3caa9a67f1fe9b03c2db44879805217092b327fa