Update git submodules
* Update system/core from branch 'master'
  to fded8e696c6aa145dcc9b9a2ddda16a07eec6a29
  - Merge "Fix unused function error for user build"
  - Fix unused function error for user build
    
    ```
    system/core/fs_mgr/fs_mgr_overlayfs.cpp:83:6: error: unused function
    'fs_mgr_is_dsu_running' [-Werror,-Wunused-function]
    ```
    
    Bug: 172405271
    Bug: 165925766
    Test: build aosp_bonito-user, no warning/error
    Change-Id: I3206e5bd13658ab0b7f5826e8e1c206c8df65684