Update git submodules
* Update external/autotest from branch 'master'
  to 18b954ca1fa9abc08988554cbf0cb5df535960ce
  - Revert "[autotest] Absolute imports in client code" am: 32cc561b21
    
    Original change: undetermined
    
    Change-Id: I49cb06f00ab417a2aea22a9c254f5969a0f754ab
    
  - Revert "[autotest] Absolute imports in client code"
    
    This reverts commit 0b69e8c2fbc5d898b564636c890174b8e572a61f.
    
    Reason for revert: errors when these files are executed in non-module context.
    
    Original change's description:
    > [autotest] Absolute imports in client code
    >
    > This CL goes through and replaces Python2-style relative imports
    > with Python3-style explicit relative imports and explicitly turns
    > on the following Python3-compatibility settings: print_function,
    > division, and absolute_import.
    >
    > Reset still fails to execute as Python3, but it fails inside the
    > config parser. The config parser is a dependency of autotest and
    > not part of autotest itself, so fixing it is out of scope for this
    > CL.
    >
    > ```
    >     self._read(fp, filename)
    >   File ".../configparser/__init__.py", line 1086,
    >  in _read
    >     raise DuplicateSectionError(sectname, fpname,
    > backports.configparser.DuplicateSectionError: While reading from '.../global_config.ini' [line 260]: section 'AUTOSERV' already exists
    > ```
    >
    > BUG=chromium:990593
    > TEST=run reset locally as Python2 and Python3
    >
    > Change-Id: If5f009954adab74b37195ddfdd6d24a54b970ec6
    > Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/2438798
    > Reviewed-by: Derek Beckett <dbeckett@chromium.org>
    > Tested-by: Gregory Nisbet <gregorynisbet@google.com>
    > Commit-Queue: Gregory Nisbet <gregorynisbet@google.com>
    
    Bug: chromium:990593
    Change-Id: Ic1c33af540d46b3e7604771c9194b060cb532838
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/2471901
    Tested-by: Gregory Nisbet <gregorynisbet@google.com>
    Commit-Queue: Gregory Nisbet <gregorynisbet@google.com>
    Reviewed-by: Greg Edelston <gredelston@google.com>
    Reviewed-by: Derek Beckett <dbeckett@chromium.org>