Update git submodules
* Update system/media from branch 'master'
  to e8bf0df312efdef330cd943ffe9e97713a2232d1
  - Merge changes I1ea9dec1,I1dbffcbe
    
    * changes:
      Fix build errors on host due to macro __unused
      Update language to comply with Android's inclusive language guidance
    
  - Fix build errors on host due to macro __unused
    
    In file included from system/media/audio_utils/tests/variadic_tests.cpp:22:
    In file included from external/googletest/googletest/include/gtest/gtest.h:62:
    In file included from external/googletest/googletest/include/gtest/internal/gtest-internal.h:40:
    In file included from external/googletest/googletest/include/gtest/internal/gtest-port.h:263:
    In file included from prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/sysroot/usr/include/x86_64-linux-gnu/sys/stat.h:106:
    prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/sysroot/usr/include/x86_64-linux-gnu/bits/stat.h:106:31: error: expected member name or ';' after declaration specifiers
        __syscall_slong_t __unused[3];
        ~~~~~~~~~~~~~~~~~         ^
    prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/sysroot/usr/include/x86_64-linux-gnu/bits/stat.h:164:31: error: expected member name or ';' after declaration specifiers
        __syscall_slong_t __unused[3];
        ~~~~~~~~~~~~~~~~~         ^
    2 errors generated.
    
    Test: build on host
    Change-Id: I1ea9dec1852a8b8bbb0612b58f971272339ef807
    
  - Update language to comply with Android's inclusive language guidance
    
    See https://source.android.com/setup/contribute/respectful-code for reference
    
    Bug: 161896447
    Test: N/A
    Change-Id: I1dbffcbe890dde44c318f57deaddd640f9ff810e