Update git submodules
* Update device/google/cuttlefish from branch 'pie-gsi'
  to 90445b61f576b0f494a3ebf0b4b09f0f21194d4a
  - Exclude hardware features from more AOSP targets
    
    Any AOSP-only target must install this permission, otherwise various *TS
    tests will fail. This was originally added only to 32-bit x86.
    
    Bug: 145127770
    Change-Id: I92540e4af515ccb3d0f5a27120192351b2a25384
    (cherry picked from commit 5a0ed1e17dc2ddb202577c18e19143cc60dff2c9)
    
  - Exclude unavailable features from AOSP build.
    
    Bug: 145127770
    Test: None
    Change-Id: I452385246cad7514130ba329de506c0d2fab9203
    
  - Increase userdata size to 4.25GB
    
    Fixes x86 CtsHardwareTestCases
    android.hardware.cts.LowRamDeviceTest#testMinDataPartitionSize
    
    java.lang.AssertionError: Application data partition size does
    not meet requirement. Found = 4160421888, Minimum = 4294967296
    
    This occurs because the usable space must be above 4GB, not the raw
    partition size.
    
    Fixes: 124520809
    Change-Id: I3c6ae0875f72c8c8c318f3ff194835e7fbd291f3
    (cherry picked from commit 038f406f5e95513c57c2f2c74b6d8563ebeecd22)
    
  - Add ambient_temperature
    
    Add some missing sensors that the new reference HAL supports
    
    Bug: 155989875
    Bug: 170364480
    Change-Id: I2ed8ba758779bc322b486a31b58cab46a80e67ff
    Merged-In: I2ed8ba758779bc322b486a31b58cab46a80e67ff
    (cherry picked from commit ba04c50301d4121b42cad0797dada277ab3e520d)
    [adelva: no relative_humidity sensor on P]