Update git submodules
* Update bionic from branch 'ndk-release-r23'
  to 52fb806266586b2a0b02217ac369deb8febb65bc
  - Merge "Snap for 7120539 from 15ade069b10f7f5291e48c01db2da4852dae04b7 to ndk-release-r23" into ndk-release-r23
  - Snap for 7120539 from 15ade069b10f7f5291e48c01db2da4852dae04b7 to ndk-release-r23
    
    Change-Id: Ibf4fa1a236d28383c1844ff2e533c5a7295fe98f
    
  - Merge changes from topic "builtins-exported"
    
    * changes:
      Use exported variants of arm32/x86 builtins
      Fix -Wl,--exclude-libs typo: x86->i686
    
  - Merge "[MemInit] Remove old API, introduce new MemInit API."
  - Merge "Fix __VERSIONER_NO_GUARD cases for availability."
  - Fix __VERSIONER_NO_GUARD cases for availability.
    
    libc++ still depends on these being declared even if they are
    unavailable. This results in a worse error message (a link error
    rather than a compiler diagnostic) if these functions end up being
    used, but without the decl headers like libc++'s math.h can't be
    included because it refers to an undeclared function.
    
    For the cases where weak symbols aren't being used, don't annotate
    these functions with their availability information.
    
    Also need to avoid using __builtin_available for this case because the
    NDK doesn't have __isOSVersionAtLeast yet.
    
    __ANDROID_UNGUARDED_AVAILABILITY__ is being used as a proxy for
    "building for the NDK" here because we don't have a good signal for
    that which works for both the NDK proper and the NDK-in-the-platform
    case.
    
    Test: imported into the NDK, built and tested NDK
    Bug: None
    Change-Id: I9ef3e19a8fa083bca0be47b80dfef7ba52a94866
    
  - Merge "Sync libm with upstream FreeBSD."
  - Use exported variants of arm32/x86 builtins
    
    For backwards compatibility (e.g. with old apps), arm32 libc.so and
    libm.so export some of the builtins. On 32-bit x86, libc.so also
    exports some of the builtins.
    
    The non-exported variant of the builtins will eventually have hidden
    symbols but doesn't currently because D93431 hasn't been merged into
    our toolchain yet. See:
     - https://reviews.llvm.org/D93431
     - I44ec79728db92c089e2f39823c35b6f97d24c1ab in toolchain/llvm_android
    
    Bug: http://b/153025717
    Test: bionic unit tests
    Change-Id: Ic489cb06a07ef61412502fc65a21b0cf630c11ed
    
  - Fix -Wl,--exclude-libs typo: x86->i686
    
    These lines shouldn't actually matter, because the DSOs are using
    version scripts to allow-list exported symbols.
    
    Bug: none
    Test: bionic unit tests
    Change-Id: I39d3df8c4f8053624f862b3c6994e30c693e928c
    
  - Sync libm with upstream FreeBSD.
    
    Upstream SHA 78599c32efed3247d165302a1fbe8d9203e38974.
    
    Test: treehugger
    Change-Id: Ib103d211315e320df89a6f0bcb30cd8ba67dd603
    
  - [MemInit] Remove old API, introduce new MemInit API.
    
    Introduces new heap-zero-init API. We've realised that it's better to be
    able to individually control MTE and heap zero-init. Having
    heap-zero-init not be controllable without affecting MTE affects our
    ability to turn off heap-zero-init in zygote-forked applications.
    
    Bug: 135772972
    Test: On FVP: atest -s localhost:5555 malloc#zero_init \
    Test: malloc#disable_mte heap_tagging_level
    Change-Id: I8c6722502733259934c699f4f1269eaf1641a09f
    

* Update development from branch 'ndk-release-r23'
  to ac20f36456315f66c25a85611ce079ca985dfbcf
  - Merge "Snap for 7120539 from 9924173829fc35ef9fc1c6b9c36707a782efc610 to ndk-release-r23" into ndk-release-r23
  - Snap for 7120539 from 9924173829fc35ef9fc1c6b9c36707a782efc610 to ndk-release-r23
    
    Change-Id: I3ffb0e83916f594b37c290b601a0d4efea9f200e
    
  - Merge "Rename `qemu.keyboard_layout` to `vendor.qemu.keyboard_layout`"
  - Merge changes from topics "snapshot_androidmk_suffix", "snapshot_list_module"
    
    * changes:
      Add support to androidmk_suffix prop
      Generate snapshot list modules
    
  - Add support to androidmk_suffix prop
    
    Bug: 177098205
    Test: run script after manually editing json
    Change-Id: I872234a15bf4e15d2fa980d48047091ed03f64dd
    
  - Generate snapshot list modules
    
    This will additionally generate {image}_snapshot module which contains
    a list of vndk and snapshot libraries. This information will be used by
    Soong to override source modules, and will look like:
    
        vendor_snapshot {
            name: "vendor_snapshot",
            version: "30",
            arch: {
                arm: {
                    vndk_libs: ["libvndk", ...],
                    shared_libs: ["libc++", ...],
                    static_libs: ["libc++_static", ...],
                    header_libs: ["libbase_headers", ...],
                    binaries: ["sh.vendor", ...],
                    objects: ["crtbegin_so", ...],
                },
                arm64: {
                    ...
                },
                ...
            },
        }
    
    As shared/static/header/binary/object snapshots may differ among
    archtecture, they will be placed under arch properties.
    
    Bug: 177098205
    Test: run script and see results
    Change-Id: I774f4a6394c0a8552be6822a9592c6511a849160
    
  - Merge "Extend the update.py script to determine usage."
  - Extend the update.py script to determine usage.
    
    After you run a build that uses the full (or any) vendor
    snapshot, you can use ninja to determine which files in
    the vendor snapshot contribute to a given goal, which is
    generally a subset of the content of a full vendor
    snapshot. This information can be fed back to the
    snapshot generation process to tailor the snapshot
    generation towards its expected usage.
    
    Bug: 157967325
    Test: manual test
    Change-Id: I0c886d130633e2ba84e9d89ae60c1faaaf9be1c4
    (cherry picked from commit 57ef5d0c6a4e8e50ee9248234da69ab810a21886)
    
  - Rename `qemu.keyboard_layout` to `vendor.qemu.keyboard_layout`
    
    Bug: 178143857
    
    Signed-off-by: Weilun Du <wdu@google.com>
    Change-Id: I27170464b9a8301ca56bd333a3e5304b8290008e
    

* Update ndk from branch 'ndk-release-r23'
  to ea4a7c54f80f780cd4a19e43d7787c81634faa1e
  - Merge "Snap for 7120539 from 859ba19aba0f040a177d3c200f3c14d4f225a293 to ndk-release-r23" into ndk-release-r23
  - Snap for 7120539 from 859ba19aba0f040a177d3c200f3c14d4f225a293 to ndk-release-r23
    
    Change-Id: Id099d5c792c86bff31cc3067ba5c8575c339a6ca
    
  - Merge changes I283399c1,Ia2a8656c,I71583079
    
    * changes:
      Put the VVL makefile back to emit warning.
      Simplify Vulkan module.
      Add a warning for bad static executable config.
    
  - Merge "Remove build system code for removed linkers."
  - Put the VVL makefile back to emit warning.
    
    Emit a warning pointing to the new location rather than breaking
    existing projects with no message.
    
    Test: imported in ndk-build project, saw warning
    Bug: https://github.com/android/ndk/issues/1374
    Change-Id: I283399c1f3009e4273c869cb5070eb0327078eb9
    
  - Simplify Vulkan module.
    
    Most of this isn't needed any more, and we don't need the intermediate
    zip step between "build" and install any more.
    
    Test: diff $OUT/sources/third_party/vulkan before and after, no change
    Bug: None
    Change-Id: Ia2a8656c6e33f306f1b386d6561f55ab92d0ef47
    
  - Add a warning for bad static executable config.
    
    Test: manual
    Bug: https://github.com/android/ndk/issues/1390
    Change-Id: I715830791470d6a2d3f7ce4dfe60a4fe3d61fdf3
    
  - Remove build system code for removed linkers.
    
    Test: treehugger
    Bug: None
    Change-Id: I977bbefe0cc0642899d5a5973baff8f93c68d193
    
  - Merge "Revert "Update LLVM to clang-r407598b.""
  - Revert "Update LLVM to clang-r407598b."
    
    This reverts commit 6f956eb35a7b8e12f4723f456832f1e6365d1d6e.
    
    Reason for revert: Broke windows
    
    Change-Id: Idb613d224d53cdf3ea43f7899204fdae6d281163
    
  - Merge "Update LLVM to clang-r407598b."
  - Merge "Build with _GNU_SOURCE (the .c files this time)."
  - Build with _GNU_SOURCE (the .c files this time).
    
    To avoid:
    
      ndk/bionic/libm/upstream-freebsd/lib/msun/src/k_exp.c:108:2:
        error: implicit declaration of function 'sincos' is invalid in C99
            sincos(y, &s, &c);
            ^
      1 error generated.
    
    The previous patch only addressed the C++ source...
    
    Test: treehugger
    Change-Id: If8912870f1249641aa264d5abd5c669de8deb6a1
    
  - Update LLVM to clang-r407598b.
    
    Test: ./checkbuild.py && ./run_tests.py
    Bug: https://github.com/android/ndk/issues/1047
    Bug: https://github.com/android/ndk/issues/1096
    Change-Id: If3c0f52602e79d8c58107cfe3282687dd0e3c1ab
    

* Update prebuilts/clang/host/linux-x86 from branch 'ndk-release-r23'
  to febb127b5f26a84257ed2731a163a05e58759e8f
  - Snap for 7120539 from 927fa208019f4feee8df0e28bd690cdad8dc7cbe to ndk-release-r23
    
    Change-Id: Idae59b29f54a3a86ccadcfb1f09541d7b4c054bc
    
  - Update profdata for r412851 using profiles from build 7119913
    
    Bug: 179065588
    Test: Presubmit
    Change-Id: I341aa38fd045618d82d50d441ac4de74e3ca49e0
    
  - Add exported variants of arm32/x86 builtins
    
    For backwards compatibility (e.g. with old apps), arm32 libc.so and
    libm.so export some of the builtins. On 32-bit x86, libc.so also
    exports some of the builtins.
    
    The non-exported variant of the builtins will eventually have hidden
    symbols but doesn't currently because D93431 hasn't been merged into
    our toolchain yet. See:
     - https://reviews.llvm.org/D93431
     - I44ec79728db92c089e2f39823c35b6f97d24c1ab in toolchain/llvm_android
    
    Also apply the "visibility" attribute to libunwind-exported.a.
    
    Bug: http://b/153025717
    Test: bionic unit tests
    Change-Id: I64123a0fdc1b407c26e4097564f540a6102177af
    

* Update prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8 from branch 'ndk-release-r23'
  to 6596d098a4fc65e29724c14d31ea7eb3b15b9d67
  - Snap for 7120539 from 9562d293163d2b0b86bc06c7d73af72a055c695e to ndk-release-r23
    
    Change-Id: I7863d3086e11bccd9635e8ba8549671181c57115
    
  - Fix license_type. Contains GFDL
    
    See: http://go/android-license-checking-v2-lsc
    
    Test: m all
    
    Bug: 151953481
    Bug: 151177513
    Bug: 67772237
    
    Exempt-From-Owner-Approval: janitorial work
    Change-Id: I478965c50e4d3e18445eb443ca8d6ff002d4a8ce
    

* Update prebuilts/ndk from branch 'ndk-release-r23'
  to a72ae2440a4ab0e73974f95d7e7e64d967e77caf
  - Merge "Snap for 7120539 from d0afc08703495fb29c617f3c7051d41fc9b2df0f to ndk-release-r23" into ndk-release-r23
  - Snap for 7120539 from d0afc08703495fb29c617f3c7051d41fc9b2df0f to ndk-release-r23
    
    Change-Id: I24f9124b304290fe3c9a4ea5527d10699d63b748
    
  - Merge "Update NDK platform prebuilts to build 7116906." into dev
  - Update NDK platform prebuilts to build 7116906.
    
    Test: ndk/checkbuild.py && ndk/run_tests.py
    Bug: None
    Change-Id: I4f082c4d0928e2284b06e6f8cf04b13a2d4c19f4
    
  - Merge "Update NDK platform prebuilts to build 7022439." into dev
  - Update NDK platform prebuilts to build 7022439.
    
    Test: ndk/checkbuild.py && ndk/run_tests.py
    Bug: None
    Change-Id: I104d7b022a4fd3f98e2ad976f58e4f337da98e8a
    

* Update toolchain/llvm-project from branch 'ndk-release-r23'
  to fec5daf2fff532f3abf1eedb43dc41c9a78eb921
  - Snap for 7120539 from b87cca39ef147de502ac4ae48aac333ca003082b to ndk-release-r23
    
    Change-Id: I5102a13c7df8d439a8dd354d4c23b6c1d362a103
    
  - Revert "[aarch64] Compile libcxx with PAuth and BTI"
    
    This reverts commit 47d06bd628e3d96aa248ef02e5f6384b7d9f63e3.
    
    Reason for revert: Broke a bunch of libc++ tests
    
    Change-Id: I131833a7312a74f4e355ab3c6d5b6aff6c51b0cc