Autoupdate of 2 submodules
*art updated to 4dc6589f392d46800a3b64625245bdfe4bbbfc2f
Don't wrap VerifyError into NoClassDefFoundError.

Follow RI behavior by returning the VerifyError. NoClassDefFoundError
only wraps initializer errors.

Also rename the field in ClassExt from verifyError to
erroneousStateError for better clarity.

And remove now unused feature of storing a class in the verifyError
field.

Test: test.py
Test: 824-verification-rethrow
Bug: 28313047
Change-Id: I19383f7b74f22a62ab1e0b8a13bea75a14c7b33f

*libcore updated to d00257e41751083f2cb865e4a58e0b172a398490
Merge "Rename verifyError field to erroneousStateError."