Update git submodules
* Update frameworks/support from branch 'androidx-master-dev'
  to 694cc0f53bb8cc3f6bfa7f36f11dc02f913459c8
  - Merge "Fixes failing DemoTest" into androidx-master-dev
  - Fixes failing DemoTest
    
    Because RtlDemo was placing children twice, it was crashing on start with this exception:
    
    java.lang.IllegalStateException: Place was called on a node which was placed already
    
    Also removes obsolete dependencies, and kotlin_module exclusions since the samples were renamed to be unique anyway.
    
    Bug: b/169651052
    Test: DemoTest
    Change-Id: Iedafcd18b2ecb7bffa7ad64b5430579a024ab8bc