Update git submodules
* Update external/python/pybind11 from branch 'master'
  to 7c3ac77d79750b1ce2d6d42838fb7a4d84734c6a
  - Upgrade python/pybind11 to v2.5.0
    
    Test: None
    Change-Id: I92652abb3aec620baffe9d5dbc7fbe18d130d8b1
    
  - v2.5.0 release
    
  - pybind11Tools.cmake: search for Python 3.9
    
  - Fix the use of MSVC in an MSYS environment (#2087)
    
    
  - stl_bind: add binding for std::vector::clear (#2074)
    
    
  - Fix compilation with MinGW only (#2053)
    
    
  - Declare call_impl() as && (#2057)
    
    
  - Handle cases where binding code immediately throws py::error_already_set
    
    When binding code immediately throws an exception of type
    py::error_already_set (e.g. via py::module::import that fails), the
    catch block sets an import error as expected. Unfortunately, following
    this, the deconstructor of py::error_already_set decides to call
    py::detail::get_internals() and set up various internal data structures
    of pybind11, which fails given that the error flag is active. The call
    stack of this looks as follows:
    
    Py_init_mymodule() -> __cxa_decrement_exception_refcount ->
    error_already_set::~error_already_set() ->
    gil_scoped_acquire::gil_scoped_acquire() -> detail::get_internals() ->
    ... -> pybind11::detail::simple_collector() -> uh oh..
    
    The solution is simple: we call detail::get_internals() once before
    running any binding code to make sure that the internal data structures
    are ready.
    
  - bindings for import_error exception
    
  - Travis CI fix (MacOS, Py3)
    
  - Use C++17 fold expressions when casting tuples and argument lists (#2043)
    
    This commit introduces the use of C++17-style fold expressions when
    casting tuples & the argument lists of functions.
    
    This change can improve performance of the resulting bindings: because
    fold expressions have short-circuiting semantics, pybind11 e.g. won't
    try to cast the second argument of a function if the first one failed.
    This is particularly effective when working with functions that have
    many overloads with long argument lists.
  - Add C++20 char8_t/u8string support (#2026)
    
    * Fix test build in C++20
    
    * Add C++20 char8_t/u8string support
    
  - Fixes #1295: Handle debug interpreter (#2025)
    
    If a debug interpreter is detected, we allow linking with
    pythonXX_d.lib under windows.
  - undo #define copysign in pyconfig.h
    
  - Free tstate on python 3.7+ on finalize_interpreter (#2020)
    
    
  - Revert "Fix a memory leak when creating Python3 modules. (#2019)"
    
    This reverts commit 819802da9926535714acf2bffe690b04f90cb12b.
    
  - Fix a memory leak when creating Python3 modules. (#2019)
    
    
  - Use newer macOS image for python3 testing
    
  - Pin breathe to 4.13.1
    
  - Install headers using both headers and package_data (#1995)
    
    
  - Revert "numpy.h: minor preprocessor fix suggested by @chaekwan"
    
    This reverts commit 61e4f1182357cc0f55b567b128011c579e4c7ccd.
    
  - numpy.h: minor preprocessor fix suggested by @chaekwan
    
  - Minor modifications to interrupt handling FAQ (#2007)
    
    
  - Add FAQ entry for dealing with long functions interruption (#2000)
    
    * Add FAQ entry, with code example, for dealing with long functions interruption
  - support for readonly buffers (#863) (#1466)
    
    
  - Aligned allocation fix for clang-cl (#1988)
    
    
  - Add exception translation for std::overflow_error. (#1977)
    
    
  - Fixing SystemError when nb_bool/nb_nonzero sets a Python exception in type_caster<bool>::load (#1976)
    
  - Fixing minor typo in basics.rst (#1984)
    
    
  - Prevent cmake error when prefix empty (#1986)
    
    
  - CMake: Add Python 3.8 to pybind11Tools (#1974)
    
    Add Python 3.8 to considered versions in CMake for additional
    hints.
    https://cmake.org/cmake/help/v3.2/module/FindPythonLibs.html
  - test pair-copyability on C++17 upwards (#1886)
    
    * test pair-copyability on C++17 upwards
    
    The stdlib falsely detects containers like M=std::map<T, U>
    as copyable, even when one of T and U is not copyable.
    Therefore we cannot rely on the stdlib dismissing std::pair<T, M>
    by itself, even on C++17.
    
    * fix is_copy_assignable
    
    bind_map used std::is_copy_assignable which suffers from the same problems
    as std::is_copy_constructible, therefore the same fix has been applied.
    
    * created tests for copyability
    
  - Report type names in return value policy-related cast exceptions (#1965)
    
    
    
  - make builds with python tests and cpp tests fail if either one fails (#1967)
    
    
  - Obey __cpp_sized_deallocation and __cpp_aligned_new
    
    Don't assume that just because the language version is C++17 that the
    standard library offers all C++17 features, too.  When using clang-6.0
    and --std=c++17 on Ubuntu 18.04 with libstdc++, __cpp_sized_deallocation
    is false.
    
  - misleading comment corrected (strides in buffer_info is bytes and not number of entries) (#1958)
    
    
  - Fix build with -Wmissing-prototypes (#1954)
    
    When building with `-Werror,-Wmissing-prototypes`, `clang` complains about missing prototypes for functions defined through macro expansions. This PR adds the missing prototypes.
    
    ```
    error: no previous prototype for function 'pybind11_init_impl_embedded' [
    -Werror,-Wmissing-prototypes]                                           
    PYBIND11_EMBEDDED_MODULE(embedded, mod) {                                             
    ^                                                                           
    external/pybind11/include/pybind11/embed.h:61:5: note: expanded from macro 'PYBIND11_EMBEDDED_MODULE'
        PYBIND11_EMBEDDED_MODULE_IMPL(name)                                       \
        ^                                                                         
    external/pybind11/include/pybind11/embed.h:26:23: note: expanded from macro 'PYBIND11_EMBEDDED_MODULE_IMPL'
          extern "C" void pybind11_init_impl_##name() {      \                  
                          ^                                             
    <scratch space>:380:1: note: expanded from here                     
    pybind11_init_impl_embedded                                                                                                                      
    ^                                                                                                                                                
    1 error generated.
    ```
  - begin working on next version