Update git submodules
* Update external/perfetto from branch 'master'
  to 579835790596c7536e89226d825e9849db6e27af
  - Merge "Use exec(curl) for downloading artifacts"
  - Use exec(curl) for downloading artifacts
    
    Due to the union of an openssl bug, python inconsistencies
    and Google Cloud changing CA, there doesn't seem to be a way
    to consistently download an artifact over https in pure python
    that works both on Linux and Mac (At least for Google HW).
    
    On Mac:
      python3 -c 'import urllib.request;  urllib.request.urlopen("https://storage.googleapis.com/")'
      Fails with CERTIFICATE_VERIFY_FAILED because python3 on mac
      bundles its own set of CA roots which seems
      now obsolete (https://bugs.python.org/msg276516)
    
      However
    
      python2 -c 'from urllib import urlretrieve; urlretrieve("https://storage.googleapis.com/")'
      works
    
    On Linux:
      python3 -c 'import urllib.request;  urllib.request.urlopen("https://storage.googleapis.com/")'
      Works
    
      However
    
      python2 -c 'from urllib import urlretrieve; urlretrieve("https://storage.googleapis.com/")'
      Fails with
      ssl.SSLError: [SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1946)
      Because of a bung introduced by OpenSSL 1.1.1e (https://bugs.python.org/issue40018)
    
    Other option (like requests) are not viable because require the user to perform
    some manual actions (pip install...) which is a bad UX
    The world failed us. exec(curl) to the rescue.
    
    Bug: many
    Test: manually tested both install-build-deps and heap_profile on mac
    Change-Id: I064c539fd15f7cac87bd0050631c6e008acaff77