Update git submodules
* Update external/googletest from branch 'master'
  to da5c5afa6ee2e79b9060290abbe763210b610e8c
  - Upgrade googletest to 011959aafddcd30611003de96cfd8d7a7685c700
    
    Test: None
    Change-Id: If8abc786d1f7a868efa9ee69bcf05be3ed4aa7be
    
  - Googletest export
    
    Remove broken URL.
    
    PiperOrigin-RevId: 311377660
    
  - Googletest export
    
    Fixed #2823 - Make it so that a semicolon appearing after an invocation of GTEST_SUPPRESS_UNREACHABLE_CODE_WARNING_BELOW_ does not trigger a redundant semicolon warning.
    
    This works by introducing an else block with a statement that intentionally does not end with a semicolon, forcing users to place the semicolon after the expansion. The approach here is preferred as opposed to removing semicolons that appear after each invocation because complete statements that do not have a visible semicolon or braces confuse users and code formatters, since the macro invocation looks superficially like an expression.
    
    PiperOrigin-RevId: 311327491
    
  - Merge pull request #2778 from lvjp:issue-2777
    
    PiperOrigin-RevId: 310911989
    
  - Merge pull request #2844 from mstorsjo:windows-includes
    
    PiperOrigin-RevId: 310910168
    
  - Googletest export
    
    Addresses https://github.com/google/googletest/pull/2784
    
    PiperOrigin-RevId: 310902202
    
  - Remove an explicit include of debugapi.h
    
    The documentation for IsDebuggerPresent says that one just should
    include windows.h, as that one is an umbrella header that includes
    the header that declares IsDebuggerPresent. In older Windows SDKs,
    debugapi.h didn't exist and IsDebuggerPresent was declared in
    winbase.h (also included by windows.h).
    
    This should fix issue #2822 properly.
    
  - Revert "Googletest export"
    
    This reverts commit a9f6c1ed1401dd9b002d4c43fb9f946d2c7466d0.
    
    That commit cannot fix the issue it sets out to fix.
    
    The original issue, #2822, was that building with a toolset
    targeting XP compatibility is missing the debugapi.h header -
    as debugapi.h didn't exist in older Windows SDKs.
    
    Commit a9f6c1ed1401dd9b002d4c43fb9f946d2c7466d0 misinterpreted
    the Microsoft documentation about IsDebuggerPresent. The information
    about which header to use, "debugapi.h (include Windows.h)" means
    that the function declaration currently lives in debugapi.h, but
    for compatibility, just include the Windows.h umbrella header.
    In older Windows SDKs (e.g. the v6.0a SDK), IsDebuggerPresent
    is declared in winbase.h, and debugapi.h doesn't exist at all in those
    versions.
    
    Including Windows.h with a different capitalization than the existing
    include won't help finding headers that don't exist.
    
    Including Windows.h with a capital W breaks cross compilation with mingw
    toolchains, where the header always has been spelled with a lower case
    W. When building on native windows, the file system is case insensitive
    and the capitalization doesn't matter.
    
    This fixes issue #2840.
    
  - Googletest export
    
    Fix `-Wgnu-zero-variadic-macro-arguments` in GMock
    
    Passing zero arguments to the variadic part of a macro is a GNU
    extension and triggers warnings when build projects using GMock with
    `-pedantic`.
    
     - Fix uses of `GMOCK_PP_INTERNAL_16TH` to always receive at least 17
    arguments. (this was triggered when `GMOCK_PP_NARG` or `GMOCK_PP_HAS_COMMA`
    were used with an argument containing no commas).
     - Fix `GMOCK_PP_HEAD` to append a dummy unused argument so that
    `GMOCK_PP_INTERNAL_HEAD` always has two arguments.
    
    PiperOrigin-RevId: 310414611
    
  - Merge pull request #2751 from calumr:quiet-flag
    
    PiperOrigin-RevId: 309958629
    
  - Merge pull request #2830 from keshavgbpecdelhi:patch-1
    
    PiperOrigin-RevId: 309951872
    
  - Googletest export
    
    Addresses Github issue (https://github.com/google/googletest/issues/2822) by following the Microsoft documention (https://docs.microsoft.com/en-us/windows/win32/api/debugapi/nf-debugapi-isdebuggerpresent) to include capital-W Windows.h before including debugapi.h.
    
    See "Header	debugapi.h (include Windows.h)"
    
    PiperOrigin-RevId: 309745868
    
  - Googletest export
    
    Fix documentation. This address https://github.com/google/googletest/pull/2827.
    
    PiperOrigin-RevId: 309241571
    
  - Googletest export
    
    Fix link to "high-perf dependency injection technique".
    
    PiperOrigin-RevId: 308893893
    
  - Merge pull request #2818 from inazarenko:master
    
    PiperOrigin-RevId: 308711492
    
  - Merge pull request #2818 from inazarenko:master
    
    PiperOrigin-RevId: 308650221
    
  - Googletest export
    
    internal change
    
    PiperOrigin-RevId: 308648034
    
  - Merge pull request #2815 from Quuxplusone:simple
    
    PiperOrigin-RevId: 308625388
    
  - Googletest export
    
    Rewrite ReturnNew action without using pump.
    
    PiperOrigin-RevId: 308219616
    
  - Googletest export
    
    Use InitGoogleTest() instead of InitGoogle() in code example
    
    PiperOrigin-RevId: 308070819
    
  - Merge pull request #2797 from Jyun-Neng:master
    
    PiperOrigin-RevId: 307604377
    
  - Googletest export
    
    Explicitly define copy constructors used in googletest tests
    
    As of C++11, providing a user-declared copy assignment operator should
    suppress the availability of an implicit default copy constructor.
    Classes that provide (or delete) a copy assignment operator must provide
    their own copy constructor if one is desired. This may be an explicit
    default copy constructor if appropriate.
    
    As googletest is a C++11 codebase, this change should be made without
    qualification.
    
    This addresses the -Wdeprecated-copy warnings issued by trunk clang:
    
    While compiling googletest/test/googletest-death-test-test.cc:
    
    In file included from .../googletest/test/googletest-death-test-test.cc:33:
    .../googletest/include/gtest/gtest-death-test.h:196:8: error: definition of implicit copy constructor for 'ExitedWithCode' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
      void operator=(const ExitedWithCode& other);
           ^
    .../googletest/test/googletest-death-test-test.cc:279:16: note: in implicit copy constructor for 'testing::ExitedWithCode' first required here
      EXPECT_PRED1(pred0,  status0);
                   ^
    
    While compiling googletest/test/googletest-param-test-test.cc:
    
    .../googletest/test/googletest-param-test-test.cc:502:8: error: definition of implicit copy constructor for 'NonDefaultConstructAssignString' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
      void operator=(const NonDefaultConstructAssignString&);
           ^
    .../googletest/test/googletest-param-test-test.cc:507:36: note: in implicit copy constructor for 'NonDefaultConstructAssignString' first required here
          Combine(Values(0, 1), Values(NonDefaultConstructAssignString("A"),
    
    This matches other changes made elsewhere in the googletest codebase,
    such as 306f3754a71d. Perhaps those previous changes did not consider
    test code.
    
    PiperOrigin-RevId: 307495126
    
  - Googletest export
    
    Fix comment that describes how to test against nullopt.
    
    PiperOrigin-RevId: 307448375
    
  - Googletest export
    
    Internal change
    
    PiperOrigin-RevId: 307040308
    
  - Removed a typo in README.md 
    
    There is an unnecessary comma before 'and'
  - Add -Wdeprecated to the build configuration.
    
  - Fix a -Wdeprecated warning.
    
        googletest-param-test-test.cc:502:8: error:
        definition of implicit copy constructor for
        'NonDefaultConstructAssignString' is deprecated because it has a
        user-declared copy assignment operator [-Werror,-Wdeprecated]
            void operator=(const NonDefaultConstructAssignString&);
                 ^
    
  - Fix a -Wdeprecated warning.
    
        googletest-port-test.cc:97:11: error:
        definition of implicit copy constructor for 'Base' is deprecated because
        it has a user-declared destructor [-Werror,-Wdeprecated]
            virtual ~Base() {}
                    ^
    
  - Fix a -Wdeprecated warning.
    
        gmock-spec-builders.h:503:3: error:
        definition of implicit copy constructor for 'Expectation' is deprecated
        because it has a user-declared destructor [-Werror,-Wdeprecated]
            ~Expectation();
            ^
    
  - Remove all uses of GTEST_DISALLOW_{MOVE_,}ASSIGN_.
    
    None of these are strictly needed for correctness.
    A large number of them (maybe all of them?) trigger `-Wdeprecated`
    warnings on Clang trunk as soon as you try to use the implicitly
    defaulted (but deprecated) copy constructor of a class that has
    deleted its copy assignment operator.
    
    By declaring a deleted copy assignment operator, the old code
    also caused the move constructor and move assignment operator
    to be non-declared. This means that the old code never got move
    semantics -- "move-construction" would simply call the defaulted
    (but deprecated) copy constructor instead. With the new code,
    "move-construction" calls the defaulted move constructor, which
    I believe is what we want to happen. So this is a runtime
    performance optimization.
    
    Unfortunately we can't yet physically remove the definitions
    of these macros from gtest-port.h, because they are being used
    by other code internally at Google (according to zhangxy988).
    But no new uses should be added going forward.
    
  - Enable protobuf printing for open-source proto messages.
    
  - VariadicMatcher needs a non-defaulted move constructor for compile-time performance.
    
    We are about to remove all uses of GTEST_DISALLOW_ASSIGN_ in favor
    of using the Rule of Zero everywhere.
    
    Unfortunately, if we use the Rule of Zero here, then when the compiler
    needs to figure out if VariadicMatcher is move-constructible, it will
    recurse down into `tuple<Args...>`, which on libstdc++ recurses too deeply.
    
        In file included from googlemock/test/gmock-matchers_test.cc:43:
        In file included from googlemock/include/gmock/gmock-matchers.h:258:
        In file included from /usr/include/c++/5.5.0/algorithm:60:
        In file included from /usr/include/c++/5.5.0/utility:70:
        In file included from /usr/include/c++/5.5.0/bits/stl_pair.h:59:
        In file included from /usr/include/c++/5.5.0/bits/move.h:57:
        /usr/bin/include/c++/5.5.0/type_traits:115:26: fatal error:
              recursive template instantiation exceeded maximum depth of 256
            : public conditional<_B1::value, _B1, _B2>::type
                                 ^
    
    The move constructor is the only problematic case, for some unknown reason.
    With GTEST_DISALLOW_ASSIGN_, the presence of a copy assignment operator
    causes the move constructor to be non-declared, thus non-defaulted, thus
    non-problematic. Without GTEST_DISALLOW_ASSIGN_, we have to do one of the
    following:
    
    - Default the copy constructor, so that the move constructor will be non-declared.
    
    - Define our own non-defaulted move constructor.
    
    ...except that doing the latter STILL did not work!
    Fortunately, the former (default the copy constructor, don't provide
    any move constructor) both works in practice and is semantically
    equivalent to the old code.
    
  - Merge pull request #2805 from pepsiman:patch-1
    
    PiperOrigin-RevId: 306462650
    
  - Merge pull request #2802 from e-i-n-s:fix_clang_warning
    
    PiperOrigin-RevId: 306460942
    
  - Merge pull request #2810 from ptahmose:master
    
    PiperOrigin-RevId: 306460738
    
  - Googletest export
    
    Fix link to "After clause". Sorry, reader, but this heading is in another document!
    
    PiperOrigin-RevId: 305947971
    
  - Merge pull request #2756 from Conan-Kudo:fix-pkgconfig-reqs
    
    PiperOrigin-RevId: 305747437
    
  - Merge pull request #2772 from Quuxplusone:travis
    
    PiperOrigin-RevId: 305747317
    
  - Merge pull request #2773 from Quuxplusone:replace-noexcept
    
    PiperOrigin-RevId: 305707266
    
  - fix signed/unsigned comparison issue (on OpenBSD)
    
  - Remove redundant .c_str()
  - gtest-unittest-api_test - fix warning in clang build
    
  - Remove duplicate codes existed in get-nprocessors.sh
    
  - Fix --gtest_print_time coloring
    
  - Replace the last instance of `throw()` with `noexcept`. NFC.
    
    Fixes a -Wdeprecated warning.
    
    /home/travis/build/Quuxplusone/googletest/googletest/test/googletest-death-test_ex_test.cc:62:28: error:
          dynamic exception specifications are deprecated [-Werror,-Wdeprecated]
      const char* what() const throw() override { return "exceptional message"; }
                               ^~~~~~~
    /home/travis/build/Quuxplusone/googletest/googletest/test/googletest-death-test_ex_test.cc:62:28: note:
          use 'noexcept' instead
      const char* what() const throw() override { return "exceptional message"; }
                               ^~~~~~~
                               noexcept
    
  - Fix a typo in .travis.yml
    
    The old code was trying to pass -Wgnu-zero-variadic-macro-arguments
    as part of CXXFLAGS, but it forgot the quotation marks needed around
    whitespace. This meant that option was ignored:
    https://travis-ci.org/github/google/googletest/jobs/666534177#L760
    
    Unfortunately, the codebase is not remotely clean with respect to that
    warning option. It fails like this:
    https://travis-ci.org/github/Quuxplusone/googletest/jobs/668118135
    
    So, remove that failing configuration from the test matrix until
    someone has time to look at it.
    
  - Merge branch 'master' into quiet-flag
  - Ensure that gtest/gmock pkgconfig requirements specify version
    
    Google Test and Google Mock require matching versions to work,
    so this requirement should be described in the pkgconfig files.
    
    This change is derived from the one used for the Fedora gtest package.
    
    Signed-off-by: Neal Gompa <ngompa13@gmail.com>
    
  - Add GTEST_BRIEF option
    
    Only prints failures and a total pass count