Update git submodules
* Update device/google/cuttlefish from branch 'android10-gsi'
  to fcd49985faf82cbb774fed72aee3ba110fe2fe5a
  - Merge changes I5f6f5990,Ia873ffe8,I830c6f70,I7c6bc972,I493be158, ... into android10-gsi
    
    * changes:
      Delete host_region_e2e_test from the host package
      Delete references to socket_forward_proxy
      Expand access to aware_available
      Remove references to stream_audio.
      Remove build dependencies on libcuttlefish_strings
      Delete socket_forward_proxy
      Remove uses of cvd::StrSplit.
      cuttlefish: EmulatedFakeCamera2: fix -Wimplicit-int-float-conversion
      Copy android.software.activities_on_secondary_displays.xml to CuttleFish Auto build target.
      Replace AutoFreeBuffer uses for SharedFD
      AutoFreeBuffer -> std::vector<char> for netlink
      Delete AutoCloseFileDescriptor. It is dead code.
      Delete AutoCloseFILE. It is dead code.
      Delete AutoUMask. It is dead code.
      Fix typo: psuedo -> pseudo
      Disable scanning the filesystem for cuttlefish-related files
      Remove the vsoc host binaries and libraries
      Delete the record_audio host binary
      Remove header dependencies on vsoc_lib
      Delete vsoc support libraries and tests
      Delete the stream_audio host binary
      Delete the record_audio host binary
      Break build dependencies on vsoc_lib
      Delete the legacy audio hal
      Delete vsoc, vsoc-future hwcomposers
      Delete guest/hals/gralloc but not /legacy
      Delete ivserver
      Delete ivserver
      Remove {assemble,launch,run}_cvd ivserver references
      Delete socket_forward_proxy
      Remove guest-side references to vsoc / qemu
      Fix starting vsoc_input_service
      Only get ".img" files from ANDROID_PRODUCT_OUT
    
  - Delete host_region_e2e_test from the host package
    
    This binary doesn't exist anymore.
    
    Test: make installclean && make -j
    Bug: 144973127
    Change-Id: I5f6f59902ed1a7269aa403c097845dfab755dc12
    
  - Delete references to socket_forward_proxy
    
    This only works in qemu/vsoc.
    
    Test: Run with launch_cvd -vm_manager=qemu_cli
    Bug: 144111429
    Change-Id: Ia873ffe8b96c5ecd926bfa9c4f25de229eb5edbd
    
  - Expand access to aware_available
    
    aware_available property is used by com.android.systemui (platform_app) and
    com.google.android.apps.tips (priv_app).
    
    Bug: 131857101
    Bug: 144425817
    Change-Id: I830c6f70702657cfa3f4c88b6766b420447a3323
    
  - Remove references to stream_audio.
    
    This binary only worked with qemu/vsoc.
    
    Bug: 144111429
    Test: Run launch_cvd -vm_manager=qemu_cli
    Change-Id: I7c6bc9727be7834db47dc98a0d91831b6e9b089b
    
  - Remove build dependencies on libcuttlefish_strings
    
    Bug: 144455581
    Test: Build and run locally
    Change-Id: I493be15857458d668e3c0b7142cebfda94311783
    
  - Delete socket_forward_proxy
    
    This only works with the vsoc driver.
    
    Bug: 144111429
    Test: Run with -vm_manager=qemu_cli
    Change-Id: Ib67a3eb7d32426e16ae2ab337fd652ef039dc9b3
    
  - Remove uses of cvd::StrSplit.
    
    This function is redundant with android::base::Split.
    
    Bug: 144455581
    Test: Build and run
    Change-Id: I4e306d8051cfae1fd892fdd166d8841c2f8ba17b
    
  - cuttlefish: EmulatedFakeCamera2: fix -Wimplicit-int-float-conversion
    
    IEEE754 single precision cannot precisely represent RAND_MAX.
    
    error: implicit conversion from 'int' to 'float' changes value from
    2147483647 to 2147483648 [-Werror,-Wimplicit-int-float-conversion]
    
    For purposes of generating random uniforms, this does not matter. Add
    explicit casts of RAND_MAX to float to fix.
    
    Bug: 139945549
    Test: lunch aosp_cf_x86_phone-userdebug && mm
    Change-Id: I72fe9a4f0fa76a0df1552fffb16a793205272d78
    Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
    
  - Copy android.software.activities_on_secondary_displays.xml to CuttleFish Auto build target.
    
    The permission is need to launch an Activity in ActivityView.
    
    Test: checks if Maps is launched in ActivityView of CarLauncher.
    Change-Id: Ibd8597d6a863a96423c757baee0454042a17d5ce
    
  - Replace AutoFreeBuffer uses for SharedFD
    
    Uses a combination of std::stringstream, std::string, and
    std::vector<char>.
    
    Bug: 144387776
    Test: Build and run locally
    Change-Id: I61f696c729b5895e922429cec550054196a01199
    
  - AutoFreeBuffer -> std::vector<char> for netlink
    
    Test: atest cuttlefish_net_tests
    Bug: 144387776
    Change-Id: I7263e59910a785ec2115c03b1f6e36e659df6b0d
    
  - Delete AutoCloseFileDescriptor. It is dead code.
    
    Bug: 144387776
    Test: TreeHugger
    Change-Id: I6e9acf55cc9b71016bf4c22ce3635783d54a19aa
    
  - Delete AutoCloseFILE. It is dead code.
    
    Bug: 144387776
    Test: TreeHugger
    Change-Id: I53ebee8d6eec4222da24e021183ee340960eff6f
    
  - Delete AutoUMask. It is dead code.
    
    Test: TreeHugger
    Bug: 144387776
    Change-Id: I3c8f8a36b0641946594ca3af5b627b4a48155a05
    
  - Fix typo: psuedo -> pseudo
    
    Test: TreeHugger
    Change-Id: I45ccf070f69de20152cc181508e136c8ac3d1c5c
    
  - Disable scanning the filesystem for cuttlefish-related files
    
    This is fragile/unstable and is not yet necessary for running the device
    locally. While the file list matters more for instances produced by the
    fetch_cvd downloader, that already produces a file list on a separate
    code path.
    
    Test: Build and run launch_cvd
    Bug: 144189763
    Change-Id: I5b4cd2e48c7cf9308dce53ee0aef75e7b7e1dae5
    
  - Remove the vsoc host binaries and libraries
    
    Bug: 144111429
    Test: Run launch_cvd -vm_manager=qemu_cli
    Change-Id: I80cec86e26ed98044a2772e1bef8a210decd3097
    
  - Delete the record_audio host binary
    
    Bug: 144111429
    Test: Run launch_cvd -vm_manager=qemu_cli
    Change-Id: I1c2ebfa95154b1f5205ccea38ba21946b722da10
    
  - Remove header dependencies on vsoc_lib
    
    Bug: 144111429
    Test: Run launch_cvd -vm_manager=qemu_cli
    Change-Id: I7cc03d824c5f74792129351c3dde89dbdabde4d5
    
  - Delete vsoc support libraries and tests
    
    Bug: 144111429
    Test: Run launch_cvd -vm_manager=qemu_cli
    Change-Id: I778b653f185acd09ea372eb1fc76f971836e691c
    
  - Delete the stream_audio host binary
    
    This depended on qemu/vsoc.
    
    Bug: 144111429
    Test: Run launch_cvd -vm_manager=qemu_cli
    Change-Id: I4438da35cb1088a571c7f2781ef7c99cc997cdb3
    
  - Delete the record_audio host binary
    
    This depended on qemu/vsoc.
    
    Bug: 144111429
    Test: Run launch_cvd -vm_manager=qemu_cli
    Change-Id: Ie0dc16708088d8282d7be9b038890bba6619bc3d
    
  - Break build dependencies on vsoc_lib
    
    Bug: 144111429
    Test: Run launch_cvd -vm_manager=qemu_cli
    Change-Id: I4ce52ba487a57df26cf1e1171ac732633865bde3
    
  - Delete the legacy audio hal
    
    This only worked with vsoc/qemu.
    
    Bug: 144111429
    Test: Run launch_cvd -vm_manager=qemu_cli
    Change-Id: I7a521962b8e15d245b482f04203937399b7a6893
    
  - Delete vsoc, vsoc-future hwcomposers
    
    Bug: 144111429
    Test: Run with -vm_manager=qemu_cli
    Change-Id: I439d773259aaec60cc3fa37675736dd118b52d8a
    
  - Delete guest/hals/gralloc but not /legacy
    
    Credit to natsu@ for pointing out that /legacy is still needed.
    
    Bug: 144111429
    Test: Run with -vm_manager=qemu_cli
    Change-Id: Ic5e3b4bd50b65da3f989902476a735604f98148c
    
  - Delete ivserver
    
    Bug: 144111429
    Test: Run with -vm_manager=qemu_cli
    Change-Id: I11efcee5769ee84dcde4706d8a50e01d3ddebf42
    
  - Delete ivserver
    
    Bug: 144111429
    Test: Run with -vm_manager=qemu_cli
    Change-Id: Ie90b0a457521f0700f235355b18fb7f07bc36751
    
  - Remove {assemble,launch,run}_cvd ivserver references
    
    Bug: 144111429
    Test: Run with -vm_manager=qemu_cli
    Change-Id: I8d28a9456854d78cf9ae82f50e686712da72fe6c
    
  - Delete socket_forward_proxy
    
    This only works with the vsoc driver.
    
    Bug: 144111429
    Test: Run with -vm_manager=qemu_cli
    Change-Id: Ida0be8aa1b1411fc5573a91284fac2cf8a269886
    
  - Remove guest-side references to vsoc / qemu
    
    Test: Run launch_cvd -vm_manager=qemu_cli
    Bug: 144111429
    Change-Id: I73c9e1712db44bcb962a0084f145255af0f62fbb
    
  - Fix starting vsoc_input_service
    
    Test: Check input in vnc with -vm_manager=qemu_cli
    Bug: 143713267
    Change-Id: I353643f874ff9b210fc7a9d5ca49782c34d24150
    
  - Only get ".img" files from ANDROID_PRODUCT_OUT
    
    This avoids accidentally seeing a "kernel" file in ANDROID_PRODUCT_OUT
    as being a user-supplied kernel image.
    
    Bug: 144189763
    Test: Build and run locally
    Change-Id: Ie2ff37d9b508bbee8b59ba62e6f503b0eef64b2a