Update git submodules
* Update frameworks/support from branch 'androidx-master-dev'
  to d3687c55bf3e4bba92275fbec4eba344e978339f
  - Merge "build_log_simplifier now removing certain known messages" into androidx-master-dev
  - build_log_simplifier now removing certain known messages
    
      Things that print often but that users aren't likely to act on when they're running on the build server, like:
    
        "Note: Some input files use or override a deprecated API."
    
    Test: Run `echo "syntaxerror" >> core/core/src/main/java/androidx/core/app/AppComponentFactory.java && ./cleanBuild.sh -y bOS --stacktrace -Pandroidx.summarizeStderr`
          and see that its output ends with this:
    
      > Task :navigation:navigation-common:compileDebugRenderscript NO-SOURCE
      > Task ...
      > Task :core:core:compileReleaseJavaWithJavac FAILED
      /usr/local/google/workspace/aosp-androidx-git/frameworks/support/core/core/src/main/java/androidx/core/app/AppComponentFactory.java:211: error: class, interface, or enum expected
    
      syntaxerror
      ^
      1 error
      > Task :paging:paging-runtime-ktx:compileReleaseRenderscript NO-SOURCE
      > Task ...
    
      FAILURE: Build failed with an exception.
    
      * What went wrong:
      Execution failed for task ':core:core:compileReleaseJavaWithJavac'.
      > Compilation failed; see the compiler error output for details.
    
      * Try:
      Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    
      * Exception is:
      org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':core:core:compileReleaseJavaWithJavac'.
      	at org.gradle...
      Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
      	at org.gradle...
      	at jdk.internal.reflect.GeneratedMethodAccessor921.invoke(Unknown Source)
      	at java.base...
      See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
    
      BUILD FAILED in 2m 52s
      917 actionable tasks: 537 executed, 380 from cache
    
    Change-Id: I8efe959c63e1f7c6489b2470c8122efa163bce50