Update git submodules
* Update prebuilts/android-emulator-build/archive from branch 'emu-master-dev'
  to 7dd51314b71eb1fb323cf360684aefaf65bf10be
  - prebuilts: add qt patches to make it cross build for aarch64
    
    BUG: 152456395
    BUG: 146226835
    
    This patch adds the linux-aarch64 device to qtbase/mkspecs/devices;
    TO fully build qt for aarch64 on x86_64 host, need to do the following
    
    1. need to use the toolchain-wrapper with
    the following change in the load script:
    aarch64-linux-gnu-ld
    /usr/bin/aarch64-linux-gnu-g++  "$@"  -lc -lm -ldl
    
    2. need to create sysroot for aarch64 cross compile
    the aarch64 host need to have all the requirements to run
    the configure without any error; plus installing
    xdamage (need during the link)
    run on linux-aarch64 host to check missing deps
    ./configure -opensource -confirm-license -skip qtwayland -skip qtlocation -skip qtscript -force-debug-info -release -no-rpath -shared -nomake examples -nomake tests -skip qtlocation -no-strip -qtlibinfix AndroidEmu -no-use-gold-linker -prefix ${TOP}/install -no-use-gold-linker -feature-library
    
    3. use the following config on linux-x86_64 host
    TOP=/usr/local/google/home/$USER/a/aarch64/qt
    SRC=/usr/local/google/home/$USER/a/aarch64/qt/src/qt-everywhere-src-5.12.1
    ${SRC}/configure -device linux-aarch64 -device-option CROSS_COMPILE=aarch64-linux-gnu- -sysroot ${TOP}/sysroot -opensource -confirm-license -skip qtwayland -skip qtlocation -skip qtscript -force-debug-info -release -no-rpath -shared -nomake examples -nomake tests -skip qtlocation -no-strip -qtlibinfix AndroidEmu -no-use-gold-linker -prefix ${TOP}/install -no-use-gold-linker -feature-library
    
    Change-Id: I7573ed3556d3acddb13d6ab3d06f21afe16e93f6
    
  - prebuilts: update pixman patch
    
    The patch comes from upstream pixman(on github) that fixes
    compile error when building the tests with newer clang.
    
    the error message:
    test/utils-prng.c:207:27: error: use of unknown builtin '__builtin_shuffle'
    test/utils-prng.c:207:25: error: assigning to 'uint8x16'
    
    Change-Id: Ifb050549cd2923fac2e3d5057f5dc9f30c27d38b