Update git submodules
* Update external/f2fs-tools from branch 'master'
  to 4cca49b65f272686f88d6325d89c3e358cc225a5
  - Merge remote-tracking branch 'aosp/upstream-master' into aosp
    
    * aosp/upstream-master:
      mkfs.f2fs: add -r (fake_seed) flag
      mkfs.f2fs: add -T flag
      sload.f2fs: handle root mount point properly when setting file attribute
      f2fs-tools: zns zone-capacity support
      f2fs_io: measure performance of write()
      f2fs_io: add OSYNC option
      fsck.f2fs: correct return value
      f2fs_io: open file in read only mode for pinning file
    
    Bug: 158453869
    Signed-off-by: Jaegeuk Kim <jaegeuk@google.com>
    Change-Id: I287e9f68658e3966b25cbf6a7f8ba55f042441f3
    
  - mkfs.f2fs: add -r (fake_seed) flag
    
    r flag sets the checkpointing seed to 0 (initially used to
    remove randomness for apex generation)
    
    Signed-off-by: Theotime Combes <tcombes@google.com>
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - mkfs.f2fs: add -T flag
    
    T flag sets timestamps to a given value
    
    Signed-off-by: Theotime Combes <tcombes@google.com>
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - sload.f2fs: handle root mount point properly when setting file attribute
    
    Need to remove "/" of mount point name from the file path name
    when mount point is "/". Otherwise, we will transfer file path
    name whose first two characters are like "//" to fs_config function.
    
    Signed-off-by: Daeho Jeong <daehojeong@google.com>
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - f2fs-tools: zns zone-capacity support
    
    NVM Express Zoned Namespace (ZNS) devices can have zone-capacity(zc) less
    than the zone-size. ZNS defines a per zone capacity which can be equal
    or less than the zone-size. Zone-capacity is the number of usable blocks
    in the zone. If zone-capacity is less than zone-size, then the segments
    which start at/after zone-capacity are considered unusable. Only those
    segments which start before the zone-capacity are considered as usable
    and added to the free_segment_count and free_segment_bitmap of the kernel.
    In such cases, the filesystem should not write/read beyond the
    zone-capacity.
    
    Update the super block with the usable number of blocks and free segment
    count in the ZNS device zones, if zone-capacity is less than zone-size.
    Set reserved segment count and overprovision ratio based on the usable
    segments in the zone.
    
    Allow fsck to find the free_segment_count based on the zone-capacity and
    compare with checkpoint values.
    
    Signed-off-by: Aravind Ramesh <aravind.ramesh@wdc.com>
    Signed-off-by: Shin'ichiro Kawasaki <shinichiro.kawasaki@wdc.com>
    [Jaegeuk Kim: add UNUSED to is_usable_seg()]
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - f2fs_io: measure performance of write()
    
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - f2fs_io: add OSYNC option
    
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - fsck.f2fs: correct return value
    
    As Norbert Lange reported:
    
    "
    $ fsck.f2fs -a /dev/mmcblk0p5; echo $?
    Info: Fix the reported corruption.
    Info: Mounted device!
    Info: Check FS only on RO mounted device
    Error: Failed to open the device!
    255
    "
    
    Michael Laß reminds:
    
    "
    I think the return value is exactly the problem here. See fsck(8) (
    https://linux.die.net/man/8/fsck) which specifies the return values.
    Systemd looks at these and decides how to proceed:
    
    https://github.com/systemd/systemd/blob/a859abf062cef1511e4879c4ee39c6036ebeaec8/src/fsck/fsck.c#L407
    
    That means, if fsck.f2fs returns 255, then
    the FSCK_SYSTEM_SHOULD_REBOOT bit is set and systemd will reboot.
    "
    
    So the problem here is fsck.f2fs didn't return correct value to userspace
    apps, result in later unexpected behavior of rebooting, let's fix this.
    
    Reported-by: Norbert Lange <nolange79@gmail.com>
    Reported-by: Michael Laß <bevan@bi-co.net>
    Signed-off-by: Chao Yu <yuchao0@huawei.com>
    [Jaegeuk Kim: fix FSCK_ERROR_CORRECTED]
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - f2fs_io: open file in read only mode for pinning file
    
    To use "pinfile" command even with read only file, changed open
    mode for it.
    
    Signed-off-by: Daeho Jeong <daehojeong@google.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>