Disable bazel for build-tools for now.
The reasons is that by default soong will run in mixed build mode, and I am
adding some support for DCLA libs where if an apex variant of the DCLA libs
is requested soong will ask bazel to build it (by issuing bazel cquery and
aquery commands from soong), for example, libbase is a DCLA lib, and when
bazel process the cquery and aquery commands it will need to locate the
android tool chain, so it gives me error like this:

ERROR: /usr/local/google/home/yudiliu/android/aosp-build-tools/out/soong/workspace/system/libbase/BUILD.bazel:19:18: While resolving toolcha
ins for target //system/libbase:libbase: invalid registered toolchain '//prebuilts/sdk:android_default_toolchain': no such package 'prebuilt
s/sdk': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.

Bug: 240424572
Test: None
Change-Id: I381e643de0dbb6e0e779e996ffc9ae4e31b969e1