Update git submodules
* Update system/tools/xsdc from branch 'master'
  to 5ccb21c51c00377d58b73c21affb60fd237f5d9e
  - Add error message for a missing dependency
    
    To use generated cpp parser, libxml2 dependency is required. But it is
    difficult to check whether libxml2 library should be added as an error
    message. So error message for adding libxml2 is added.
    
    Test: remove libxml2 on xsdc-cpp-tests and check build error log
    errorlog: "out/soong/.intermediates/system/tools/xsdc/tests/resources/
    nested_type/xsdc_nested_type_tests/gen/cpp/include/nested_type.h:14:2:
    error: Require libxml2 library. Please add libxml2 to shared_libs or
    static_libs #error Require libxml2 library. Please add libxml2 to
    shared_libs or static_libs"
    Bug: 171520107
    
    Change-Id: I6b56e48f7c33703af05ab78275892166f509ea7b