Update git submodules
* Update external/f2fs-tools from branch 'master'
  to e7e1a49d8e384652cf70ff0bbd78bebf48824619
  - Merge remote-tracking branch 'aosp/upstream-master' into aosp
    
    * aosp/upstream-master:
      f2fs-tools: avoid unused parameter build errors
      f2fs_io: accept fallocate to have bigger size
      fsck.f2fs: do not access nat etnries in ckpt before initialization
      fsck: Check write pointer consistency of non-open zones
      fsck: Check write pointer consistency of open zones
      fsck: Check fsync data always for zoned block devices
      fsck: Introduce move_one_curseg_info() function
      fsck: Find free zones instead of blocks to assign to current segments
      libf2fs_zoned: Introduce f2fs_reset_zone() helper function
      libf2fs_zoned: Introduce f2fs_report_zone() helper function
      libf2fs_zoned: Introduce f2fs_report_zones() helper function
      fsck.f2fs: check total_segments from devices in raw_super
      mkfs/Makefile.am: fix build without blkid
      tools/fibmap: fix build error
      f2fs_io: add copy command
      f2fs_io: add helper functions for handling errors
    
    Change-Id: Iccc2db9fda90fa563e9fb2903026adb9a6911d60
    Signed-off-by: Jaegeuk Kim <jaegeuk@google.com>
    
  - f2fs-tools: avoid unused parameter build errors
    
    This patch specifies unused parameters explicitly to avoid build errors.
    
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - f2fs_io: accept fallocate to have bigger size
    
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - fsck.f2fs: do not access nat etnries in ckpt before initialization
    
    ckpt->entries is initialized by fsck_init(), but we tried to access it during
    f2fs_do_mount().
    
    The call sequence is:
     - f2fs_do_mount
      - record_fsync_data
        - traverse_dnodes
         - do_record_fsync_data
          - ADDRS_PER_PAGE
           - get_node_info
            - node_info_from_raw_nat(fsck->entries[nid])
     - do_fsck
      - fsck_init
       - build_nat_area_bitmap
        - fsck->entries = calloc(fsck->nr_nat_entries);
    
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - fsck: Check write pointer consistency of non-open zones
    
    To catch bugs in write pointer handling code for zoned block devices,
    have fsck check consistency of write pointers of non-open zones, that
    current segments do not point to. Check two items comparing write pointer
    positions with valid block maps in SIT.
    
    The first item is check for zones with no valid blocks. When there is no
    valid blocks in a zone, the write pointer should be at the start of the
    zone. If not, next write operation to the zone will cause unaligned write
    error. If write pointer is not at the zone start, reset the zone to move
    the write pointer to the zone start.
    
    The second item is check between write pointer position and the last
    valid block in the zone. It is unexpected that the last valid block
    position is beyond the write pointer. In such a case, report as the bug.
    Fix is not required for such zone, because the zone is not selected for
    next write operation until the zone get discarded.
    
    In the same manner as the consistency check for current segments, do the
    check and fix twice: at the beginning of do_fsck() to avoid unaligned
    write error during fsck, and at fsck_verify() to reflect meta data
    updates by fsck.
    
    Signed-off-by: Shin'ichiro Kawasaki <shinichiro.kawasaki@wdc.com>
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - fsck: Check write pointer consistency of open zones
    
    On sudden f2fs shutdown, write pointers of zoned block devices can go
    further but f2fs meta data keeps current segments at positions before the
    write operations. After remounting the f2fs, this inconsistency causes
    write operations not at write pointers and "Unaligned write command"
    error is reported.
    
    To avoid the error, have f2fs.fsck check consistency of write pointers
    of open zones that current segments point to. Compare each current
    segment's position and the write pointer position of the open zone. If
    inconsistency is found and 'fix_on' flag is set, assign a new zone to the
    current segment and check the newly assigned zone has write pointer at
    the zone start. Leave the original zone as is to keep data recorded in
    it.
    
    To care about fsync data, refer each seg_entry's ckpt_valid_map to get
    the last valid block in the zone. If the last valid block is beyond the
    current segments position, fsync data exits in the zone. In case fsync
    data exists, do not assign a new zone to the current segment not to lose
    the fsync data. It is expected that the kernel replay the fsync data and
    fix the write pointer inconsistency at mount time.
    
    Also check consistency between write pointer of the zone the current
    segment points to with valid block maps of the zone. If the last valid
    block is beyond the write pointer position, report to indicate a bug. If
    'fix_on' flag is set, assign a new zone to the current segment.
    
    When inconsistencies are found, turn on 'bug_on' flag in fsck_verify() to
    ask users to fix them or not. When inconsistencies get fixed, turn on
    'force' flag in fsck_verify() to enforce fixes in following checks.
    
    This check and fix is done twice. The first is done at the beginning of
    do_fsck() function so that other fixes can reflect the current segment
    modification. The second is done in fsck_verify() to reflect updated meta
    data by other fixes.
    
    Signed-off-by: Shin'ichiro Kawasaki <shinichiro.kawasaki@wdc.com>
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - fsck: Check fsync data always for zoned block devices
    
    Fsck checks fsync data when UMOUNT flag is not set. When the f2fs was not
    cleanly unmouted, UMOUNT flag is not recorded in meta data and fsync data
    can be left in the f2fs. The first fsck run checks fsync data to reflect
    it on quota status recovery. After that, fsck writes UMOUNT flag in the
    f2fs meta data so that second fsck run can skip fsync data check.
    
    However, fsck for zoned block devices need to care fsync data for all
    fsck runs. The first fsck run checks fsync data, then fsck can check
    write pointer consistency with fsync data. However, since second fsck run
    does not check fsync data, fsck detects write pointer at fsync data end
    is not consistent with f2fs meta data. This results in meta data update
    by fsck and fsync data gets lost.
    
    To have fsck check fsync data always for zoned block devices, introduce
    need_fsync_data_record() helper function which returns boolean to tell
    if fsck needs fsync data check or not. For zoned block devices, always
    return true. Otherwise, return true if UMOUNT flag is not set in CP.
    Replace UMOUNT flag check codes for fsync data with the function call.
    
    Signed-off-by: Shin'ichiro Kawasaki <shinichiro.kawasaki@wdc.com>
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - fsck: Introduce move_one_curseg_info() function
    
    When fsck updates one of the current segments, update_curseg_info() is
    called specifying a single current segment as its argument. However,
    update_curseg_info() calls move_curseg_info() function which updates all
    six current segments. Then update_curseg_info() for a single current
    segment moves all current segments.
    
    This excessive current segment move causes an issue when a new zone is
    assigned to a current segment because of write pointer inconsistency.
    Even when a current segment has write pointer inconsistency, all other
    current segments should not be moved because they may have fsync data
    at their positions.
    
    To avoid the excessive current segment move, introduce
    move_one_curseg_info() function which does same work as
    move_curseg_info() only for a single current segment. Call
    move_one_curseg_info() in place of move_curseg_info() from
    update_curseg_info().
    
    Signed-off-by: Shin'ichiro Kawasaki <shinichiro.kawasaki@wdc.com>
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - fsck: Find free zones instead of blocks to assign to current segments
    
    When fsck needs to assign a new area to a curreng segment, it calls
    find_next_free_block() function to find a new block to assign. For zoned
    block devices, fsck checks write pointer consistency with current
    segments' positions. In case a curseg is inconsistent with the
    write pointer of the zone it points to, fsck should assign not a new free
    block but a new free zone/section with write pointer at the zone start,
    so that next write to the current segment succeeds without error.
    
    To extend find_next_free_block() function's capability to find not only
    a block but also a zone/section, add new_sec flag to
    find_next_free_block() function. When new_sec flag is true, skip check
    for each block's availability so that the check is done with unit of
    section. Note that it is ensured that one zone has one section for f2fs
    on zoned block devices. Then the logic to find a new free section is good
    to find a new free zone.
    
    When fsck target devices have ZONED_HM model, set new_sec flag true to
    call find_next_free_block() from move_curseg_info(). Set curseg's
    alloc_type not SSR but LFS for the devices with ZONED_HM model, because
    SSR block allocation is not allowed for zoned block devices. Also skip
    relocate_curseg_offset() for the devices with ZONED_HM model for the
    same reason.
    
    Signed-off-by: Shin'ichiro Kawasaki <shinichiro.kawasaki@wdc.com>
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - libf2fs_zoned: Introduce f2fs_reset_zone() helper function
    
    To prepare for write pointer consistency fix by fsck, add
    f2fs_reset_zone() helper function which calls RESET ZONE command. The
    function is added to lib/libf2fs_zoned which gathers zoned block device
    related functions.
    
    When f2fs-tools are built without blkzoned.h kernel header, the helper
    function f2fs_reset_zone() prints an error message as other helper
    functions in lib/libf2fs_zoned print. To make the message consistent
    through the all helper functions, modify message strings in
    f2fs_check_zones() and f2fs_reset_zones().
    
    Signed-off-by: Shin'ichiro Kawasaki <shinichiro.kawasaki@wdc.com>
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - libf2fs_zoned: Introduce f2fs_report_zone() helper function
    
    To prepare for write pointer consistency check by fsck, add
    f2fs_report_zone() helper function which calls REPORT ZONE command to
    get write pointer status of a single zone. The function is added to
    lib/libf2fs_zoned which gathers zoned block device related functions.
    
    Signed-off-by: Shin'ichiro Kawasaki <shinichiro.kawasaki@wdc.com>
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - libf2fs_zoned: Introduce f2fs_report_zones() helper function
    
    To prepare for write pointer consistency check by fsck, add
    f2fs_report_zones() helper function which calls REPORT ZONE command to
    get write pointer status. The function is added to lib/libf2fs_zoned
    which gathers zoned block device related functions.
    
    To check write pointer consistency with f2fs meta data, fsck needs to
    refer both of reported zone information and f2fs super block structure
    "f2fs_sb_info". However, libf2fs_zoned does not import f2fs_sb_info. To
    keep f2fs_sb_info structure out of libf2fs_zoned, provide a callback
    function in fsck to f2fs_report_zones() and call it for each zone.
    
    Add SECTOR_SHIFT definition in include/f2fs_fs.h to avoid a magic number
    to convert bytes into 512B sectors.
    
    Signed-off-by: Shin'ichiro Kawasaki <shinichiro.kawasaki@wdc.com>
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - fsck.f2fs: check total_segments from devices in raw_super
    
    For multi-device F2FS, we should check if the sum of total_segments from
    all devices matches segment_count.
    
    Signed-off-by: Qiuyang Sun <sunqiuyang@huawei.com>
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - mkfs/Makefile.am: fix build without blkid
    
    Commit d56232bc1640e2a3ffc412faff42cd8e77dbb8dd hardcoded -lblkid in
    libf2fs_format_la_LDFLAGS which breaks the build with --without-blkid
    option so use ${libblkid_LIBS} instead
    
    Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - tools/fibmap: fix build error
    
    fibmap.c:28:10: fatal error: 'sys/sysmacros.h' file not found
             ^~~~~~~~~~~~~~~~~
    1 error generated.
    make[3]: *** [fibmap.o] Error 1
    make[3]: *** Waiting for unfinished jobs....
    
    Fixes: ce64ea0815bf ("f2fs-tools: Add support for Casefolding")
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - f2fs_io: add copy command
    
    Add a copy command to f2fs_io, to allow testing direct I/O writes where
    the source page is from a different file (mmap) or an internal kernel
    page (sendfile).  It could be useful for other tests in the future too.
    
    Signed-off-by: Eric Biggers <ebiggers@google.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - f2fs_io: add helper functions for handling errors
    
    Add and use helper functions for:
    
    - Printing an error message (optionally with errno) and exiting.
    - Allocating memory, exiting on error.
    - Opening a file, exiting on error.
    
    Signed-off-by: Eric Biggers <ebiggers@google.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>