Update git submodules
* Update external/brotli from branch 'master'
  to 876ec63736a1ae918e8d1fe1e93d4e45156279f4
  - Upgrade brotli to v1.0.8
    
    Test: make
    Change-Id: Ibcf77fefe96f8411bd173ea180b6bdb5e2ee081a
    
  - Fix build files (#829)
    
    
  - New version: 1.0.8 (#827)
    
    
  - Update (#826)
    
     * IMPORTANT: decoder: fix potential overflow when input chunk is >2GiB
     * simplify max Huffman table size calculation
     * eliminate symbol duplicates (static arrays in .h files)
     * minor combing in research/ code
    
  - Fix output parameter type for _BitScanReverse (#819)
    
    Fix #811
  - CMake: change default ("") build type to Release (#818)
    
    Fix #817
  - Mute strerror/strcpy warnings is MSVC build. (#815)
    
    
  - Add workaround for lying feof. (#814)
    
    Should fix #812
  - Update platform.h (#813)
    
    fix compile error (platform.h:362: error: cast discards qualifiers from pointer target type)
  - Add runtime linker path to pkg-config files (#740)
    
    Otherwise libraries will not be found at runtime when installing to a
    path not included in the default runtime linker's path with programs
    linking brotli configured via pkg-config.
  - .gitignore: Ignore .obj files (#805)
    
    EDK II windows build produces .obj files in source tree
  - Filter sources for the tarball. (#808)
    
    
  - Update (#807)
    
     - fix formatting
     - fix type conversion
     - fix no-op arithmetic with null-pointer
     - improve performance of hash_longest_match64
     - go: detect read after close
     - java decoder: support compound dictionary
     - remove executable flag on non-scripts
  - Update bazel to 2.2 + update config (#798)
    
    Newer bazel does not support `maven_jar` rule anymore...
  - Move TZCNT and BSR intrinsics to platform.h, add MSVC versions (#636)
    
    
  - Added go.mod file to go/cbrotli directory (#754)
    
    * Added go.mod file
    
    * go.mod removed go version
  - Add HAVE_LOG2 build macro (#783)
    
    * Add HAVE_LOG2 build macro
    
    Fixes #781
    
    * Rename macro to BROTLI_HAVE_LOG2 and move comment for visibility
  - Adding CIFuzz (#797)
    
    
  - Make types of variable match (#796)
    
    
  - Add missing "const" to a couple of kConstants (#780)
    
    These showed up in a Chromium audit:
    https://bugs.chromium.org/p/chromium/issues/detail?id=747064#c8
    
    Although already effectively const, adding "const" causes the symbols to
    be moved into the read-only section of the binary.
  - Add vcpkg installation instructions (#776)
    
    
  - Fix license in setup.py (#769)
    
    
  - Add oss-fuzz fuzzing status badge to README (#767)
    
    
  - Disable PIC in EMCC mode. (#768)
    
    
  - Add an option to avoid building shared libraries. (#766)
    
    Add an option to avoid building shared libraries (for building with EMCC)
    
    Drive-by:
    * maven: ramp up java level to minimal required
    * travis: replace deprecated clang-5.0 with clang-7
    * maven: fallback to jdk10 to void javadoc bug
    
  - Fix include for EMCC build (#765)
    
    
  - More careful sanitizer detection (#764)
    
    
  - Update (#762)
    
    * put LICENSE file into .jar
     * fix typo
     * add clarification comment in PY wrapper
  - Explicitly mark tests/testdata/* as binary. (#761)
    
    Fixes #760
    
    Drive-by:
     * update go_rules
     * modernize brotli_inc
     * fix wrapper build
     * update PY to 3 in Travis / OSX / Bazel build
     * upgrade JS Bazel rules.
    
  - Update (#753)
    
     * fix executable mode of decode.js
     * explain clang-analyser about non-nullability
     * fix "dead assignment"
     * rename proguard.cfg -> proguard.pgcfg
  - Update (#749)
    
    Update:
    
     * Bazel: fix MSVC configuration
     * C: common: extended documentation and helpers around distance codes
     * C: common: enable BROTLI_DCHECK in "debug" builds
     * C: common: fix implicit trailing zero in `kPrefixSuffix`
     * C: dec: fix possible bit reader discharge for "large-window" mode
     * C: dec: simplify distance decoding via lookup table
     * C: dec: reuse decoder state members memory via union with lookup table
     * C: dec: add decoder state diagram
     * C: enc: clarify access to static dictionary
     * C: enc: improve static dictionary hash
     * C: enc: add "stream offset" parameter for parallel encoding
     * C: enc: reorganize hasher; now Q2-Q3 require exactly 256KiB
               to avoid global TCMalloc lock
     * C: enc: fix rare access to uninitialized data in ring-buffer
     * C: enc: reorganize logging / checks in `write_bits.h`
     * Java: dec: add "large-window" support
     * Java: dec: improve speed
     * Java: dec: debug and 32-bit mode are now activated via system properties
     * Java: dec: demystify some state variables (use better names)
     * Dictionary generator: add single input mode
     * Java: dec: modernize tests
     * Bazel: js: pick working commit for closure rules
    
  - Update WORKSPACE files. (#742)
    
    
  - Fix #741
  - Ensure decompression consumes all input (#730)
    
    * Ensure decompression consumes all input
    
    If not, it's a corrupt stream.
    
    * Use byte strings
    
  - Verbose CLI + start pulling "Shared-Brotli" (#722)
    
    * Verbose CLI + start pulling "Shared-Brotli"
    
     * vesbose CLI output; fix #666
     * pull `SHIFT` transforms; currently this is semantically dead code;
       later it will be used by "Shared-Brotli"