Update git submodules
* Update tools/repohooks from branch 'master'
  to a863ff2a5fe16dab4b0198e35e9d41c3e3b84987
  - Add prebuilt apk builtin hook
    
    Checking in platform prebuilt APKs requires that the commit message
    contains the APK's badging info, location of where it was built,
    and whether or not it is suitable for public or preview release.
    
    Bug: 111363405
    Test: Unit tests pass
    Test: Manual.  Enabled hook, tried to submit CLs with different
          commit messages.
    
    Change-Id: I0b2aa17ee41d9c2d6a8d27608c532bd7c9e42f8f
    
  - checkpatch: update to linux-4.17
    
    We also need to fix the update script to handle version output that
    is sorted alphabetically rather than by versions.  Otherwise we keep
    seeing 4.9 as the latest release instead of 4.1x.
    
    Bug: chromium:850856
    Test: `./checkpatch.pl-update` grabs 4.17
    Change-Id: I821737ec685fda8d18b87edbf6112e3da54da67f
    
  - hooks: Explain the case-sensitivity of the regexps
    
    Bug: None
    Test: Read the error after changing this line to start with "TEST: "
    Change-Id: I660b036812fe2ecc3d779f283528f685c5570b8c
    
  - Merge "pylint: say what you're missing."
  - pylint: say what you're missing.
    
    The binary can be specified and probably you'll need something
    different if you specified something other than pylint.
    
    Fall back to suggesting the name of the binary which happens to match
    the package name, for pylint3.
    
    Bug: 78321780
    Test: ./pylint.py --executable-path asdf ./pylint.py
      # and observe the error message.
    
    Change-Id: If93726d9bbd097f97ccfe132404a9cb2cabcb033
    
  - git: Properly handle gitfiles
    
    For additional worktrees, .git is not a directory, but instead a "gitfile"
    pointing to the actual .git directory.
    
    To properly handle those, leverage git-rev-parse for validating git
    repositories instead of determining it by checking whether there is
    a .git directory.
    
    Test: git worktree add worktree; cd worktree; git branch --set-upstream-to=goog/pi-dev; ../pre-upload.py --dir .
    Bug: 77999387
    Change-Id: I18b2fd6df58e24e644cd3c29eed99a80ae462fb0
    
  - Allow users to specify list of files/path to google-java-format
    am: cc9b46c682
    
    Change-Id: Ib0226d718d7a959ef15de6a6c4bfe582e7603107
    
  - Disallow external diff drivers in rh/git.py and google-java-format.py
    am: 9e01ab18dc
    
    Change-Id: I071e9c5655e5aac08014334d8b7122120080d0ca
    
  - Allow users to specify list of files/path to google-java-format
    
    Bug: 69068870
    Test: Ran "repo upload" and verified that google-java-format runs on all
          modified files when a list of files/path is not specified.
    Test: Ran "repo upload" and verified that google-java-format runs on all
          modified files from a list of files/path.
    Change-Id: Ib07c9fa81ffbcf7ef38feaf6ea40b321c701f998
    
  - Disallow external diff drivers in rh/git.py and google-java-format.py
    
    Bug: None
    Test: Ran "git diff HEAD^" and verified that the external diff tool was
          not being used.
    Change-Id: I13cfefcf9abf032ad20a9313683eb75442234963
    
  - Merge "pylint: handle missing pylint better"
    am: 97e923f9f0
    
    Change-Id: I5672392469435091ee213c7c5e5531366cc4d941
    
  - Merge "pylint: handle missing pylint better"
  - Merge commit 'ee12b72f62ef9cb2a6881155e94bac3aa259b781' into HEAD
    
    Change-Id: Ia9e7ff6287027c3501fdc47c935614f4f2e1f9e2
    
  - Add support for warning command
    am: 0886c91f7f
    
    Change-Id: I6db604e02f7a7accb136e66cc7de952df62f98f5
    
  - Add support for warning command
    
    If the process exits with code 77, then assume it is a warning,
    print the output of the command, but still allow uploading.
    
    Test: upload hooks
    Bug: 69115822
    Change-Id: I42194203e8e3aa4622e4a79fb995c7df9f8d9314
    
  - cpplint: sync with latest Google version
    am: f43a5e4800
    
    Change-Id: Id8aa9151ea1f90b99c71d891980f327a6111330f
    
  - cpplint: sync with latest Google version
    
    Also tweak the update script to insert a pylint ignore line so it
    doesn't get checked by our pylint upload hooks.
    
    Bug: None
    Test: None
    Change-Id: I8f6d85354cbd52d36b9884852c8b14cc811e0104
    
  - pylint: handle missing pylint better
    
    If you don't have pylint installed, trying to run pylint will result in
    confusuing output:
    
    Traceback (most recent call last):
      File "./tools/pylint.py", line 69, in <module>
        sys.exit(main(sys.argv[1:]))
      File "./tools/pylint.py", line 65, in main
        os.execvp(cmd[0], cmd)
      File "/usr/lib/python2.7/os.py", line 346, in execvp
        _execvpe(file, args)
      File "/usr/lib/python2.7/os.py", line 382, in _execvpe
        func(fullname, *argrest)
    OSError: [Errno 2] No such file or directory
    
    Rather than make people guess that they need to install pylint, catch
    this error and display something more user friendly:
    
    pylint.py: unable to run `pylint`: [Errno 2] No such file or directory
    pylint.py: Try installing pylint: sudo apt-get install pylint
    
    Bug: None
    Test: `./tools/pylint.py tools/cpplint.py --executable-path asdf` no longer barfs
    Change-Id: I7a259e2d950d66855c0dea367e035fe6adc4ce93
    
  - address lint warnings after pylint upgrade
    am: 2ef213ca32
    
    Change-Id: I1797b09c8e64f8e8261e46f7b072e91a21ceeaf7
    
  - address lint warnings after pylint upgrade
    
    Newer pylint 1.6.5 emits warnings not seen with older versions.
    Tweak the code to get lint clean again.
    
    Bug: None
    Test: ./tools/pylint.py no longer complains
    Change-Id: Ib2f620ea4c60357430779c42b16d26a3b2ef2ca7
    
  - clang-format: fail gracefully when clang-format itself aborts am: f363ab9d13 am: 23e637629c
    am: 71d3de9a45
    
    Change-Id: I2c2877949580243039b64b027fc379426c39c410
    
  - clang-format: fail gracefully when clang-format itself aborts am: f363ab9d13
    am: 23e637629c
    
    Change-Id: If8a5f0856401c94705cb7efca7f491aedaaa4610
    
  - clang-format: fail gracefully when clang-format itself aborts
    am: f363ab9d13
    
    Change-Id: Ia424c0df1023b96e02bd67953d2301e35f32ffdb
    
  - clang-format: fail gracefully when clang-format itself aborts
    
    If the clang-format program aborts/crashes, make sure we don't dump
    a raw traceback as users might think it's a problem with repohooks.
    
    Bug: 65671402
    Test: Ran clang-format on some files
    Change-Id: Ibfccac60ad550146d6d44c23c7566361e8add260
    
  - pylint: support per-repo pylintrc files. am: 6d58a8136d am: 6abc478494 am: 97972e149d
    am: 2e3a82f335
    
    Change-Id: Idc8d26d60ec9ef5ebd9c32ecdd1200c231ced73a
    
  - pylint: support per-repo pylintrc files. am: 6d58a8136d am: 6abc478494
    am: 97972e149d
    
    Change-Id: Ib70a8f8a62c18983811efacd6690f39e72244c61
    
  - pylint: support per-repo pylintrc files. am: 6d58a8136d
    am: 6abc478494
    
    Change-Id: I8a8fd19d7ecef6f08c0a26c2a49d44a8aebe31d1
    
  - pylint: support per-repo pylintrc files.
    am: 6d58a8136d
    
    Change-Id: I6c57413997f9720f6c503821f6ffa5d99d7759c7
    
  - pylint: support per-repo pylintrc files.
    
    Use the pylintrc in the repo if exists, otherwise fallback to the
    default one.
    
    Bug: None
    Test: repo upload
    Change-Id: I33cb428ceab56215e375b725da673ffed21cd928
    
  - drop "Android" from the Test error message am: e6f9679d01 am: b13c1acffd
    am: 4c4e78c4d9
    
    Change-Id: Ieb39066166697dad152805c5af7f64bc4a02e5c2
    
  - Add support for automatic fixups to google-java-format am: d1fd88b71c am: 1f99b7db96 am: 086a189a96
    am: 7e74f70baf
    
    Change-Id: I0e57dd108fe8241c36c39ed1f255fb5b7a87f3df
    
  - Add support for automatically applying fixes am: dab680c723 am: b7b810ad5a am: 93bfe8098e
    am: d7f8346125
    
    Change-Id: I81ae436edfa08a4b17d64ec6585a8f9ce8179ade
    
  - Pass --skip-sorting-imports to google-java-format. am: 1b169302fe am: 7aaaa82a25 am: d14131b6cc
    am: fca9989bf6
    
    Change-Id: I157b09bd41d2963ee52fd40130ea8b6b2d917f33
    
  - Pass --skip-sorting-imports to google-java-format.
    
    In the newest version of the formatter, imports are sorted by default.
    This would normally be fine, except that AOSP has a defined order that
    doesn't confirm to this style, which would lead to the formatter
    requiring a lot of changes and possibly introducing conflicts without
    a larger scale cleanup. So turn off this behavior.
    
    Projects that would prefer to sort their imports may specify the
    --sort-options arg in their PREUPLOAD.cfg files to revert to the
    default google-java-format behavior.
    
    Bug: 31552314
    Test: Verified in local test repository
    Change-Id: I9e2df57ef472e7f2d1d4e795ba63559c1aacac67
    
  - Add a builtin repo hook to run google-java-format. am: 0f9d9f8609 am: b34b636e95 am: e6f64f7d49
    am: 212e1d6e31
    
    Change-Id: I98622341432fe4382e12b9160a646a16e027ed1a
    
  - Add more environment variables am: e9db4ebaf5 am: f6ce62d673 am: 1265b558b7
    am: 55456e9f58
    
    Change-Id: If92c92edea3033ff0c561ecbcf8906b746997a91
    
  - hooks: update clang-format tool documentation am: ec044d3e9b am: 335ed4f76a am: bee1fea3b2
    am: 413eadc25b
    
    Change-Id: Ie7a52e953d8e97682401ef95f86ea8d51208b247
    
  - unify helper vars across all sections am: b960818021 am: 90f1f4558c am: 9f6c447004
    am: 17fc41882e
    
    Change-Id: I8d3e074e58b14da099ffa527e9d561a838ccd512
    
  - Merge "Add Tool Path for gofmt" am: a1fe889a64 am: 1943046070
    am: 723744d58c
    
    Change-Id: I91a624c4dc2f8ff2471beabffeb16e707c596058
    
  - hooks: Improve the clang-format wrapper script am: 4913e578e8 am: 2c917a92f9
    am: 6123b2f421
    
    Change-Id: Iad28d39347bf5867af3a179bc9f63f71bffd669d
    
  - Add an option to ignore merged commits am: 5c4c293174 am: 5a82c5fd0e
    am: a720538231
    
    Change-Id: I26a9e9cd0285c5d72bb82c9aedc6d6e5d7ad2db7
    
  - Print status of hooks as they're being run. am: 25abf4bf35 am: 90a201c14d am: 0135532ca8
    am: 2158a15b49
    
    Change-Id: I85b0090875007eeb2e7393ce93421e44aacf9b2b
    
  - Fix typo in docstring. am: 54a754b076 am: b8c7f2ccb8 am: 2f26adeda1
    am: e36d4b03f4
    
    Change-Id: I925b504912aae9aff23c0ff1887ab5c3c48bff4b
    
  - hooks: use the provided name for custom hooks. am: 409f5cdc5b am: b4b3b8fdd9 am: 877882f81e
    am: f9cff6d9d0
    
    Change-Id: I52beaddafbe4260eb549fd92b2692d8f5ba69b02
    
  - README: rework config file headers am: 23461b60d2 am: de3fd0266c am: 006e023cf2
    am: cba08cc0b0
    
    Change-Id: Ifb5ad66a6e78cbb6d75bca186fba7e465372e031
    
  - Add a better description of why users should include Test in messages. am: ddb342b01e am: 3287a9ae75 am: f7cbec93f2
    am: de5f20cf23
    
    Change-Id: I06441865eda9b3f8b6394bf8f1c527b2d1ae90b7
    
  - Handle empty commits in repohooks. am: f6ea937965 am: 807254fbc0 am: d3814df213
    am: 28653061a9
    
    Change-Id: I1f2f19b20f1606212b1e4a8a4ea763dc9dad3066
    
  - Merge "pylint: add a tools path config for it" am: 77bdd31937 am: b843789dff am: 84f9b5dc07
    am: 36fcda2e19
    
    Change-Id: Ie9467e49b4e2554298963bd5a4baf74b269a9185
    
  - hooks: Make the error when upstream not found more actionable am: d8f3675ac0 am: 94ec6f85bd am: cecdf7a490
    am: fdc5c159a1
    
    Change-Id: I0e8c8e93bffb6eb8973f5ba3b3cb8d849ac5b04c
    
  - Add cpplint.py to be used in preupload repo hooks am: a49a37499e am: 27d0d8de65 am: 5093c2ce86
    am: fa3b8b1523
    
    Change-Id: I4395d33908f61dbe35052e3ab107bced60afae8c
    
  - hooks: Add a first-approximation clang-format hook am: adc235b65f am: 6d10e2a892 am: 5a47fcc279
    am: 6cc77c9e4e
    
    Change-Id: Ic405fea77927a779875105b45d8d05cb34d50431
    
  - Merge "config: enable loading of project wide defaults" am: 9cac05d73c am: d568fd66ec am: e5e7e04075
    am: 996d41c29d
    
    Change-Id: Ibbbb48003f883091f91d310fe01ba968ce68d019
    
  - Merge "PREUPLOAD.cfg: enable unittests & Test field in commit messages" am: 24db2aaf35 am: 0182a4e8f2 am: 8fb0869dec
    am: c72f383bc0
    
    Change-Id: I0ba94879b40ccbb0488fdd455ef6fd3c38826598
    
  - hooks: bug: allow None am: dd7d4e392f am: 97f0262e00 am: 73de7e2227
    am: 1c98ebded0
    
    Change-Id: I25284261ce1a10400f21ccfef70e8c0bae67f695
    
  - hooks: Add PRESUBMIT_COMMIT to the custom hook options am: 31a817c12a am: 14f28b2e36 am: fa8e1908cd
    am: 1c5a70ef0a
    
    Change-Id: I87b09e27dacb722b4dc615e82242823db5505c94
    
  - Enable repo upload pylint wrapper to work with gpylint. am: 3572e0ab2f am: 271f20b9a6 am: ef6bf99110
    am: a0ae674ccb
    
    Change-Id: I8b85f459f2f0386f1989c54aaae75fe276a8a694
    
  - Add PRESUBMIT_COMMIT_MESSAGE to the env. am: 6f7988675e am: c662107ff1 am: 0da8278cfa
    am: 03768dc1cd
    
    Change-Id: I7249c9e0dfd15a87635f422f5e6ed1cda89ddb4c
    
  - hooks: xmllint: check rng files am: 8ec324d239 am: 5b014f002d am: 5289f13a1b
    am: d4aa82fc48
    
    Change-Id: I525e8a574b2cf3b65dea61083d083089d32cd18c
    
  - hooks: add a 'Test: ' commit message hook am: 5430605ba2 am: 15c1d74174 am: 6e5232e23a
    am: 702722515a
    
    Change-Id: I142ae9672f9aa6a0052af85304778fa17028dd77
    
  - hooks: add a checkpatch.pl hook am: 34ee9be12f am: 72f8216882 am: 1c8271aee5
    am: ce422c8e6c
    
    Change-Id: I3be81c68c1079442e36956426980d2fd1d95f11a
    
  - hooks: add some commit message hooks am: 76b1bc7640 am: dab1a763a5 am: 35eced323d
    am: 0a9b6fa9c9
    
    Change-Id: If59f648fd4e98af1fc595401ed22103b06b3c970
    
  - tools: start a directory to hold various tools/wrappers am: 4953eba604 am: a0fc39b63a am: 8a63383c20
    am: d0e613e2c3
    
    Change-Id: Iea912dd6438b7deb8f43c843b736f63b31c67646
    
  - Add --init-hook option to pylint am: e2a8046fa9 am: 4fa8ff70c1 am: 805ae6406c
    am: 0eb24135f7
    
    Change-Id: I593dea85dfaeb37cc7c69631dd9e870c04bd0c45
    
  - git: make remote parsing a bit more robust am: 05c689eb3e am: 61ea65d290 am: 1c5cc40657
    am: 5779c5fc2d
    
    Change-Id: I39cbd3945115c11e7365fecfe8b63d8e2516b823
    
  - pre-upload: exit quickly when there are no hooks registered am: 558aff4f18 am: a9596d7e7a am: a37f83c9e3
    am: 86df34cd82
    
    Change-Id: I535443345a4fd3b3d7c54bce425480a1153b897c
    
  - rename config file to PREUPLOAD.cfg am: dc25362ca8 am: 1043f9b6da am: b5302178d3
    am: b043e50768
    
    Change-Id: I86ffe11b314e1bbb07e7cd20cec2a316ab88d8b9
    
  - initial import am: 2e65c54e73 am: ea21f26df6 am: 50fcb75fd8
    am: ddf8d7a9ff
    
    Change-Id: I7473e6f4d6a935bc705fdc4a3446a9469e229e24