Update git submodules
* Update external/libchromeos-rs from branch 'master'
  to e0cc5d5a1de2038e55acc4bff322a0018f66ed63
  - Fix build on aosp-master/mainline_modules
    
    Apply the same default as crosvm to avoid inconsistency.
    
    Previous error:
      error: external/libchromeos-rs/Android.bp:35:1: module "liblibchromeos"
      variant "linux_bionic_x86_64_rlib_rlib-std": depends on disabled module
      "libdata_model"
    
    Bug: 174797066
    Test: build/soong/scripts/build-mainline-modules.sh
    Change-Id: I60725421b9fc40d7f30bf78eba876bb2b1adb832
    

* Update external/vm_tools/p9 from branch 'master'
  to c16ad1e3847b804825ccd294e3ac5e7ba6cce005
  - Fix build on aosp-master/mainline_modules
    
    Apply the same default as crosvm to avoid inconsistency. libp9 depends
    on libchromeos.
    
    Previous error:
      error: external/libchromeos-rs/Android.bp:35:1: module "liblibchromeos"
      variant "linux_bionic_x86_64_rlib_rlib-std": depends on disabled module
      "libdata_model"
    
    Bug: 174797066
    Test: build/soong/scripts/build-mainline-modules.sh
    Change-Id: I997c0a6ae2bd69935de1b0ded066942d1e7a1fa6