Merge branch 'upstream-master' into 'master'
* aosp/upstream-master:
  ELF reader: use linkage name instead of name
  DWARF processor: process children of incomplete structures
  DWARF processor: support namespace
  DWARF processor: support scope in enum
  DWARF processor: skip DW_TAG_GNU_template_template_param children
  ELF loader: tweak symbol values as per the ARM and AARCH64 ELF ABIs
  DWARF processor: process static members as variables.
  writer: generate hex IDs using I/O manipulators
  error: use a wrapper object for hexadecimal output cont.
  DWARF processor: handle template parameter pack DIEs
  type roots: add merge support

Signed-off-by: Giuliano Procida <gprocida@google.com>
Change-Id: Ie32d606956daf06b31a632ab189ad1c2b783b62f