Update git submodules
* Update system/tools/aidl from branch 'master'
  to 79f0ed1644e438c4e7ae3435d2c5d33ff85e961a
  - Fix error when added type is AIDL type.
    
    This was causing infinite recursion in the C++ backend because
    the enum with name 'byte' had backing type 'byte' meaning the primitive,
    but AidlTypeSpecifier has no way to encode "I know this is a built-in
    type", so it would recurse.
    
    Bug: 155027421
    Test: added corpus entry
        ERROR: a/path/Foo.aidl:1.15-20: byte is an invalid name because
        'byte' is a built-in AIDL type.
    Change-Id: Ie338be23d8d9b296c6a198f8f79dda5d78701a77