Update git submodules
* Update frameworks/support from branch 'androidx-master-dev'
  to 85f40e19a23bafed775b6292cc1815e1727e3d7e
  - Merge "Fix failing postsubmit test: androidx.camera.extensions.ExtensionTest" into androidx-master-dev
  - Fix failing postsubmit test: androidx.camera.extensions.ExtensionTest
    
    1. When call eglCreateWindowSurface() use EGL14.EGL_NONE instead of 'null'.
       java.lang.IllegalArgumentException: attrib_list == null
    
    This exception happened in the thread which try to set window surface, that exception causes
    the rendering therad got the null window surface object and then native crash occurred.
    
    Bug: 143062759
    Test: Pixel C API23, Pixel 2
    Change-Id: If74bf96a9bed02841334db9c9cb1b25bb420e04f