Update git submodules
* Update frameworks/base from branch 'master'
  to 314863c132479b108f0ce61a5a753123cd3a15ca
  - Merge changes from topic "inc-hard-am"
    
    * changes:
      Revert^2 "Cache resolved theme values"
      Set resource id correctly when resolve fails
      Revert^2 "libandroidfw hardening for IncFs"
      idmap2: remove call to obsolete 'idmap2 verify' from valgrind.sh
      idmap2: remove the 'scan' command
    
  - Revert^2 "Cache resolved theme values"
    
    6ca48473e533a8b89abac6294a0bb8130b8c8c89
    
    Change-Id: Icb295186b85e1edcdcebc1d746f7ff0d6ef66829
    Merged-In: Icb295186b85e1edcdcebc1d746f7ff0d6ef66829
    
  - Set resource id correctly when resolve fails
    
    If for some reason the resource id cannot be resolved to a value
    (there is no configuration that matches the AssetManager configuration
    or some error occurs), set the resource id of the SelectedValue to the
    resource id that could not be resolved. This was the behavior before
    the AssetManager IncFs hardening refactor.
    
    Bug: 173203252
    Test: atest com.google.android.config.pts.PreinstalledAppsTestCase
    Test: Chrome icon appears on launcher
    Change-Id: Iad1760c0e246da1a4bf64d1c2ec60bb08da32d06
    Merged-In: Iad1760c0e246da1a4bf64d1c2ec60bb08da32d06
    
  - Revert^2 "libandroidfw hardening for IncFs"
    
    55ef6167a2c235bd88c7216238b2001b46795b79
    
    Change-Id: I02d4890d181655dfd0a14c188468db512559d27b
    Merged-In: I02d4890d181655dfd0a14c188468db512559d27b
    
  - idmap2: remove call to obsolete 'idmap2 verify' from valgrind.sh
    
    The 'verify' command was removed as part of a707013b78c. Update
    valgrind.sh accordingly.
    
    Test: frameworks/base/cmds/idmap2/valgrind.sh
    Change-Id: I571cb46bb2ca09a244dc7b609a8bb0ffe01a6e2a
    Merged-In: I571cb46bb2ca09a244dc7b609a8bb0ffe01a6e2a
    
  - idmap2: remove the 'scan' command
    
    The 'scan' command has been replaced by 'create-multiple'. Remove the
    unused code.
    
    Also remove unused functions and #includes from FileUtils, and the
    obsolete JNI plumbing.
    
    Test: atest idmap2_tests OverlayDeviceTests OverlayHostTests
    Change-Id: Iae073c13ce64b5db48f22f7e723bc8c0c5fcd2c9
    Merged-In: Iae073c13ce64b5db48f22f7e723bc8c0c5fcd2c9
    

* Update system/incremental_delivery from branch 'master'
  to d593cca8e22cf514f854ceeec935bdee17c6b6ff
  - Merge changes from topic "inc-hard-am"
    
    * changes:
      Fix map_ptr "Bad file descriptor"
      Fix a off64_t compilation error on mac
      Revert^2 "Move map_ptr to incfs namspace"
    
  - Fix map_ptr "Bad file descriptor"
    
    It is common to close a file descriptor after calling mmap since the
    map stays open until munmap is invoked. The current implementation
    of IncfsFileMap checks if block verification is enabled each time the
    pointer to the mmaped data is retrieved. Instead, only check if
    verification is enabled when IncfsFileMap::Create is invoked while the
    fd is guaranteed to be open.
    
    Bug: 173254631
    Test: boot and verify that no more "Bad file descriptor" logs occur
    Test: libincfs-test
    Change-Id: Icddb0c9af717927ef8f186b64ac0287ce0ba4acd
    Merged-In: Icddb0c9af717927ef8f186b64ac0287ce0ba4acd
    
  - Fix a off64_t compilation error on mac
    
    Fix error: use of undeclared identifier 'off64_t'
    Based on fix from If4ede4a3304c74a30143689cec79bca9ce425908.
    
    Bug: 173169164
    Test: none
    Change-Id: Ia8ddf32fea18f2eff168a18234b5563d2522b811
    Merged-In: Ia8ddf32fea18f2eff168a18234b5563d2522b811
    
  - Revert^2 "Move map_ptr to incfs namspace"
    
    f6a4b40998b6fa71ac08a5fa4c9a9d92fa04b1f0
    
    Change-Id: I6b7d8181c7d68e0da3d6505d3de95269ec7b471b
    Merged-In: I6b7d8181c7d68e0da3d6505d3de95269ec7b471b