Update git submodules
* Update tools/asuite from branch 'master'
  to d47254354c51e21dbb550de2d91896ca6b4d47d4
  - Merge "Atest: slience "No module named: google" in python3."
  - Atest: slience "No module named: google" in python3.
    
    ModuleNotFoundError: No module named 'google' only occurs when 2
    criteria stand:
    1. running atest in source code(atest-src or atest3-src).
    2. protobuf is not installed(pip or pip3)
    
    Since most users are running in prebuilt atest, this issue won't occur
    but we need to catch the exception since tab completion becomes the only
    window to invoke atest from source code.
    
    Bug: 147562331
    
    Test: source envsetup.sh; lunch
      pip3 install protobuf
      atest3-src --<tab><tab> # complete args.
      atest3-src hello_world_test # work perfectly.
    
      pip3 uninstall protobuf
      atest3-src -<tab><tab>  # nothing's gonna happen.
      atest3-src --<tab><tab> # nothing's gonna happen.
      atest3-src hello_world_test # will see the prompt.
    
      pip3 install protobuf   # recover installed status.
    
    Change-Id: Ib0c66491b722a0f2841d6e3b959a18aad355e2c5