Update git submodules
* Update device/google/cuttlefish from branch 'pie-gsi'
  to efd82a105f244bf8d5a46e9d70ae9d9637ebf46e
  - Delete references to ivsh in flags and the config.
    
    Bug: 144111429
    Test: launch_cvd -vm_manager=qemu_cli
    Change-Id: I7b1c53d44e6be063eaa1a8ba1cc816ed89c8cfce
    
  - Delete references to the vsoc e2e test
    
    Bug: 144111429
    Test: launch_cvd [-vm_manager=qemu_cli]
    Change-Id: If80c6a9cacd1f4db15287836f8def087b5e7ef3f
    
  - Delete host_region_e2e_test from the host package
    
    This binary doesn't exist anymore.
    
    Test: make installclean && make -j
    Bug: 144973127
    Change-Id: I5f6f59902ed1a7269aa403c097845dfab755dc12
    
  - Delete references to socket_forward_proxy
    
    This only works in qemu/vsoc.
    
    Test: Run with launch_cvd -vm_manager=qemu_cli
    Bug: 144111429
    Change-Id: Ia873ffe8b96c5ecd926bfa9c4f25de229eb5edbd
    
  - Remove references to stream_audio.
    
    This binary only worked with qemu/vsoc.
    
    Bug: 144111429
    Test: Run launch_cvd -vm_manager=qemu_cli
    Change-Id: I7c6bc9727be7834db47dc98a0d91831b6e9b089b
    
  - Delete socket_forward_proxy
    
    This only works with the vsoc driver.
    
    Bug: 144111429
    Test: Run with -vm_manager=qemu_cli
    Change-Id: Ib67a3eb7d32426e16ae2ab337fd652ef039dc9b3
    
  - cuttlefish: EmulatedFakeCamera2: fix -Wimplicit-int-float-conversion
    
    IEEE754 single precision cannot precisely represent RAND_MAX.
    
    error: implicit conversion from 'int' to 'float' changes value from
    2147483647 to 2147483648 [-Werror,-Wimplicit-int-float-conversion]
    
    For purposes of generating random uniforms, this does not matter. Add
    explicit casts of RAND_MAX to float to fix.
    
    Bug: 139945549
    Test: lunch aosp_cf_x86_phone-userdebug && mm
    Change-Id: I72fe9a4f0fa76a0df1552fffb16a793205272d78
    Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
    
  - Replace AutoFreeBuffer uses for SharedFD
    
    Uses a combination of std::stringstream, std::string, and
    std::vector<char>.
    
    Bug: 144387776
    Test: Build and run locally
    Change-Id: I61f696c729b5895e922429cec550054196a01199
    
  - AutoFreeBuffer -> std::vector<char> for netlink
    
    Test: atest cuttlefish_net_tests
    Bug: 144387776
    Change-Id: I7263e59910a785ec2115c03b1f6e36e659df6b0d
    
  - Delete AutoCloseFILE. It is dead code.
    
    Bug: 144387776
    Test: TreeHugger
    Change-Id: I53ebee8d6eec4222da24e021183ee340960eff6f
    
  - Delete AutoUMask. It is dead code.
    
    Test: TreeHugger
    Bug: 144387776
    Change-Id: I3c8f8a36b0641946594ca3af5b627b4a48155a05
    
  - Remove the vsoc host binaries and libraries
    
    Bug: 144111429
    Test: Run launch_cvd -vm_manager=qemu_cli
    Change-Id: I80cec86e26ed98044a2772e1bef8a210decd3097
    
  - Delete the record_audio host binary
    
    Bug: 144111429
    Test: Run launch_cvd -vm_manager=qemu_cli
    Change-Id: I1c2ebfa95154b1f5205ccea38ba21946b722da10
    
  - Remove header dependencies on vsoc_lib
    
    Bug: 144111429
    Test: Run launch_cvd -vm_manager=qemu_cli
    Change-Id: I7cc03d824c5f74792129351c3dde89dbdabde4d5
    
  - Delete vsoc support libraries and tests
    
    Bug: 144111429
    Test: Run launch_cvd -vm_manager=qemu_cli
    Change-Id: I778b653f185acd09ea372eb1fc76f971836e691c
    
  - Delete the stream_audio host binary
    
    This depended on qemu/vsoc.
    
    Bug: 144111429
    Test: Run launch_cvd -vm_manager=qemu_cli
    Change-Id: I4438da35cb1088a571c7f2781ef7c99cc997cdb3
    
  - Delete the record_audio host binary
    
    This depended on qemu/vsoc.
    
    Bug: 144111429
    Test: Run launch_cvd -vm_manager=qemu_cli
    Change-Id: Ie0dc16708088d8282d7be9b038890bba6619bc3d
    
  - Break build dependencies on vsoc_lib
    
    Bug: 144111429
    Test: Run launch_cvd -vm_manager=qemu_cli
    Change-Id: I4ce52ba487a57df26cf1e1171ac732633865bde3
    
  - Delete the legacy audio hal
    
    This only worked with vsoc/qemu.
    
    Bug: 144111429
    Test: Run launch_cvd -vm_manager=qemu_cli
    Change-Id: I7a521962b8e15d245b482f04203937399b7a6893
    
  - Delete vsoc, vsoc-future hwcomposers
    
    Bug: 144111429
    Test: Run with -vm_manager=qemu_cli
    Change-Id: I439d773259aaec60cc3fa37675736dd118b52d8a
    
  - Delete guest/hals/gralloc but not /legacy
    
    Credit to natsu@ for pointing out that /legacy is still needed.
    
    Bug: 144111429
    Test: Run with -vm_manager=qemu_cli
    Change-Id: Ic5e3b4bd50b65da3f989902476a735604f98148c
    
  - Delete ivserver
    
    Bug: 144111429
    Test: Run with -vm_manager=qemu_cli
    Change-Id: I11efcee5769ee84dcde4706d8a50e01d3ddebf42
    
  - Delete ivserver
    
    Bug: 144111429
    Test: Run with -vm_manager=qemu_cli
    Change-Id: Ie90b0a457521f0700f235355b18fb7f07bc36751
    
  - Remove {assemble,launch,run}_cvd ivserver references
    
    Bug: 144111429
    Test: Run with -vm_manager=qemu_cli
    Change-Id: I8d28a9456854d78cf9ae82f50e686712da72fe6c
    
  - Delete socket_forward_proxy
    
    This only works with the vsoc driver.
    
    Bug: 144111429
    Test: Run with -vm_manager=qemu_cli
    Change-Id: Ida0be8aa1b1411fc5573a91284fac2cf8a269886
    
  - Remove guest-side references to vsoc / qemu
    
    Test: Run launch_cvd -vm_manager=qemu_cli
    Bug: 144111429
    Change-Id: I73c9e1712db44bcb962a0084f145255af0f62fbb
    
  - Fix starting vsoc_input_service
    
    Test: Check input in vnc with -vm_manager=qemu_cli
    Bug: 143713267
    Change-Id: I353643f874ff9b210fc7a9d5ca49782c34d24150
    
  - Retrofit vsoc_input_service to use vsock
    
    This allows using vsoc_input_service under qemu without the vsoc/ivshmem
    support that is missing in 4.19 gki.
    
    The alternative is to use virtio-input, but in qemu this requires
    forwarding a hardware device (by using root permissions) while in crosvm
    the same functionality is available through a file descriptor.
    
    Test: launch_cvd -vm_manager=qemu_cli, check adb and vnc
    Bug: 143713267
    Change-Id: Ice9767b28d9011fba6389435c029bed2e80ba7b8
    
  - Retrofit vsoc_input_service to use vsock
    
    This allows using vsoc_input_service under qemu without the vsoc/ivshmem
    support that is missing in 4.19 gki.
    
    The alternative is to use virtio-input, but in qemu this requires
    forwarding a hardware device (by using root permissions) while in crosvm
    the same functionality is available through a file descriptor.
    
    Test: launch_cvd -vm_manager=qemu_cli, check adb and vnc
    Bug: 143713267
    Change-Id: I5b7bdc063ff57aa3a455f77b8a7c23db29e1646e
    
  - Run qemu without vsoc
    
    This enables the crosvm options on qemu and disables references to the
    vsoc driver. The vsoc driver was specially written to share memory with
    the guest and the host through ivsh, but it is not included in the 4.19
    kernel due to difficulty including it as a module in the gki setup.
    
    Test: launch_cvd -vm_manager=qemu_cli, check adb and vnc
    Bug: 143713267
    Change-Id: I747f7f4c2f21c2e737899a07f1d8e8439da3ea6e
    
  - Delete virtual_usb_manager and USB support
    
    This functionality was never enabled for crosvm.
    
    Test: Build and run locally
    Bug: 146087651
    Change-Id: Ifeae71ec11beb3654b201fd431ab1498e980ea31
    
  - Add workaround for missing ROM on arm64
    
    qemu-system-aarch64 incorrectly looks for a ROM file that is not
    installed by default on arm64 systems. This is discussed in more detail
    in https://bugzilla.redhat.com/show_bug.cgi?id=1337510
    
    Change-Id: I623d25660ca62aeaa1502b3e0fc4c026389ee704