Update git submodules
* Update bionic from branch 'master'
  to 50a7621b3fc493ffbb72aa23e29a4f1727dc1f51
  - Merge "[GWP-ASan] Remove include."
  - [GWP-ASan] Remove include.
    
    Unnecessary include, and the file was deleted with upstream changes.
    
    Bug: N/A
    Test: cd external/gwp_asan && atest
    Change-Id: Id8facff0c5e382aa639ce158b7b5862ce157aa25
    

* Update external/gwp_asan from branch 'master'
  to fdfd07773c03b7f6e92bcd8bacb760db6ee813d4
  - [GWP-ASan] [Android-Specific] Integrate upstream build changes.
    
    <eom>
    
    Bug: N/A
    Test: cd external/gwp_asan && atest
    Change-Id: I1677fa81e64da1a7926c635057f6f5e7f0ad1439
    
  - [GWP-ASan] Port tests to Fuchsia
    
    This modifies the tests so that they can be run on Fuchsia:
    - add the necessary includes for `set`/`vector` etc
    - do the few modifications required to use zxtest instead og gtest
    
    `backtrace.cpp` requires stacktrace support that Fuchsia doesn't have
    yet, and `enable_disable.cpp` currently uses `fork()` which Fuchsia
    doesn't support yet. I'll revisit this later.
    
    I chose to use `harness.h` to hold my "platform-specific" include and
    namespace, and using this header in tests rather than `gtest.h`,
    which I am open to change if someone would rather go another direction.
    
    Differential Revision: https://reviews.llvm.org/D91575
    
    GitOrigin-RevId: 5556616b5b5223f95607ad94053a55f0deaf2762
    Change-Id: Iaf94dafca4c47ea8a1995effd16e6eb8c3c27847
    
  - [GWP-ASan] Respect GWP_ASAN_DEFAULT_ENABLED compile-time macro
    
    If the containing allocator build uses -DGWP_ASAN_DEFAULT_ENABLED=false
    then the option will default to false.  For e.g. Scudo, this is simpler
    and more efficient than using -DSCUDO_DEFAULT_OPTIONS=... to set gwp-asan
    options that have to be parsed from the string at startup.
    
    Reviewed By: hctim
    
    Differential Revision: https://reviews.llvm.org/D91463
    
    GitOrigin-RevId: 7810d837864933b49f5e20a970a8e51ea091fa8e
    Change-Id: I1ea91786766f66a71b1b2ccefe6e6d1dea5807a8
    
  - [GWP-ASan] Stub out backtrace/signal functions on Fuchsia
    
    The initial version of GWP-ASan on Fuchsia doesn't support crash and
    signal handlers, so this just adds empty stubs to be able to compile
    the project on the platform.
    
    Differential Revision: https://reviews.llvm.org/D90537
    
    GitOrigin-RevId: 98fe39df939ee6f1fd20b75edcc9fe0860b52dba
    Change-Id: I052fb2894410445675c0c92f6fe2d193c88ce82f
    
  - [GWP-ASan] Fuchsia specific mapping & utilities functions
    
    This CL introduces the Fuchsia versions of the existing platform
    specific functions.
    
    For Fuchsia, we need to track the VMAR (https://fuchsia.dev/fuchsia-src/reference/kernel_objects/vm_address_region)
    of the Guarded Pool mapping, and for this purpose I added some platform
    specific data structure that remains empty on POSIX platforms.
    
    `getThreadID` is not super useful for Fuchsia so it's just left as a
    stub for now.
    
    While testing the changes in my Fuchsia tree, I realized that
    `guarded_pool_allocator_tls.h` should have closed the namespace before
    including `GWP_ASAN_PLATFORM_TLS_HEADER`, otherwise drama ensues.
    
    This was tested in g3, upstream LLVM, and Fuchsia (with local changes).
    
    Differential Revision: https://reviews.llvm.org/D90483
    
    GitOrigin-RevId: 63ad0876567d7a782daedfe9f564942a37f063f5
    Change-Id: I168990fcc3cb04d6db0d325c62df82cd247870eb
    
  - [GWP-ASan] Add mutexes for Fuchsia
    
    Mitch expressed a preference to not have `#ifdef`s in platform agnostic
    code, this change tries to accomodate this.
    
    I am not attached to the method this CL proposes, so if anyone has a
    suggestion, I am open.
    
    We move the platform specific member of the mutex into its own platform
    specific class that the main `Mutex` class inherits from. Functions are
    implemented in their respective platform specific compilation units.
    
    For Fuchsia, we use the sync APIs, as those are also the ones being
    used in Scudo.
    
    Differential Revision: https://reviews.llvm.org/D90351
    
    GitOrigin-RevId: 3591721ada99810aeddfa3d4c83eea0dbeed7f18
    Change-Id: I102c868a95729956e4587f6e0f2a07b45312e31a
    
  - [GWP-ASan] Abstract the thread local variables access
    
    In a similar fashion to D87420 for Scudo, this CL introduces a way to
    get thread local variables via a platform-specific reserved TLS slot,
    since Fuchsia doesn't support ELF TLS from the libc itself.
    
    If needing to use this, a platform will have to define
    `GWP_ASAN_HAS_PLATFORM_TLS_SLOT` and provide `gwp_asan_platform_tls_slot.h`
    which will define a `uint64_t *getPlatformGwpAsanTlsSlot()` function
    that will return the TLS word of storage.
    
    I snuck in a couple of cleanup items as well, moving some static
    functions to anonymous namespace for consistency.
    
    Differential Revision: https://reviews.llvm.org/D90195
    
    GitOrigin-RevId: 90678f65ae47523586bd34392ed3cd1369cf5e9b
    Change-Id: I1b2a2d4a07f977cbade91d90f89c71583e0eb0cc
    
  - [GWP-ASan] Refactor memory mapping functions
    
    In preparation for Fuchsia support, this CL refactors the memory
    mapping functions.
    
    The new functions are as follows:
    - for Freeslots and Metadata:
      `void *map(size_t Size, const char *Name) const;`
      `void unmap(void *Ptr, size_t Size) const;`
    - for the Pool:
      `void *reservePool(size_t Size);`
      `void commitPool(void *Ptr, size_t Size) const;`
      `void decommitPool(void *Ptr, size_t Size) const;`
      `void unreservePool();`
      Note that those don't need a `Name` parameter as those are fixed per
      function. `{reserve,unreserve}Pool` are not `const` because they will
      modify platform specific class member on Fuchsia.
    
    I added a plethora of `assert()` as the initial code was not enforcing
    page alignment for sizes and addresses, which caused problem in the
    initial Fuchsia draft. All sizes should now be properly rounded up to
    a page.
    
    Differential Revision: https://reviews.llvm.org/D89993
    
    GitOrigin-RevId: 612e02ee8c3e8f204378796af2eb526cf5e348f0
    Change-Id: Ice75aeea9879e1bce9ad4617c7eb0a4dd8707792
    
  - [GWP-ASan] Move random-related code in the allocator (redo)
    
    This is a redo of D89908, which triggered some `-Werror=conversion`
    errors with GCC due to assignments to the 31-bit variable.
    
    This CL adds to the original one a 31-bit mask variable that is used
    at every assignment to silence the warning.
    
    Differential Revision: https://reviews.llvm.org/D89984
    
    GitOrigin-RevId: 3580a45014e90a9895cc2dec28ab2e7f78c47470
    Change-Id: I020ea0158bd0365d7ee2926dd7e58d69f4333d6e
    
  - Revert "[GWP-ASan] Move random-related code in the allocator"
    
    This reverts commit 9903b0586cfb76ef2401c342501e61e1bd3daa0f.
    
    Causes build failures (on GCC 10.2) with the following error:
    
    In file included from /home/nikic/llvm-project/compiler-rt/lib/scudo/standalone/combined.h:29,
                     from /home/nikic/llvm-project/compiler-rt/lib/scudo/standalone/allocator_config.h:12,
                     from /home/nikic/llvm-project/compiler-rt/lib/scudo/standalone/wrappers_cpp.cpp:14:
    /home/nikic/llvm-project/compiler-rt/lib/scudo/standalone/../../gwp_asan/guarded_pool_allocator.h: In member function ‘bool gwp_asan::GuardedPoolAllocator::shouldSample()’:
    /home/nikic/llvm-project/compiler-rt/lib/scudo/standalone/../../gwp_asan/guarded_pool_allocator.h:82:69: error: conversion from ‘uint32_t’ {aka ‘unsigned int’} to ‘unsigned int:31’ may change value [-Werror=conversion]
       82 |           (getRandomUnsigned32() % (AdjustedSampleRatePlusOne - 1)) + 1;
          |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
    
    GitOrigin-RevId: 04e42f62548d4c0367664188a938b609435718e2
    Change-Id: Iba53121f730112bb1b553aea0994f535e8d9e569
    
  - [GWP-ASan] Move random-related code in the allocator
    
    We need to have all thread specific data packed into a single `uintptr_t`
    for the upcoming Fuchsia support. We can move the `RandomState` into the
    `ThreadLocalPackedVariables`, reducing the size of `NextSampleCounter`
    to 31 bits (or we could reduce `RandomState` to 31 bits).
    
    We move `getRandomUnsigned32` into the platform agnostic part of the
    class, and `initPRNG` in the platform specific part.
    
    `ScopedBoolean` is replaced by actual assignments since non-const
    references to bitfields are prohibited.
    
    `random.{h,cpp}` are removed.
    
    Differential Revision: https://reviews.llvm.org/D89908
    
    GitOrigin-RevId: 9903b0586cfb76ef2401c342501e61e1bd3daa0f
    Change-Id: If24a2c99aab63fd345d2baa066bf8a180f63c745
    
  - [GWP-ASan] Rework utilities (NFC)
    
    Few changes wrt utilities:
    - split `Check` into a platform agnostic condition test and a platform
      specific termination, for which we introduce the function `die`.
    - add a platform agnostic `utilities.cpp` that gets the allocation
      alignment functions original in the platform specific file, as they
      are reusable by all platforms.
    
    Differential Revision: https://reviews.llvm.org/D89811
    
    GitOrigin-RevId: be8e4de7240eb0f7dc2f7fd6d07898184c04c72b
    Change-Id: Ieb35f441fbecc2c4c6a6d9a9c31690014cd5b159
    
  - [GWP-ASan] Cleanup (NFC)
    
    Cleaning up some of the GWP-ASan code base:
    - lots of headers didn't have the correct file name
    - adding `#ifdef` guard to `utilities.h`
    - correcting an `#ifdef` guard based on actual file name
    - removing an extra `;`
    - clang-format'ing the code (`-style=llvm`)
    
    Differential Revision: https://reviews.llvm.org/D89721
    
    GitOrigin-RevId: ae9d0400283229032fb3795b7b50920bf9be38dc
    Change-Id: I269ac3eb9bd8f95495f32a3df88969a8038604a6
    
  - [GWP-ASan] Crash handler API returns sizeof(collected trace)
    
    Summary:
    Fix up a slight bug with the crash handler API, where we say that we
    return the size of the collected trace (instead of the size of the trace
    that's returned) when the return buffer is too small, and the result is
    truncated.
    
    Also, as a result, patch up a small uninitialized memory bug.
    
    Reviewers: morehouse, eugenis
    
    Reviewed By: eugenis
    
    Subscribers: #sanitizers
    
    Tags: #sanitizers
    
    Differential Revision: https://reviews.llvm.org/D84652
    
    GitOrigin-RevId: d19af2f2476b5e13a65d5283cce9859e2c1ef763
    Change-Id: I25e3b65e33ac23b5ebfdf2513eb257f842acbdd5
    
  - [GWP-ASan] Add bionic and CTS tests to TEST_MAPPING
    
    <eom>
    
    Bug: N/A
    Test: cd external/gwp_asan && atest
    Change-Id: I74074d83351020cc8cd4dc80852a80baedc003c9