Update git submodules
* Update external/elfutils from branch 'master'
  to 90dbf8b9d445351125baf97f32bd38ac718e558c
  - Merge "Upgrade elfutils to elfutils-0.182"
  - Upgrade elfutils to elfutils-0.182
    
    Test: make
    Change-Id: Ib7da528486d0474ccbc82dd53fb52303ef59f75c
    
  - Do not install profile.d/debuginfod.*sh files unless debuginfod is enabled
    
    Fixes: 94708e964601 ("PR25461: add /etc/profile.d files for default $DEBUGINFOD_URLS")
    Fixes: fee123fb771f ("PR25461: uninstall /etc/profile.d files for distuninstallcheck")
    Signed-off-by: Dmitry V. Levin <ldv@altlinux.org>
    
  - Prepare for 0.182
    
    Set version to 0.182.
    Update NEWS and elfutils.spec.in.
    Regenerate po/*.po files.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - debuginfod: Accelerate traversal, shutdowns, improve metrics
    
    Added new metrics for scanning that allow estimation of its reading
    bandwidth.  Accelerated responsivity to SIGINT shutdown during
    archive-scanning phase, which previously insisted on completely
    processing the current archive.  Noted in systemd service file that in
    the worst case, it might still take a long time.  Accelerated
    traversals by moving regex -I/-X handling to apply to file names only
    (as always documented), so directory traversal metrics are accurate
    regardless of their name.
    
    Signed-off-by: Frank Ch. Eigler <fche@redhat.com>
    
  - tests: Add dlopen override to dwfl-proc-attach for old glibc/valgrind.
    
    Some combination of old glibc and valgrind create unsuppressable memory
    leak warnings when the process is run under valgrind, is multi-threaded
    and uses dlopen. libdw will try to dlopen libdebuginfod be default.
    So simply override dlopen and always return NULL to make sure
    libdebuginfod is never loaded.  The dwfl-proc-attach test doesn't rely
    on libdebuginfod anyway.
    
    This was seen on the armbian buildbot which uses valgrind 3.14.0 and
    glibc 2.28.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - tests: Remove bashism from test-wrapper.sh /bin/sh script.
    
    Debian uses dash as /bin/sh which is pretty strict about syntax. It
    didn't like the == in  the test for strings in the test-wrapper.sh.
    Replace by single =.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - tests: Run valgrind also on binary tests.
    
    When configuring with --enable-valgrind we were only running valgrind
    on tests with a shell wrapper script. This patch makes sure to also run
    valgrind on "pure" binary tests. This found one small issue in libasm
    where we could be writing some uninitialized padding to an ELF file.
    And there were a couple tests that didn't clean up all the resources
    they used. Both issues are also fixed with this patch.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - elfutils.spec.in: fix debuginfod state/config file flags
    
    During a test upgrade of an RPM based on this spec file, it was
    observed that, er, the /var/cache/.../debuginfod.sqlite file was
    zeroed.  Whoops!  We don't want to lose this data.  Removed the
    %verify attributes and added %ghost for the sqlite database.
    
    Signed-off-by: Frank Ch. Eigler <fche@redhat.com>
    
  - PR26775: restore thread_work_groom metric to cycle count
    
    ... and add new metrics about progress of traversal and groom
    processes.  Correct one control flow abnormality that could
    prematurely end a scanner thread and might have accounted for
    the inconsistent test results from the previous patch.
    
    Signed-off-by: Frank Ch. Eigler <fche@redhat.com>
    
  - PR26775: make grooming progress visible & interruptible
    
    On very large servers, it's desirable to be able to interrupt a rescan
    or groom cycle.  SIGUSR[12] now do that.  (Unfortunately, this is not
    practically testable in the testsuite, since these cycles are so fast
    on that small dataset.)  We also expose more internal progress count
    about the grooming pass, so the administrator can assess possible need
    to interrupt.
    
    Signed-off-by: Frank Ch. Eigler <fche@redhat.com>
    
  - PR26810: debuginfod should tolerate some absence/renaming sans grooming
    
    debuginfod now knows to handle a case where a buildid search is
    satisfiable from more than one source (e.g., archive location), but
    some of them are invalid.  New exception catching beneath the sqlite
    scanning loop ensures all possible matches are scanned in case of
    errors.
    
    Signed-off-by: Frank Ch. Eigler <fche@redhat.com>
    
  - tests: Add read_unaligned testcase
    
    Run tests/read_unaligned 1 on a big endian and little endian machine
    to generate the le_mem and be_mem arrays. The one byte variants are
    kind of impossible to get wrong, but including them makes sure the
    other variants are not naturally aligned in memory.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - Fix leb128 reading
    
    PR 26773 points out that some sleb128 values are decoded incorrectly.
    
    This version of the fix only examines the sleb128 conversion.
    Overlong encodings are not handled, and the uleb128 decoders are not
    touched.  The approach taken here is to do the work in an unsigned
    type, and then rely on an implementation-defined cast to convert to
    signed.
    
    Signed-off-by: Tom Tromey <tom@tromey.com>
    
  - libelf: Sync elf.h from glibc.
    
    Makes elf.h standalone and removes __BEGIN_DECLS/__END_DECLS macros.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - unstrip: Stop using strndupa.
    
    This functon has inherent safety issues, since a long enough path can
    lead to memory clobbering. Due to the recursive nature of
    make_directories(), multiple calls could also stack overflow. Instead,
    the string can be allocated in the heap.
    
    As a bonus, this improves musl compatibility, since musl doesn't include
    the strndupa macro for now.
    
    Also add braces around while loop.
    
    Signed-off-by: Érico Rolim <erico.erc@gmail.com>
    
  - debuginfod: Translate CURLE_PEER_FAILED_VERIFICATION to ECONNREFUSED.
    
    When a file couldn't be retrieved because of an bad HTTPS certificate
    find-debuginfod currently says:
    Server query failed: No such file or directory
    
    With this patch it will say:
    Server query failed: Connection refused
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - libdw: dwarf_frame_register takes an array of at least 3 Dwarf_Ops
    
    GCC11 will warn about a mismatch in the declaration of dwarf_frame_register:
    
    dwarf_frame_register.c:37:61: error: argument 3 of type ‘Dwarf_Op *’
      declared as a pointer [-Werror=array-parameter=]
       37 | dwarf_frame_register (Dwarf_Frame *fs, int regno, Dwarf_Op *ops_mem,
          |                                                   ~~~~~~~~~~^~~~~~~
    libdw.h:1068:43: note: previously declared as an array ‘Dwarf_Op[3]’
     1068 |                                  Dwarf_Op ops_mem[3],
          |                                  ~~~~~~~~~^~~~~~~~~~
    
    When fixing that it will show an actual bug in the addrcfi testcase:
    
    addrcfi.c:98:16: error: ‘dwarf_frame_register’ accessing 96 bytes in a
      region of size 64 [-Werror=stringop-overflow=]
       98 |   int result = dwarf_frame_register (stuff->frame, regno, ops_mem, &ops, &nops);
          |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    addrcfi.c:98:16: note: referencing argument 3 of type ‘Dwarf_Op *’
     1069 | extern int dwarf_frame_register (Dwarf_Frame *frame, int regno,
          |            ^~~~~~~~~~~~~~~~~~~~
    
    Fix the declaration, fix the bug and add an extra comment to the description
    in libdw.h.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - backends: Remove tilegx backend.
    
    Support for the Tilera TILE-Gx processor has been removed or deprecated
    in gcc and binutils already. There are no users and there is no way to
    test it.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - libebl: Remove unused ebl_syscall_abi.
    
    GCC11 -Warray-parameter warned about ebl_syscall_abi being inconsistently
    declared (once with a pointer to int, once with an array of 6 int elements).
    Since ebl_syscall_abi isn't actually used and was only implemented for
    3 backends without any tests just remove it.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - Fix bug in read_3ubyte_unaligned_inc
    
    The read_3ubyte_unaligned_inc macro calls read_2ubyte_unaligned, but
    it should call read_3ubyte_unaligned.
    
    Signed-off-by: Tom Tromey <tom@tromey.com>
    
  - PR26756: add more prometheus metrics to debuginfod
    
    Add an error_count{} family of metrics for each libc/libarchive/http
    exception instance created during operation.  Add a family of fdcache*
    metrics for tracking fdcache operations and status.  Test via a
    injecting a permission-000 empty nothing.rpm in the testsuite.
    
    Signed-off-by: Frank Ch. Eigler <fche@redhat.com>
    
  - debuginfod: suppress fdcache prefetching during dwz lookup
    
    During a recent from-scratch reindexing of the rpm/deb corpus at
    debuginfod.elfutils.org, we found the fdcache chewed up an abnormal
    amount of $TMPDIR space.  This was due to internal .dwz lookups, which
    triggered fdcache prefetching as for a webapi query, but there was not
    a timely fdcache eviction pass to clean it up again.  Rather than add
    that pass, it's better to suppress the prefetching completely, as an
    internal .dwz search will only ever need that file, not any others
    from the same archive.
    
    Signed-off-by: Frank Ch. Eigler <fche@redhat.com>
    
  - PR25461: uninstall /etc/profile.d files for distuninstallcheck
    
    No one uses "make uninstall" except the buildbot.  Let's make it
    happy too.
    
    Signed-off-by: Frank Ch. Eigler <fche@redhat.com>
    
  - PR25461: add /etc/profile.d files for default $DEBUGINFOD_URLS
    
    To give distros a simple knob to let their userbase enjoy debuginfod
    services, we add a --enable-debuginfod-urls[=URLS] to the configury.
    This propagates to $DEBUGINFOD_URLS environment variable settings
    in /etc/profile.d/debuginfod.{sh,csh} files.
    
    The default is nothing.  If simply enabled, the current prototype
    public server is used.  If enabled with parameters, the builder/distro
    can specify a default URL search path of their own.
    
    Signed-off-by: Frank Ch. Eigler <fche@redhat.com>
    
  - debuginfod-find.1: Fix formatting on wide consoles
    
    The SYNOPSIS section looks less funny with missing
    .br directives added in.
    
    Signed-off-by: Frank Ch. Eigler <fche@redhat.com>
    
  - readelf: Support showing view pairs in loclists as GNU extension.
    
    View pairs are encoded in .debug_loclists as they are encoded in
    .debug_locs sections by the GCC compiler. Scan for DW_AT_GNU_locviews
    attributes that point to the view pairs just in front of the actual
    location lists.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - libdwfl: Add ZSTD support.
    
    Newer kernels might be compressed using ZSTD add support to libdwfl open
    so we can can automatically read ZSTD compressed files and kernel images.
    
    The support is very similar to the bzip2 and lzma support, but slightly
    different. With a bit more macros it could maybe have used the gzip.c
    USE_INFLATE code path. But I felt that the many macros didn't really help
    understand the code. So the unzip routine has a slightly different code
    path for ZSTD.
    
    https://sourceware.org/bugzilla/show_bug.cgi?id=26632
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - debuginfod: store only canonicalized sref pathnames in database
    
    Since PR25548, we let debuginfod answer /buildid/HEX/source/PATH
    queries with both canonicalized and raw PATHs.  It canonicalizes
    incoming paths, but still stored the raw paths in the database too.
    This near-dupe storage is not needed, since the queries would always
    find the canonicalized version too, so stop doing that.  This saves
    database space/time.
    
    Signed-off-by: Frank Ch. Eigler <fche@redhat.com>
    
  - debuginfod: Fix BUILD_STATIC build.
    
    The BUILD_STATIC build, as used by the coverage setup, was broken for
    debuginfod because the DUMMY_LIBDEBUGINFOD case was mixed up. It should
    include libcurl_LIBS when NOT doing a dummy build.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - debuginfod-find.c: Fix license block comment. File is GPLv3+ only.
    
    The license itself was correct, just the comment to get a copy of
    the LGPL was wrong.
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>
    
  - debuginfod-find: Support compressed (kernel) ELF images.
    
    By using dwelf_elf_begin instead of elf_begin we automatically get
    support for determining the build-id of compressed (kernel) images.
    
    https://sourceware.org/bugzilla/show_bug.cgi?id=26599
    
    Signed-off-by: Mark Wielaard <mark@klomp.org>