Darwin: Point to the correct version of libstd
Fixes build breakage:
error: prebuilts/rust/darwin-x86/Android.bp:18:1: module
"libstd_x86_64-apple-darwin" variant "darwin_x86_64_rlib":
module source path
"prebuilts/rust/darwin-x86/1.50.0/lib/rustlib/x86_64-apple-darwin/lib/libstd-2f4e11c6a19d82a4.rlib"
does not exist

Test: TH
Change-Id: I08ca6d2510ae58b3e829e7461d09aa4014df6281