Update git submodules
* Update external/libcap from branch 'master'
  to d3106b3008811589a68aee30919d041793cdb09d
  - Upgrade libcap to libcap-2.39
    
    Change-Id: I372a3e08bacb93acadb81ff5ca263eac882ef7a2
    
  - Up the release version to 2.39
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - More experiments with markdown as a representation for the man pages.
    
    I'm leaning towards pandoc instead of man-to-md. Mostly because it has
    greater coverage in terms of supported formats.
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - Some documentation for individual capability values.
    
    I want a place to capture nuances in these files through experience
    and bug reports/patches.
    
    Make use of these to document the Go cap package definitions of each
    Value so that the godoc automated documentation at places like go.dev
    become more useful for actually using the package.
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - libcap/cap Go package documentation cleanup.
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - Rewrite libpsx thread shutdown path to support musl.
    
    Addresses:
    
       https://bugzilla.kernel.org/show_bug.cgi?id=208477
    
    Removed the non-wrapping libpsx macro hacks. The API surface as such
    becomes a little smaller and I now have confidence that wrapping
    pthread_create using the linker options works with Go, gcc and musl
    compilers. I feel it is stable enough to call good to delete the
    workarounds.
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - Remove incorrect and misleading comment.
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - Add a Go example of changing UID/GID.
    
    This is something pretty fundamental that a number of folk have asked
    about. It is essentially the motivating issue for:
    
       https://github.com/golang/go/issues/1435
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - It looks as if the module files need a libcap directory tag.
    
    I initially made one, and now modules are building with that stale
    value v0.2.37. All despite the fact the Go modules are at v0.2.38.
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - Drop the go suffix from module name.
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - Up the release version to 2.38
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - Fix a rare deadlock in cap.Launch().
    
    The main functional change with this commit is to fix this bug:
    
      https://bugzilla.kernel.org/show_bug.cgi?id=208445
    
    Also, include better documentation for the "cap" module. Now that it
    is a proper Go module, it is starting to show up on the automated
    golang module sites (such as pkg.go.dev) and I thought it deserved
    more of an intro comment.
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - Fix capability list generation and legacy go package install.
    
    Fixes Hussam Al-Tayeb bug report:
    
      https://bugzilla.kernel.org/show_bug.cgi?id=208439
    
    The list generation has been intended to be fully self-defined
    since 2.23, but I didn't complete the job back then because of
    a lack of a way to runtime-determine the capabilities actually
    supported by the running kernel.  This last bit was fixed with
    2.30 and I should have caught the need for this final clean up
    then.
    
    The go install was broken in 2.37 as a oversight as I refactored
    to support go modules. I did a write up about how this Go
    support is expected to work here:
    
      https://sites.google.com/site/fullycapable/building-go-programs-that-manipulate-capabilities
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - Documentation fixes for go packages.
    
    Also converted an internal type from int to uint. This change should
    not affect any client code.
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - Restructure the tree a little to provide a module example.
    
    I've written up how to build web.go here:
    
      https://sites.google.com/site/fullycapable/building-go-programs-that-manipulate-capabilities
    
    But it struc me that the code itself does not explain about the
    CGO_LDFLAGS_ALLOW workaround, so I've relocated the web.go code
    and included a README as well as a pointer to the above explanation.
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - A final twist in the Go module support.
    
    It turns out that the Go module abstraction needs a tag specific to
    each sub-package, and can't share a generic one for libcap as a whole
    for both Go modules. As such, replace the vX.Y.Z tag with two
    package/vX.Y.Z tags.
    
    Signed-off-by: Andrew G Morgan <morgan@kernel.org>
    
  - Up the release version to 2.37
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - Create symlink for including psx_syscall.h
    
    The primary path for this header is now in the Go package psx, but we
    still need to link it via libcap/include.
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - Migrate header for psx_syscall.h to Go package tree.
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - Refactored the psx package to build as a Go module.
    
    Cleaned up the Go module redirection html file, now installed
    at:
    
      https://kernel.org/pub/linux/libs/security/libcap/
    
    Note, I've moved the C source for libpsx.a into the psx/
    directory, but the libpsx.a file is still built in the libcap
    subdirectory as before. I also symlinked the C include files from
    the psx/ directory. This made the source compile in conjuction
    with the "psx" Go package automatically. It also substantially
    simplified the go/Makefile.
    
    I feel pretty good about this next version from the perspective
    of a viable "psx" build. Caveat the need for CGO_LDFLAGS_ALLOW
    on the command line pre-go1.15. Hopefully, the psx package comment
    is enough for folk to figure that detail out.
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - A step closer to modularizing the cap and psx packages.
    
    After reading more about Go modules, I now see how ownership of the
    stable URL path for the packages is required. As such, I'm changing
    the official package paths to these:
    
      "kernel.org/pub/linux/libs/security/libcap/cap"
      "kernel.org/pub/linux/libs/security/libcap/psx"
    
    I have the right permissions to maintain these directories. I will
    place the libcap/{cap,psx}/index.html files at those locations and
    then validate that the go getting magic does the right things.
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - Revamp the way we package cap and psx packages.
    
    It has been requested that we make the "libcap/cap" package into
    a module that plays better with the golang ecosystem. I was holding
    off until there was a golang version that contained the
    runtime.AllThreadsSyscall() support, but that appears to not have
    made it to 1.15, so I'm using a development build tag dependency
    in otherwise static sources for the "libcap/cap" package.
    
    My intention is that the canonical import paths for these packages
    will be:
    
       "git.kernel.org/libs/libcap/cap"
       "git.kernel.org/libs/libcap/psx"
    
    That being said, I may have to move them if I can't get some
    proxy to resolve these paths to the right git repo of kernel.org.
    
    The is work in the direction of addressing:
    
       https://bugzilla.kernel.org/show_bug.cgi?id=207567
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - First attempt at supporting the Go "psx" package as a module.
    
    The intended import path for this module is:
    
       "git.kernel.org/libs/libcap/psx"
    
    This is my first attempt at such module support, so it will
    likely require some iteration.
    
    This is work in the direction of addressing:
    
       https://bugzilla.kernel.org/show_bug.cgi?id=207567
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - CAP_BPF is the CAP_LAST_CAP now.
    
    eBPF (extended Berkeley Packet Filters) now have their own capability.
    Earlier releases of the kernel used CAP_SYS_ADMIN for this feature.
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - Tidy up the comment related to the XATTR backup definitions.
    
    We generally try not to use C++ style line comments.
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - libcap: Fix for older kernels
    
    cap_file.c:204:33: error: 'XATTR_NAME_CAPS' undeclared (first use in
    this function)
      sizeofcaps = fgetxattr(fildes, XATTR_NAME_CAPS,
    
    Kernels after 2.6.36 moved the declarations to userapi,
    Hope this can be defined manually
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - Fix declaration of mostly never compiled code.
    
    The cap_set_nsowner() function, on systems where VFS_CAP_U32
    is not defined. Bug report from Prasanth R.
    
      https://bugzilla.kernel.org/show_bug.cgi?id=208365
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - cap_get_proc.3: change "current process" to "calling process"
    
    The term "current process" is kernel-developer speak that is often not
    understood by user-space programmers. Change to "calling process",
    which is clearer.
    
    Signed-off-by: Michael Kerrisk (man-pages) <mtk.manpages@gmail.com>
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - Improve synopsis formatting of getpcaps.8 man page.
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - getpcaps.8: Note that pid==0 displays capabilities of getpcaps itself
    
    When experimenting with capabilities, it's useful to know that
    pid==0 causes getpcaps to display its own capabilities.
    
    Signed-off-by: Michael Kerrisk (man-pages) <mtk.manpages@gmail.com>
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - cap_get_proc.3: for cap_get_pid(), pid==0 means "the calling process"
    
    It's useful to know that when cap_get_pid() gets pid==0,
    it returns the caller's capabilities.
    
    Signed-off-by: Michael Kerrisk (man-pages) <mtk.manpages@gmail.com>
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - cap_get_proc.3: Typo fixes
    
    Signed-off-by: Michael Kerrisk (man-pages) <mtk.manpages@gmail.com>
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - Better protect some header #define's.
    
    Apparently some folk like to supply these defines on the compiler
    command line. Protect these defines with some more macrology.
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
    
  - Clean up an unused variable.
    
    Signed-off-by: Andrew G. Morgan <morgan@kernel.org>