Update git submodules
* Update packages/modules/Gki from branch 'master'
  to e93732c02baea5b03549cb53802e3134b0526e46
  - GkiInstallTest: Always initialize mOverlayfs var.
    
    If assumption fails and mOverlayfs was not initialized, the
    test tearDown() method failed with the following error:
    
    java.lang.AssertionError: Some partitions did not restore
    overlayfs properly. Before test: null, after test: []
    
    ... This is because mOverlayfs is null. Always initalize
    mOverlayfs variable so that we are not comparing null to
    an empty set.
    
    Test: atest
    Bug: 174126387
    Change-Id: I3d70dfba451a970a0b8b6e8ddd96f2d6e8d85ab7