Update git submodules
* Update external/fmtlib from branch 'master'
  to a57248685e84ab1fc551f121991a39f3615c584f
  - Upgrade fmtlib to 7.0.1
    
    Change-Id: I366440880f4d3889f4e941db424dbc2e47a09a3e
    
  - Update version
    
  - Fix a changelog entry
    
  - Fix undefined reference error
    
  - Merge release branch
    
  - Fix date
    
  - Bump version
    
  - Workaround a bug in gcc
    
  - Fix docs
    
  - Bump version in namespace
    
  - Fix the docs
    
  - Update version
    
  - Update version
    
  - Minor corrections in the changelog
    
  - Bump version
    
  - Update docs
    
  - Add a section on std::format compatibility
    
  - Update README.rst
  - Update changelog
    
  - Update changelog
    
  - Revert changelog changes
    
  - Add ClickHouse to the list of projects (#1751)
    
    
  - Revert changelog conversion since GFM is not supported there
    
  - Update changelog
    
  - Convert changlog to markdown
    
  - Rename changelog
    
  - Update ChangeLog.rst
  - Update README.rst
  - Update changelog
    
  - Update changelog
    
  - Update readme
    
  - Update README.rst
  - Update changelog and readme
    
  - Deprecate arg_formatter
    
  - Update changelog
    
  - Update changelog
    
  - Disable numeric formatting by default
    
  - Update changelog
    
  - Fix formatting
    
  - Update changelog
    
  - FMT_NUMERIC_ALIGN -> FMT_DEPRECATED_NUMERIC_ALIGN
    
  - Make the n specifier an opt-in
    
  - Fix a conversion warning with Clang10 on Windows (#1750)
    
    Fixes #1747
  - Fix a typo. Thanks Tracy Chapman from TripleChecker
    
  - Fix a typo
    
  - Fix possible infinite recursion in FMT_ASSERT (#1744)
    
    Use std::fprintf for assertion message output preventing infinite
    recursion when output to stderr is limited or broken.
  - Use consistent include style
  - Add a simple buffered stream with no sync
    
  - Use digit pairs as in unrolledlut
    
  - Update changelog
    
  - Update changelog
    
  - Update changelog and disable internal
    
  - Don't use non-portable attribute
    
  - Tweak the docs
    
  - Extract docs from compile.h
    
  - Apply clang-format
    
  - Document format string compilation
    
  - Spelling fixes
  - Update README.rst
  - Spelling fixes
  - Spelling fixes
  - Fix a compile error introduced in #1738
    
  - Deprecate compile
    
  - Add user-defined type support to compilation
    
  - Tweaks for EDG based compilers (Intel, nVidia, MCST/Elbrus, etc).
    
    Using the __EDG_VERSION__ macro for checks related to EDG-based
    compilers instead of a macros specific for each of ones.
    
  - Do not use -Wl,--as-needed with emscripten.
    
    On some platform, fmt is using the following link flag:
    ```cmake
      target_link_libraries(fmt -Wl,--as-needed)
    ```
    
    This is not supported by wasm-ld as of today.
    This patch stop using it when compiling using emscripten.
    
    Bug: https://github.com/fmtlib/fmt/issues/1736
    
  - Reintroduce UDT support to fmt::to_string and test ADL
    
  - Add FMT_COMPILE support to format_to
    
  - Streamline default FP formatting
    
  - Update README.rst
  - Added  #define WIN32_LEAN_AND_MEAN before including windows.h (#1729)
    
    Co-authored-by: gabime <gmelman1@mgail.com>
  - Optimize common case
    
  - Make to_string bypass format
    
  - Inline compiled format
    
  - Finish text::format
    
  - Re-enable assert in format_decimal
    
  - Fix ambiguity
    
  - Reuse format_decimal
    
  - Fix formatting of bool with FMT_COMPILE and add more tests
    
  - Use write instead of format_int in to_string
    
  - Undo branching reduction
    
  - Undo branching reduction
    
  - Fix sign handling in 'L'
    
  - Reduce branching
    
  - Optimize small string parsing
    
  - Fix a warning
    
  - Enable compilation for all types
    
  - Add a simple format string compilation API
    
  - Tweak comments
    
  - Move project in order to solve a CMake warning 
    
    CMake Warning (dev) at /usr/share/cmake-3.17/Modules/GNUInstallDirs.cmake:225 (message):
      Unable to determine default CMAKE_INSTALL_LIBDIR directory because no
      target architecture is known.  Please enable at least one language before
      including GNUInstallDirs.
  - Update README.rst
  - Fix a warning (#1722)
    
  - c++11 use formatting user-defined types (#1721)
    
    
  - Update README.rst
  - Update README.rst
  - Improve default formatting
    
  - MINGW cross compiler fixes
    
  - Add default_arg_formatter
    
  - Fix a UB
    
  - Cleanup arg_formatter_base
    
  - Simplify arg_formatter_base
    
  - Inline visitor
    
  - Make symbols readable
    
  - Make advance_to a noop for back_insert_iterator
    
  - Optimize format string parsing
    
  - Inline visit
    
  - Optimize format string parsing
    
  - Optimize format handler
    
  - Move format_handler to detail
    
  - Fix a warning (#1712)
    
  - fix typo which caused the loss of the counting information when using a printf context with a truncating_iterator
    
  - Fix warnings
    
  - Move digits10 to where they belong and add comments
    
  - Fix a warning
    
  - Ignore /doc/node_modules directory
    
  - Cleanup arg_formatter_base
    
  - Fix format_decimal overloads
    
  - Inline parse_format_string
    
  - Remove undocumented buffer_range and output_range
    
  - Increase VM disk size
    
  - Remove uses of buffer_range
    
  - Don't install sphinx cache files
    
    When building documentation sphinx creates cached files in the .doctrees
    directory and aren't required for viewing documentation only for
    building. As added benefit this makes fmt reprodcubile as the cached
    files are different when the build environment is varied.
    
  - Remove uses of buffer_range
    
  - Simplify copy_str
    
  - Simplify arg_formatter
    
  - Simplify arg_formatter_base
    
  - Improve handling of separators
    
  - Reduce the number of comparisons
    
  - Use memcpy for copying digits
    
  - Support custom FMT_INC_DIR in pkgconfig and cmake configs (#1702)
    
    * Support custom FMT_INC_DIR in pkgconfig and cmake configs
    
    When CMAKE_INSTALL_INCLUDEDIR or FMT_INC_DIR override the header
    installation directory, they should be used instead of
    ${CMAKE_INSTALL_PREFIX}/include in fmt-targets.cmake and fmt.pc.
    
    * Put headers into FMT_INC_DIR/fmt rather than directly into FMT_INC_DIR
    
    This makes FMT_INC_DIR an alias for CMAKE_INSTALL_INCLUDEDIR and
    simplifies generation of pkgconfig and cmake configs.
    
    * Do not split target_include_directories
  - Fix Mingw support
    
    If the ``_POSIX_`` flag is set, _fdopen will not be defined by
    Mingw headers, which is addressed by this commit.
    
    For what is worth, as opposed to ``fdopen``, ``_pipe`` *will*
    actually have the ``_`` prefix when ``_POSIX_`` is set.
    
  - Optimize common case
    
  - Update README.rst
  - fix zero flag for char types and make zero flag ignored if a precision is specified
    
  - Temporarily revert parsing changes
    
  - Remove a redundant branch
    
  - fix max/min macro (#1697)
    
    
  - Fix an example (thanks Alexey Kuzmenko)
    
  - Make ostream formatter work with compile-time format strings (#1692)
    
  - Update README.rst
  - Knuth is using fmt library (#1691)
    
    
  - Optimize small string parsing
    
  - Optimize small string concatenation
    
  - Move void_t to where it's used
    
  - Update analytics
    
  - Adding sentinel support to fmt::join(). (#1689)
    
    
  - Add c specifier support to integral types (#1652)
    
  - fix interaction of space flag and '+' flag, as well as '-' flag and '0' flag (#1687)
    
    
  - Update signatures
    
  - Add fmt::detail::buffer to the docs (#704)
    
  - Fix apidoc
    
  - Merge branch 'master' of github.com:fmtlib/fmt
    
  - Update docs
    
  - make plus flag for printf not be ignored for char argument (#1683)
    
    * make plus flag for printf not be ignored for char argument
    
    * clarify overwriting of alignment specifiers for printf with char argument
  - Apply doc patch to 6.2.1
    
  - nested replacement fields may omit arg_id (#1681)
    
    syntax.html already has examples like `fmt::format("{:.{}f}", 3.14, 1)` using this, 
    and https://en.cppreference.com/w/cpp/utility/format/formatter#width_and_precision shows that this is the case for the C++20 std::format
    
    The Format Specification Mini-Language grammar seems to be the only one not showing this; update it to match.
  - Make dynamic_format_arg_store reusable and add reserve() (#1677)
    
    Implemented #1674: make dynamic_format_arg_store reusable and add
    reserve() for better memory menagement.
  - Update version
    
  - internal -> detail (#1538)
    
  - Simplify named arguments
    
  - Named arguments go brrr
    
  - Ditch internal::arg_map
    
  - Bump version
    
  - Make implicit capture explicit for C++20 (#1669)
    
    
  - Update changelog
    
  - Update changelog
    
  - Support named args in dynamic_format_arg_store (#1655). (#1663)
    
    Dynamic arguments storage. Implementation of enhancement from issue
    #1170.
  - Consistently namespace qualify size_t
    
  - Purge basic_writer
    
  - Purge basic_writer
    
  - Revert enum change
    
  - Fix some warnings (#1667)
    
    * Fix sign-conversion warning
    
    * Add missing "extern template" declarations for non-header-only build
    
    * Use typed enums to fix Wsigned-enum-bitfield warnings
    
    * Consolidate FMT_HEADER_ONLY code
  - Purge basic_writer
    
  - Make copyfmt not throw (#1666)
    
  - Remove compatibility stubs
    
  - Separate nonfinite formatting
    
  - Remove deprecated APIs
    
  - Move FMT_MAYBE_UNUSED to where it's actually used
    
  - Fix inconsistent type detection (#1662)
    
  - Exclude std::abort from compilation when compiling CUDA with Clang (#1661)
    
    
  - Inherit arg_formatter_base from basic_writer
    
  - Refactor pointer formatting
    
  - Move int_writer to the namespace scope
    
  - Improve handling of alignment
    
  - Improve handling of alignment
    
  - Use '0' fill with numeric align for consistency with std::format
    
  - Suppress ubsan warning
    
  - Cleanup
    
  - Remove undocumented deprecated APIs
    
  - Simplify vformat_to
    
  - FMT_CONSTEXPR -> constexpr
    
  - Update date formatting example to use threadsafe localtime
    
  - Reduce library size
    
  - Update README.rst
  - Update README.rst
  - build: Fix installation paths
    
    It is not generally true that `CMAKE_INSTALL_<dir>` variables are relative paths:
    
    https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files
    
  - Reduce template bloat in write_int
    
  - Fix a shadowing warning (#1658)
    
  - Allow to avoid inclusion of os.cc in fmt target
    
    - Allows to avoid part of #1654
    - Not possible to use with MASTER_PROJECT as testing uses it a lot
    
  - Pass iterator by value
    
  - Make write_padded non-members
    
  - Bump fuzzer allocation limit
    
  - Reduce branching in write_padded
    
  - Reduce library size
    
  - Replace FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION  with fmt-specific macro (#1650)
    
    Signed-off-by: Asra Ali <asraa@google.com>
  - Fix a warning (#1649)
    
  - Reduce library size
    
  - Reduce library size
    
  - Clarify encoding conversion in chrono
    
  - Improve compile time by using extern template (#1452)
    
  - Clarify why we don't check argument id
    
  - Check dynamic width/precision id at compile time (#1614)
    
  - Revert "Check dynamic widht/precision id at compile time (#1614)"
    
    This reverts commit 7d748a6f826a14d44b7fe5007b37461d5dbb78fd.
    
  - Don't access a C string past precision in printf (#1595)
    
  - Check dynamic widht/precision id at compile time (#1614)
    
  - Get rid of do_check_format_string
    
  - Simplify udl_formatter with FMT_STRING
    
  - Enable compile-time error tests
    
  - Fix markup
    
  - Clarify formatter reuse
    
  - Suppress bogus MSVC analysis warnings
    
  - Fix a recent regression in handling max packed arguments
    
  - Add Facebook Folly to the list of projects
    
  - Tweak readme
    
  - Improve readme formatting
    
  - README: add vectorized.io/redpanda in the list of users
    
  - Add windows terminal to the projects using {fmt}
  - Use a delegating ctor and add inlines
    
  - Remove remaining wchar_t instantiation
    
  - Don't generate RTTI for allocator
    
  - Fix build on ancient gcc
    
  - Simplify format_args
    
  - Always inline arg_data functions
    
  - Always inline value ctors
    
  - Simplify checks
    
  - Fix incorrect assumptions about nul termination
    
  - Reenable constexpr _compile on GCC 9
    
  - Don't use constexpr on Intel compiler (#1628)
    
  - Merge arg overloads and cleanup
    
  - Remove warning in core.h with when compiling with gcc and -Wshadow
    
    In file included from build/_deps/fmt-src/include/fmt/format.h:44:0,
                     from src/main.cpp:5:
    build/_deps/fmt-src/include/fmt/core.h: In member function ‘const T& fmt::v6::internal::dynamic_arg_list::push(const Arg&)’:
    build/_deps/fmt-src/include/fmt/core.h:1256:10: error: declaration of ‘node’ shadows a member of ‘fmt::v6::internal::dynamic_arg_list’ [-Werror=shadow]
         auto node = std::unique_ptr<typed_node<T>>(new typed_node<T>(arg));
              ^~~~
    build/_deps/fmt-src/include/fmt/core.h:1236:37: note: shadowed declaration is here
       template <typename = void> struct node {
    
  - Remove warning in format.h when compiling with gcc and -Wshadow
    
    build/_deps/fmt-src/include/fmt/format.h: In member function ‘decltype (ctx.out()) fmt::v6::formatter<fmt::v6::bytes>::format(fmt::v6::bytes, FormatContext&)’:
    build/_deps/fmt-src/include/fmt/format.h:3251:58: error: declaration of ‘writer’ shadows a global declaration [-Werror=shadow]
         internal::basic_writer<range_type> writer(range_type(ctx.out()));
                                                              ^~~
    build/_deps/fmt-src/include/fmt/format.h:2741:53: note: shadowed declaration is here
     using writer FMT_DEPRECATED_ALIAS = internal::writer;
    
  - Cleanup named arguments
    
  - Improve handling of named arguments
    
  - Add check for CompiledFormat to avoid ambiguous call
    
  - Add stack-based named argument storage
    
  - Fix a clang-tidy warning
    
  - Fix a typo
    
  - Fix ostream support in sprintf (#1631)
    
  - Fixed clang tidy warning -multiple declarations in a single statement reduces readability
    
  - Fix clang warning about explicit ctor
    
  - Clean up basic_format_args
    
  - Clean up printf
    
  - Suppress an MSVC warning (#1622)
    
  - Simplify warning suppression
    
  - Add floating-point L specifier (#1624)
    
  - Suppress a bogus MSVC warning
    
  - Define FMT_EXTERN_TEMPLATE_API on export
    
  - Bump version
    
  - Fix handling of unsigned char strings in printf
    
  - Merge branch 'master' of github.com:fmtlib/fmt
    
  - Fix the docs
    
  - Avoid windows issue with min() max() macros
    
    Including the ``windows.h`` file without defining ``NOMINMAX`` will define the `min()` and `max()` macros which will result in issues compiling any C++ code that uses any variant of `max`, for example `std::numeric_limits<std::streamsize>::max()` and many others.  Although max() isn't used in Fmt anywhere, it is often used in codes that include a format include file so simply upgrading to the current version of lib::fmt will break the windows build which worked prior to the update...
  - Update signature in the docs