Update git submodules
* Update tools/asuite from branch 'master'
  to 57463d6fbfb69e32d98802234f1f4a5caaac60f8
  - Atest: ensure subprocess generate str.
    
    This CL is to avoid 'TypeError: can only concatenate str (not "bytes")
     to str' from happening since the in python3 the default output in in
    byte.
    
    1. Decode check_output() when returning bytes.
    2. Decode socket_data when it's bytes.
    3. Replace typo datas with data_map.
    
    Bug: 144892734
    Bug: 144881266
    Bug: 144960829
    
    Test: ./atest.py hello_world_test -v
      ./atest.py native-benchmark -v
      ./atest_integration_tests.py -cy (fail for now, not error)
    Change-Id: Id6da7ecb2fd66fb93419b306e75012cd085a88df
    
  - Atest: resolve 'function' object has no attribute 'im_class'.
    
    Bug: 144820145
    
    Test: None
    Change-Id: I9bece98728b91b5badfe664be094d0c18b6da0c9