Minor refactoring to allow building model as a separate library
Previously, when attempting to build the model package as a separate
library compilation failed with:

```
tools/metalava/src/main/java/com/android/tools/metalava/Reporter.kt:235:49: error: smart cast to 'Path' is impossible, because 'path' is a public API property declared in different module
```

This change fixes that error by using `?.let` to avoid the smart cast.

Bug: 287241408
Test: ./gradlew
Change-Id: I714ce597f17955456dc8c8fd48873f48e5d70e86