Update git submodules
* Update external/android-clat from branch 'master'
  to df338699853d02d2a562b9a88beab6f34ced5f83
  - Fix some build errors when CLAT_DEBUG is set to 1
    
    After seteing CLAT_DEBUG to 1 to enable debug logging,
    there were some build errors, as shown below:
    
    external/android-clat/dump.c:205:6: error: conflicting types for 'dump_tcp'
    external/android-clat/dump.c:214:6: error: conflicting types for 'dump_tcp6'
    external/android-clat/dump.c:229:30: error:
    invalid application of 'sizeof' to an incomplete type 'struct tun_pi'
      for (i = 0; i < len && i < PACKETLEN; i++) {
                                 ^~~~~~~~~
    
    Bug: 171277941
    Test: builds and boots
    Test: connect to ipv6-only wifi network: ping 8.8.8.8 still works
    Change-Id: Ifb5d84951c4832ae4e3eb8a24329df0243f6ee55