Update git submodules
* Update external/python/asn1crypto from branch 'master'
  to 2b20719855546eec025b0433f144d8780850ebd1
  - Upgrade python/asn1crypto to 1.4.0
    
    Test: make
    Change-Id: I91c1d9e084d4804e09aa5d686816dba41512357e
    
  - Version 1.4.0
    
  - Fix keys.PublicKeyInfo.bit_size tests on Python 2.6
    
  - Ensure keys.PublicKeyInfo.bit_size returns an int
    
  - Tweak error messages on invalid OIDs
    
  - Merge pull request #174 from joernheissler/oid-arc-2
    
    Fix parsing of ObjectIdentifier's first octet.
  - Fix PyPy on CircleCI
    
  - Merge pull request #188 from daxtens/travis-ppc64le
    
    Add ppc64le jobs to Travis CI
  - Add ppc64le jobs to Travis CI
    
    As with ARM64, Travis CI supports ppc64le ("Power") now.
    
    I've just mimicked the job that ARM64 does, I think that provides
    decent coverage without bloating the test matrix too much. (We could
    also test pypy on Power, but I don't think it gets us too much extra
    value.)
    
  - Disable uploading coverage reports to codecov since it is a constant thorn in my side
    
  - Fix an issue with asn1crypto_tests when running egg_info from sdist
    
  - Merge pull request #181 from hroncok/patch-1
    
    Fix a syntax typo
  - Fix a syntax typo
    
    
    This worked for now, but is SyntaxError in Python 3.9.0a6:
    
      File "/usr/lib/python3.9/site-packages/asn1crypto/x509.py", line 1139
        return', '.join(
             ^
    SyntaxError: invalid string prefix
    
    (The Python change might actually be reverted before 3.9 final, but this can be fixed anyway.)
  - Run GitHub actions on pull requests
    
  - Update deps task to filter by python_version and requires_python
    
  - Fix parsing of ObjectIdentifier's first octet.
    
    X.660 §7.6 specifies that the first arc of an OID must be 0 to 2 and
    the second arc below arcs 0 and 1 must be 0 to 39. Arc 2 is not
    restricted in that way.
    
    The algorithm for parsing ObjectIdentifiers did not work for
    OID 2.X with X >= 40.
    
    This change also enforces above restrictions when setting an
    ObjectIdentifier.