Update git submodules
* Update build/soong from branch 'master'
  to d3cd2f5793ae81a09fd7d30f622080aa1695081a
  - Merge "Repeat metalava errors at the end to make it easy to find them"
  - Repeat metalava errors at the end to make it easy to find them
    
    Also suppress "unresolved import" messages.
    
    Bug: 161374683
    Test: Introduce a lint error, run "m update-api" and make sure the
        error shows up at the end.
    Change-Id: Ib5250f7f9593dc4f89f9e7f6dc614e230a966e8f
    

* Update tools/metalava from branch 'master'
  to 83c745c5d2a8e1d570de9b9cd321322a43dae7e6
  - Make clear why metalava failed.
    
    - Repeat all the errors from the reporter at the end.
    - When metalava failed due to an exception or sandbox violation, show
    An "Error:" or "Aborting: " prefix to make clear that's the failure reason.
    
    - Also, fix a bug where metalava didn't fail when there's a sandbox
    violation when running with --strict-input-files:stack
    
    Bug: 161374683
    Test: JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/ ./gradlew
    Test: Introduce a lint error, run "m update-api" and make sure the
        error shows up at the end.
    Change-Id: I963e57b31e69bbf4c1ffdc12ee3911d7dd5d8469