Update git submodules
* Update tools/repohooks from branch 'android11-gsi'
  to dfe6ed518d4c8acf11cbd63150d4848cfa4f01ea
  - Snap for 6948038 from 89b9c5960a0723e769e323edd7b123a956a8dee0 to rvc-platform-release am: a1696e0353
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/tools/repohooks/+/12979325
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ib74bb9b8c668b40097578f0aac3f5be824b3f6ae
    
  - Snap for 6948038 from 89b9c5960a0723e769e323edd7b123a956a8dee0 to rvc-platform-release
    
    Change-Id: I2c294e301577b95abfea30b44cf3fd4e21f57b55
    
  - Merge branch 'rvc-qpr1-release' into rvc-platform-merge
    
    Change-Id: Ic6fa726ff97d1692e1e2fded19eb68f68dbabadc
    
  - Snap for 6844997 from eb433868757764e154d396d3627417747db9a743 to rvc-qpr1-release
    
    Change-Id: I268414873fc550ed34e1ccc4e469d39980daa44e
    
  - hooks: support Python 3.6 for ExclusionScope am: 573d316aa2
    
    Original change: https://android-review.googlesource.com/c/platform/tools/repohooks/+/1428528
    
    Change-Id: Ie5f6a45ff10bffed2d6e1a2da1115cb2a8202c3a
    
  - hooks: support Python 3.6 for ExclusionScope
    
    re.Pattern was only introduced in Python 3.7.
    
    Test: ./pre-upload
    Bug: 168593718
    Change-Id: I9dc685a8d1863808d9c475539a8f1fdbd96474d0
    
  - Snap for 6823548 from 9fed6d949cc19977ea51abd67579702cc59244da to rvc-qpr1-release
    
    Change-Id: I842e0670e4c1329bcf3f5281a1cdece989beb13e
    
  - tools: switch all our tools to python3 shebang am: 5be91ca1c2
    
    Original change: https://android-review.googlesource.com/c/platform/tools/repohooks/+/1422908
    
    Change-Id: I92a7234bfbfd5076856a51ccca953aa6889c4611
    
  - tools: switch all our tools to python3 shebang
    
    We did this for pylint already, so switch the rest too.
    
    Bug: None
    Test: running each tool with --help works
    Change-Id: I0c6156cbcfabf2ebb7874cbb8a52059b1a88dfcc
    
  - Snap for 6820514 from 09cc9a71c6836e421a6d40f4df52d2ce5a66a496 to rvc-qpr1-release
    
    Change-Id: I3c420cf21ca7ff639b81746b151171d1e00286df
    
  - Add [Builtin Hooks Exclude Paths] section am: ea52820de8
    
    Original change: https://android-review.googlesource.com/c/platform/tools/repohooks/+/1395027
    
    Change-Id: Ia33c2a2caf6d02259fb3b393157a08d7e5e64a3f
    
  - Snap for 6809626 from 5e2fb9aa23ecc7265773ee69a0d20830f52b81c9 to rvc-qpr1-release
    
    Change-Id: Ie50db83143ec7d98427c869aec2a6a990fab3039
    
  - Add [Builtin Hooks Exclude Paths] section
    
    There is currently no convenient option to enable a hook globally if
    some projects will fail the processing. The recommended setup is to
    enable the hook within each project's repository (using PREUPLOAD.cfg).
    This creates inconsistencies for large codebase. Adds a new
    configuration section to explicitly exclude some projects during the
    processing of a hook.
    
    The intent of this change is to enable rustfmt globally in AOSP,
    except for some paths (e.g. external/, vendor/).
    
    Test: Modified GLOBAL-PREUPLOAD.cfg to enable the new option,
      manually creates changes and review output of pre-upload.py
    Bug: 160223496
    Change-Id: I94dbbf0ce2e6b58c4d4b4fc89c56a2a87543d878
    
  - drop python2 testing entirely am: ec4cdcbeee
    
    Original change: https://android-review.googlesource.com/c/platform/tools/repohooks/+/1417624
    
    Change-Id: I80c4a873c4e87b9936104d94e6723a72b3649341
    
  - drop python2 testing entirely
    
    No point in linting or testing when the code forces Python 3.6+.
    
    Bug: None
    Test: `repo upload` still works
    Change-Id: I5af19b5dc70be3f5be99157d1fc4287e4437c553
    
  - Snap for 6806651 from 615f08ee34ad7db309ed6a19124010a78c86cc08 to rvc-qpr1-release
    
    Change-Id: Ib9f0a0534d155cb2391f07d0fd6637c1baf8d4ef
    
  - config: refactor PreUploadSettingsTests am: 324296b110
    
    Original change: https://android-review.googlesource.com/c/platform/tools/repohooks/+/1413981
    
    Change-Id: I929668c32fb13fa260cd12562f00b026fdff3d52
    
  - config: add {Local,Global}PreUploadFile classes am: c9ba009aab
    
    Original change: https://android-review.googlesource.com/c/platform/tools/repohooks/+/1413980
    
    Change-Id: Ie264829e1cbf047d0bc6af3cc021d42f4a304dc4
    
  - config: refactor PreUploadSettingsTests
    
    PreUploadFileTests and PreUploadSettingsTests share the same setup and
    teardown for writing configuration files. Extract that behaviour into a
    new class (FileTestsBase).
    
    Test: pre-upload.py
    Bug: 160223496
    Change-Id: I8b572cdb0f43ae4557323a43a69e66ead67d87fe
    
  - config: add {Local,Global}PreUploadFile classes
    
    Creates 2 new classes to differentiate local (PREUPLOAD.cfg) and global
    (GLOBAL-PREUPLOAD.cfg) files. While not useful yet, this allows to
    implement validation that is specific to local files.
    
    Ideally, PreUploadFile would be declared as @abstractclass but the
    support for py2/py3 makes this constraint tedious to implement.
    
    Test: pre-upload.py
    Bug: 160223496
    Change-Id: I75e0e644f713002f1ba50a405965362c1c5a7589
    
  - Snap for 6803753 from 24a38ce5e7368039d36fc39f5c39468396974e2c to rvc-qpr1-release
    
    Change-Id: Ib95b039ef94b9990b66f98878286ecb6fa288939
    
  - pre-upload: drop support for Python 2 am: 7698778fb0
    
    Original change: https://android-review.googlesource.com/c/platform/tools/repohooks/+/1373921
    
    Change-Id: I2f0e1d3939e10be0763b24ecc0b14118c1be048e
    
  - pre-upload: drop support for Python 2
    
    Repo itself has been warning about Python 2 support for over a year,
    while pre-uplooad has been warning for about a month.
    
    We don't actually rip out any code (yet) to make sure this sticks in
    case we have to revert things temporarily.
    
    Bug: None
    Test: `repo upload` still works w/Python 3.6
    Change-Id: Ia00bc3c9a59b0e6828df2691f47c6da94adb8038
    
  - Snap for 6799200 from 0569f18a26d4831ee75827b379fe90c3df9de097 to rvc-qpr1-release
    
    Change-Id: I5c9b67492e892f283d8727e9c53ba2a721f42580
    
  - config: refactor file management am: 1baec120bf
    
    Original change: https://android-review.googlesource.com/c/platform/tools/repohooks/+/1409412
    
    Change-Id: Id7ed769c4436ae3d316ad046d1c181fd316f60b3
    
  - config: refactor file management
    
    The existing config management started out with just one file, but
    has grown to load & merge from multiple sources.  Refactor classes
    to better reflect this: one class to represent a single file, and
    another to represent the union of them all.
    
    By itself, this isn't interesting.  But it lays the groundwork to
    be able to load config files from subdirs instead of only one file
    per project.
    
    Bug: 160223496
    Test: Unittests pass
    Change-Id: I522b18fa8bc31f787c92cf95db7da4168007915e
    
  - Snap for 6793271 from 425db52f349d233f4501180c8949bd6ba9f20b92 to rvc-qpr1-release
    
    Change-Id: I9275edd88ead4ba3c5aadf5860157d12e5d34212
    
  - config: add Python 3 compat APIs am: 41a1fd1aac
    
    Original change: https://android-review.googlesource.com/c/platform/tools/repohooks/+/1409411
    
    Change-Id: I20b225c3916994aabf677b5fdc86c5f5dbdae60f
    
  - Snap for 6790172 from fd6d0e0b33455142503a39741c486ff26c6ba232 to rvc-qpr1-release
    
    Change-Id: Ie60f3db6098d4926d7febcfd6ba2439527760844
    
  - config: fix handling of optional args am: 0d0796a3ea
    
    Original change: https://android-review.googlesource.com/c/platform/tools/repohooks/+/1409410
    
    Change-Id: Ie20fc9502b2683e80f3f172255a4275c2131cfbf
    
  - config: pull valid sections into a class constant am: 3798d7e067
    
    Original change: https://android-review.googlesource.com/c/platform/tools/repohooks/+/1409409
    
    Change-Id: I17090f93848c0aaf47245df5a53ca3ce6aefc351
    
  - config: add Python 3 compat APIs
    
    Extend the items API to be like Python 3 with an optional |section|,
    and add a read_dict API for Python 2 that matches Python 3.  We'll
    use both of these in the next commit.
    
    Bug: 160223496
    Test: Unittests pass
    Change-Id: I2b9cb987ae25f852f86427dccb18e10fe80a35da
    
  - config: fix handling of optional args
    
    The current logic only works for a single optional arg, and the counts
    are off by one atm (for reporting).  Rework the logic to simplify and
    so a follow up change is easier to extend.
    
    Bug: 160223496
    Test: Unittests pass
    Change-Id: Ibcb9e159486620c9e69312ed47ba9063cf2477b9
    
  - config: pull valid sections into a class constant
    
    This matches the VALID_OPTIONS style, and will make follow up
    refactors easier.
    
    Bug: 160223496
    Test: Unittests pass
    Change-Id: I161e4b714a6faa3432588306e50ef02ab30763a2
    
  - Snap for 6777077 from a4350d0cc24b53d77b2cea9b8a9a2e2ff9e828f7 to rvc-qpr1-release
    
    Change-Id: I6dd6316b1bb43792e07828e3f21c606fd70f90d5
    
  - hooks: rustfmt: handle multiple commits am: f773756405
    
    Original change: https://android-review.googlesource.com/c/platform/tools/repohooks/+/1399689
    
    Change-Id: Ib0b684b692726004efd8859569e3a3f513078498
    
  - hooks: rustfmt: handle multiple commits
    
    The rustfmt hook was relying on ${PREUPLOAD_FILES} which is only correct
    when evaluating HEAD. Update the hook to parse the correct version of
    the file.
    
    Before 2.0, rustfmt does not support --check when passing the source via
    stdin. Handle this case by comparing the input with the output and
    report a command to fix the issue to the user.
    
    Bug: 164111102
    Test: Added multiples changes to system/security (typo and incorrect
      indentation). Run pre-upload.py manually.
    Change-Id: Ibd1bfcb9e630f0b21abfb1e1feb1248fcddf2236
    
  - Snap for 6766785 from 4e726de5b66ba3d23cf4e51c244ced972236e380 to rvc-qpr1-release
    
    Change-Id: I428b93365c2508237b6df20d154720174411e1bc
    
  - hooks: use dedicated None asserts am: 8ee0f2a826
    
    Original change: https://android-review.googlesource.com/c/platform/tools/repohooks/+/1401348
    
    Change-Id: I5f8d55c2c1cdcca60971fa8d6acc5164b2c10fdb
    
  - hooks: use dedicated None asserts
    
    These provide better diagnostics & checking than Equal.
    
    Bug: None
    Test: unittests still pass
    Change-Id: I0c34bc1dae6d32fa58cfe0c45414157b2363b1ee
    
  - Snap for 6736586 from 17310693309dbf74f87fab1a5ecd64bbd6aaeac0 to rvc-qpr1-release
    
    Change-Id: I22f5a3bb021ffe9e43086e8017387d95a200e683
    
  - git: simplify commit message extraction command am: 7e07d8f6fd
    
    Original change: https://android-review.googlesource.com/c/platform/tools/repohooks/+/1383801
    
    Change-Id: Ie063537cd26e5e967160b4878cca3b4c87b7c0e0
    
  - Snap for 6730149 from 7aa7d112dcc23ee6f65186afea737fe0b9c30ad8 to rvc-qpr1-release
    
    Change-Id: I6fe2e82c512bf2e043fb8427ea2dd5f74e199b77
    
  - pre-upload: use first-parent diff for list of affected files am: ce8e83897b
    
    Original change: https://android-review.googlesource.com/c/platform/tools/repohooks/+/1383803
    
    Change-Id: Ie176a524ce0a8c77a8b7900cbc4f949a2fc4519a
    
  - Snap for 6729113 from 1a07824a1931021478891cf189f6ffb1b37f45a5 to rvc-qpr1-release
    
    Change-Id: I4094eb6514c37f8a09809a8add70e731d6a31ec3
    
  - git: use "git rev-list" to get a revision listing am: 2e1406dfa9
    
    Original change: https://android-review.googlesource.com/c/platform/tools/repohooks/+/1383802
    
    Change-Id: Ie436d3aa297c3410246571f7fe7c6ce2bdf7b3e4
    
  - git: simplify commit message extraction command
    
    Instead of using "git log <commit>^!", which means "perform a walk
    that includes <commit> and excludes its parents", perform a
    non-walking command.
    
    We could use "git log --no-walk <commit>" for this.  Instead, let's
    use the lower-level "git diff-tree", to get into the habit of using
    plumbing commands that try to support scripting by behaving simply and
    predictably.
    
    Noticed by code inspection.
    
    Change-Id: I167e0920c0c0f67d9def1bdbdd34bd88941193a5
    
  - pre-upload: use first-parent diff for list of affected files
    
    Otherwise, trying to upload a merge can fail with errors like
    
     ValueError: Failed to parse diff output: ::100644 100644 100644 4d2b33a 4d2b33a d63fea7 MM      BUILD
    
    because "git diff <foo>^!" returns a diff against all parents
    that DIFF_RE does not know how to parse.
    
    Reported-by: Matthew Maurer <mmaurer@google.com>
    Change-Id: Iafd846f083c0c078b383f7d48ad00cce896a404c
    
  - git: use "git rev-list" to get a revision listing
    
    As a lower-level plumbing command designed for scripting, this can be
    counted on to behave simply and predictably over time.
    
    Change-Id: I628727686898a3fa5441a2dc58f9edb867d2aec7
    
  - Snap for 6720487 from b76ba4222fee3654614689994fc5716020b4779f to rvc-qpr1-release
    
    Change-Id: I6647996d8a7d9c7e104c102c5266e674748129a3
    
  - Pull upstream cpplint.py from github.com/google/styleguide am: 7a814a1785
    
    Original change: https://android-review.googlesource.com/c/platform/tools/repohooks/+/1375269
    
    Change-Id: I07073b9adfb2f719906a8ec200f76bd5c1de91cb
    
  - Pull upstream cpplint.py from github.com/google/styleguide
    
    Update language to comply with Android's inclusive language guidance
    
    See https://source.android.com/setup/contribute/respectful-code for
    reference
    
    Bug: 161896447
    Test: None
    Change-Id: I7c18212291d7bfe57a0452a3d317a90cedd079c5
    
  - Snap for 6689685 from cfb0facf5c0a72007315c286c478f7fc48441032 to rvc-qpr1-release
    
    Change-Id: I2adf8060e33797ccb6227ae6cf5050de277ed01b
    
  - Snap for 6683212 from 33e3a95389cdd3117bbd7ed6f99685f62b5c0e3b to rvc-qpr1-release
    
    Change-Id: If76ce5e90d31720b6abca01e4cee1977260a66a8