Update git submodules
* Update external/google-benchmark from branch 'master'
  to 846b7549b6b43c6947f53b1e94968558d5a36830
  - Upgrade google-benchmark to dce3322a549650d18f50b5f1428a5942327ab6a5
    
    Test: make
    Change-Id: I07850ca99c79dd2225cb48821200a365b90e4d2c
    
  - Add support for z/OS XL compiler inline asm syntax (#1063)
    
    On s390 architecture, z/OS XL compiler uses HLASM inline assembly, which has different syntax and needs to be distinguished to avoid compilation error.
  - src/benchmark_register.h: add missing <limits> inclusion (#1060)
    
    Noticed missing header when was building llvm with gcc-11:
    
    ```
    llvm-project/llvm/utils/benchmark/src/benchmark_register.h:17:30:
      error: 'numeric_limits' is not a member of 'std'
       17 |   static const T kmax = std::numeric_limits<T>::max();
          |                              ^~~~~~~~~~~~~~
    ```
  - Add support for DragonFly BSD (#1058)
    
    Without this commit, compilation fails on DragonFly with the following message:
    
    ```
    /home/mneumann/Dev/benchmark.old/src/sysinfo.cc:446:2: error: #warning "HOST_NAME_MAX not defined. using 64" [-Werror=cpp]
    ^~~~~~~
    ```
    
    Also note that the sysctl is actually `hw.tsc_frequency` on DragonFly:
    
    ```
    $ sysctl hw.tsc_frequency
    hw.tsc_frequency: 3498984022
    ```
    
    Tested on:
    
    ```
    $ uname -a
    DragonFly box.localnet 5.9-DEVELOPMENT DragonFly v5.9.0.742.g4b29dd-DEVELOPMENT #5: Tue Aug 18 00:21:31 CEST 2020
    ```
  - Add CycleTimer implementation for M68K architecture (#1050)
    
    As per discussions in here [1], LLVM is going to get backend support on
    Motorola 68000 series CPUs (a.k.a M68K or M680x0). So it's necessary to
    add CycleTimer implementation here, which is simply using `gettimeofday`
    same as MIPS. This fixes #1049
    
    [1] https://reviews.llvm.org/D88389
  - Include github workflows status in README
  - Add support for JSON dumps of benchmark diff reports. (#1042). Fixes #737.
    
    NOTE: This is a fresh-start of #738  pull-request which I messed up by re-editing the commiter email which I forgot to modify before pushing. Sorry for the inconvenience.
    
    This PR brings proposed solution for functionality described in #737 
    
    Fixes #737.
  - Fixed pkg-config on other than Ubuntu GNU/Linux distributions. (#1043)
    
    Signed-off-by: Vitaly Zaitsev <vitaly@easycoding.org>
  - Bind benchmark builder to Python (#1040)
    
    * Fix setup.py and reformat
    
    * Bind benchmark
    
    * Add benchmark option to Python
    
    * Add Python examples for range, complexity, and thread
    
    * Remove invalid multithreading in Python
    
    * Bump Python bindings version to 0.2.0
    
    Co-authored-by: Dominic Hamon <dominichamon@users.noreply.github.com>
  - Add workflow to exercise bindings (#1041)
    
    * Initial version to try to run python bindings example
    
    * python indent issue in setup.py
    
    * better naming
  - Bind more State methods/attributes to Python (#1037)
    
    * Bind Counter to Python
    
    * Bind State methods to Python
    
    * Bind state.counters to Python
    
    * Import _benchmark.Counter
    
    * Add Python example of state usage
    
    Co-authored-by: Dominic Hamon <dominichamon@users.noreply.github.com>