Update git submodules
* Update external/autotest from branch 'master'
  to 4df0a41d937c40222522995c0a9d2c35c6ca8db0
  - Revert "[Autotest][Py3] Update utils.py to support Python3" am: b8456209ae
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I052d045208355f5442e17a55ef5185af2f586257
    
  - Revert "[Autotest][Py3] Update utils.py to support Python3"
    
    This reverts commit a1ae931843904c1b258e0fbd73276c966ce3a70d.
    
    Reason for revert: I think this is breaking firmware tests, which ironically got added to this CQ the day after this merged!
    
    https://stainless.corp.google.com/search?view=matrix&row=test&col=build&first_date=2020-12-09&last_date=2020-12-15&test=%5Efirmware_Cr50&exclude_cts=true&exclude_not_run=false&exclude_non_release=true&exclude_au=true&exclude_acts=true&exclude_retried=false&exclude_non_production=false
    
    Original change's description:
    > [Autotest][Py3] Update utils.py to support Python3
    >
    > To support python3, utils.py must encode the computed hash,
    > and decode the data being read from the pipes. Without it TypeErrors occur
    > when trying to write to the buffers. This IS python2 compatible.
    > """
    > autotest/files/autotest_lib/client/common_lib/utils.py", line 303, in process_output
    >     buf.write(data)
    > TypeError: string argument expected, got 'bytes'
    >
    > """
    >
    > The changes have been tested in python2 and python3, along with the
    > utils_unittest
    >
    > Ran 167 tests in 12.714s
    >
    > OK
    > All passed!
    >
    > BUG=chromium:990593
    > TEST=dummy_Pass (python2 and 3) utils_unittest
    >
    > Change-Id: I6986005a43297d1584b8542ec0b1ce8e6861eb0c
    > Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/2547640
    > Tested-by: Derek Beckett <dbeckett@chromium.org>
    > Reviewed-by: Greg Edelston <gredelston@google.com>
    > Reviewed-by: Gregory Nisbet <gregorynisbet@google.com>
    > Commit-Queue: Derek Beckett <dbeckett@chromium.org>
    
    Bug: chromium:990593
    Change-Id: Ia667308957d12e8568291dda8d5cb5c702b6859f
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/2593727
    Reviewed-by: Derek Beckett <dbeckett@chromium.org>
    Reviewed-by: Jorge Lucangeli Obes <jorgelo@chromium.org>
    Commit-Queue: Derek Beckett <dbeckett@chromium.org>
    Commit-Queue: Jorge Lucangeli Obes <jorgelo@chromium.org>
    Tested-by: Derek Beckett <dbeckett@chromium.org>
    Auto-Submit: Derek Beckett <dbeckett@chromium.org>